### ISSUE TITLE
Bug with badges of verified accounts

### ISSUE THREAD

**Issue by ChevalierNumerique** [eramdam/BetterTweetDeck#101]
Look at the screenshot ;) 

http://image.noelshack.com/fichiers/2016/41/1476103456-screenshot2016-10-10-14-42-38.png

**Comment by LeoColomb** [comment]
Actually the bug is about profil pictures, managed differently in the new TD version.

![image](https://cloud.githubusercontent.com/assets/846943/19244229/928d1cc2-8f1b-11e6-8359-8b53af34909a.png)

**Comment by eramdam** [comment]
@LeoColomb I'm not sure what I should see on the 1st screenshot?
