### ISSUE TITLE
gfycat preview is buggy

### ISSUE THREAD

**Issue by Primeey** [eramdam/BetterTweetDeck#103]
Tweet example: https://twitter.com/Ceweal_/status/786669232301936640
What happens: https://www.youtube.com/watch?v=km79ctF09T4 When you click to watch it there's a loading icon in the centre which never stops playing and the gfycat plays above it in a very small area

**Comment by eramdam** [comment]
@Primeey Are you up-to-date? I just tried on last version (3.0.19) and it's correctly displaying

**Comment by Primeey** [comment]
Yes v 3.0.19?

**Comment by eramdam** [comment]
Okay. Will investigate when I can. Does it happen only on gfycat?

**Comment by Primeey** [comment]
Yeah only gfycat. I just tried reinstalling better tweetdeck but that didn't fix it.

**Comment by eramdam** [comment]
That's weird because everytime I try I can't reproduce. I'll send you a test build later today so you can try again.

**Comment by eramdam** [comment]
I did a fix on `3.0.20`, will be deployed soon.
