### ISSUE TITLE
Contribution guidelines for features

### ISSUE THREAD

**Issue by pixeldesu** [eramdam/BetterTweetDeck#106]
Something I came across while contributing my feature to BTD was that a contribution guideline for feature additions/bug fixes is missing, the current guidelines only covers bug reports.

These guidelines should cover if there are any special conventions (commit/branch names, code style) to follow and what the general procedure of working, submitting, testing and approval of features is.

**Comment by eramdam** [comment]
Fixed now that https://github.com/eramdam/BetterTweetDeck/pull/107 is merged (kinda)
