### ISSUE TITLE
Improving the dark color scheme

### ISSUE THREAD

**Issue by pixeldesu** [eramdam/BetterTweetDeck#108]
_For starters, this is pretty much a question if BTD wants to go as far as changing a major aspect of the client, in this case the coloring of the dark theme._

I must say, I really use dark themes quite a lot, especially on mobile when the light interfaces tend to burn out my eyes when I'm browsing Twitter in the night, but for long the dark color scheme of TweetDeck has bugged me. 

I'm not really a fan of the bland gray-tones, and Twitter themselves aren't either, they probably just don't bother changing it.

A change I'd like to suggest (or even implement if @eramdam is fine with this) would be adapting the official dark color scheme (the dark blue-ish one) to TweetDeck, because that looks way nicer than what we currently have available.

**Comment by eramdam** [comment]
I thought _a lot_ about this. And I'm not very confident about replacing the current one completely. I guess I could just add another variation, that would be a safer option. Although I know for sure some colors are still blue-grayish in the current dark theme and could be improved :D

**Comment by pixeldesu** [comment]
We easily could achieve this with a option that only works with `.btd__{cool option name}[data-btdtheme="dark"]` to just change up dark mode (cool additional data attribute there, by the way), so the implementation itself shouldn't be too hard, even if we make it just optional.

**Comment by pixeldesu** [comment]
Considering TweetDeck is on a spree of constant updates again, this is not feasible with the amount of (possible) UI changes with all the classes changing at random.

Probably something for an userstyle, now that Night Mode has arrived on web Twitter.
