### ISSUE TITLE
Autoplaying occurring in quoted Tweets

### ISSUE THREAD

**Issue by snowbound** [eramdam/BetterTweetDeck#114]
Noticed that if one has the option to auto play animated GIFs it does not prevent animated gifs in requoted tweets from looping endlessly.

**Comment by eramdam** [comment]
@snowbound I guess you meant?

> Noticed that if one has the option to **disable** auto play animated GIFs it does not prevent animated gifs in requoted tweets from looping endlessly.

**Comment by snowbound** [comment]
Oops right you are. Preventing the endless looping of animated gifs appears to be something that Tweetdeck devs do not want to implement. I has been requested by numerous users as something they wanted in the software.

**Comment by eramdam** [comment]
Now that TweetDeck made an actual setting for that. I'm closing this issue.
