### ISSUE TITLE
Paste images into DMs

### ISSUE THREAD

**Issue by lucaznunes** [eramdam/BetterTweetDeck#119]
What about pasting images?

**Comment by eramdam** [comment]
You can already paste them inside tweets... https://twitter.com/BetterTDeck/status/818729297942716417

Still missing in DMs though

**Comment by lucaznunes** [comment]
Hope you can get the paste inside DMs. It will be a great feature. I'm learning JavaScript, hope I can contribute to your project in the future.

**Comment by eramdam** [comment]
Was added by 3.3.0
