### ISSUE TITLE
Change title to reflect notifications

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#135]
The main challenge would be to have a list of unseen notifications but the rest should be pretty straightforward

https://twitter.com/Leifinator/status/843929275761922049

**Comment by pixeldesu** [comment]
I don't think the amount of unseen notifications itself is required, or...it would be too complex to check for exactly that.

What you can always check for tho are the per-timeline icons that show new content ( `.is-new` in the sidebar)

It would count the main timeline/home then, tho.

**Comment by eramdam** [comment]
That could be a way. I will see if I can track down what event triggers the notifications, maybe I could just hook to it and act on the title accordingly 🤔

**Comment by pixeldesu** [comment]
Added in #181
