### ISSUE TITLE
"Share on TweetDeck" does not work with Vivaldi browser's Web Panel

### ISSUE THREAD

**Issue by kakakaya** [eramdam/BetterTweetDeck#136]
I recently installed BetterTweetDeck on Vivaldi browser. But, I noticed that "Share on TweetDeck" (right click menu) does not work with TweetDeck which is running in Vivaldi's Web Panel.  ( If I open TweetDeck on normal tab, it works well. )

Is this a bug? Or, is it impossible to share on TweetDeck in Web Panel?

**Comment by kakakaya** [comment]
My environment:

version: 3.3.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.88 Safari/537.36 Vivaldi/1.7.735.46
configure dump:
```json
{
  "css": {
    "actions_on_hover": true,
    "actions_on_right": true,
    "bigger_emojis": true,
    "collapse_dms": false,
    "gray_icns_notifs": false,
    "hide_context": false,
    "hide_url_thumb": true,
    "minimal_mode": false,
    "no_bg_modal": true,
    "no_col_icns": false,
    "no_scrollbars": false,
    "round_pic": true,
    "show_provider_indicator": false,
    "show_verified": true,
    "slim_scrollbars": false,
    "small_icns_compose": true,
    "usrname_only_typeahead": true
  },
  "custom_columns_width": {
    "enabled": false,
    "size": "250px"
  },
  "custom_ts": {
    "full": "",
    "short": ""
  },
  "flash_tweets": {
    "enabled": true,
    "mode": "mentions"
  },
  "full_aft_24": true,
  "installed_date": 1490627822086,
  "installed_version": "3.3.0",
  "nm_disp": "inverted",
  "no_gif_pp": false,
  "no_hearts": false,
  "no_tco": true,
  "share_item": {
    "enabled": true,
    "short_txt": false
  },
  "stop_gifs": true,
  "thumbnails": {},
  "ts": "relative"
}
```

**Comment by eramdam** [comment]
@kakakaya To be quite honest, I never tested the extension under Vivaldi. What's the "Web Panel" in Vivaldi exactly? I'll give it a try to see what's going on exactly.

**Comment by kakakaya** [comment]
"Web Panel" is Vivaldi's original feature. It displays web page in side bar, so useful to use with TweetDeck, Gmail or something.
https://vivalditips.com/efficiency/panels
![2017-03-28 02_38_31-vivaldi web browser - wikipedia](https://cloud.githubusercontent.com/assets/3298037/24369709/d0a6dd5e-135f-11e7-82b2-2f285563c88f.png)

In my guess, this Web Panel might be independent from usual tabs, so BetterTweetDeck can't find TweetDeck if it is in the Web Panel.

Vivaldi can use Google Chrome's extensions, so I thought that BetterTweetDeck extension also will work. But, if you don't support except of Google Chrome and Opera, that's OK.

**Comment by eramdam** [comment]
Well, the API is supposed to be the same but maybe Vivaldi's Web Panel is not being listed as a tab? I'd have to check that out. Is this the only thing not working though? :D

**Comment by kakakaya** [comment]
I'm using BetterTweetDeck with Vivaldi for some hours, and it works pretty well  (except this bug) like Google Chrome version! On the other hand, the TweetDeck itself has problem: sometime popup window misses when running in Web Panel.

**Comment by eramdam** [comment]
As I expected, Vivaldi doesn't expose the Web Panel as a regular tab within `chrome.tabs` so there's not much I can do. I will try to open a bug request on their end so they know about the issue at least.

**Comment by eramdam** [comment]
Closing this as Vivaldi still didn't gave me any answer and I'm not expecting any anytime soon. Sorry!
