### ISSUE TITLE
Streamable videos are extremely tiny

### ISSUE THREAD

**Issue by Primeey** [eramdam/BetterTweetDeck#138]
So this seems to be a common problem I'm always running into eh? First it was gfycat now it's videos from Streamable. When you click on a streamable video it opens in a tiny thumbnail and there's a constantly loading icon under it. It also doesn't auto play which I'm not sure is intended or not

[Screenshot ](http://i.imgur.com/xl2vTsK.png) ([While playing](http://i.imgur.com/XtMoxWL.png))
[Tweet example](https://twitter.com/ethe32/status/846504051856560128)

**Comment by eramdam** [comment]
I know. I'm working on a total revamp of the modals in another branch because having responsive iframes in the current markup of TD's modals is a pain in the @#$! Hopefully I should be able to release this in the coming weeks.
