### ISSUE TITLE
Feature request: DK style date

### ISSUE THREAD

**Issue by rubin110** [eramdam/BetterTweetDeck#14]
YYYY/MM/DD

Thanks. :D

**Comment by eramdam** [comment]
@rubin110 
I'm on the brink of writing the feature for the 3.0 version of BetterTweetDeck, and I noticed something: Isn't it a problem to not have infos about the time of the day when it comes to tweets? :D 

I mean, I'm all open to this feature but I think it might be problematic to lose timing precision on a Twitter client

**Comment by eramdam** [comment]
Closing in favor of https://github.com/eramdam/BetterTweetDeck/issues/48 (However discussion can continue since it could be added as a preset)
