### ISSUE TITLE
Verification before send tweets

### ISSUE THREAD

**Issue by PataPataPata** [eramdam/BetterTweetDeck#141]
I think Tweetdeck had this in the past: A checkbox under the text box, to confirm tweeting.

It's useful when one is running a lot of accounts (Personal and business, e.g.), and don't want to tweet to a wrong account. Of course this option should be optional.

(P.S: Thanks for your great work, eramdam.)

**Comment by eramdam** [comment]
It's still there, you just have to enable "Confirmation step" on your account in the Accounts view

![image](https://cloud.githubusercontent.com/assets/1409924/24583283/cf3a422e-16f9-11e7-88ef-bb54af0ddd62.png)
