### ISSUE TITLE
Mastodon (or any gnusocial) column

### ISSUE THREAD

**Issue by riking** [eramdam/BetterTweetDeck#143]
I'm only half joking here

Okay, spec: A new column type that would display a feed from a gnusocial instance such as mastodon.social. Column setup would involve granting permission for extension access and checking that the displayed feed is correct.

**Comment by eramdam** [comment]
As far as I like the idea, it would be a pain to develop since I'd have to basically write to the very core of TweetDeck to allow such a thing. Sorry but no, this is clearly out of scope. Unless someone finds a miracle way, this will be a `wontfix`.
