### ISSUE TITLE
Work on Better TweetDeck's website

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#149]
I'm opening this issue so I can try to make the process on this transparent. This issue itself is a WIP. I'll be adding more soon.

**Comment by Sophia2329** [comment]
What's this going to be about?

**Comment by eramdam** [comment]
A website for better.tw. I have a private repo for it and it's getting closer to release so I'll be able to close this soon.

**Comment by eramdam** [comment]
I can finally close this because the website is live https://twitter.com/BetterTDeck/status/945035740236283905 and its source is at https://github.com/eramdam/better.tw
