### ISSUE TITLE
Add an option to increase search list width

### ISSUE THREAD

**Issue by zspitzer** [eramdam/BetterTweetDeck#151]
there's no reason the search dialog results need to be quite narrow

can we get an option to override the width (and maybe compact the whitespace) between tweets?

![image](https://cloud.githubusercontent.com/assets/426404/25848299/191f1e66-34fd-11e7-9ff9-44764b0839d6.png)

**Comment by eramdam** [comment]
Since TweetDeck recently killed the "old search" hack, I'm afraid this is not very relevant anymore so I'm closing the issue.
