### ISSUE TITLE
Limiting Tweets

### ISSUE THREAD

**Issue by eorroe** [eramdam/BetterTweetDeck#153]
I love twitter, but sometimes I'm addicted. I do use some extensions to help me block it after a certain time but would love if this extension had an option to limit the amounts of tweets I can scroll per column.

For example, I only want to scroll through 50-100 tweets and then be done, it'd be awesome if BetterTweetDeck somehow limited the number of tweets loaded that way I don't keep scrolling and move on.

Using site blockers sometimes can be counterproductive because I actually sometimes **need** to reopen TweetDeck for work.

So either a global setting for each column or if possible being able to set a number for each column?

**Comment by eramdam** [comment]
I get the whole idea, but it would be awwfully hard to implement without actually breaking anything inside TweetDeck. Sorry. :/
