### ISSUE TITLE
Can RT but RT box won't close until I "X" it

### ISSUE THREAD

**Issue by Philosocrat** [eramdam/BetterTweetDeck#158]
I can RT, but after making several successful retweets, the RT box stays in place after clicking the "Retweet" button, so then I have to "X" it to make it go away; then I have to reload TweetDeck, and this cycle begins again...  I'm using @googlechrome in Windows 10 on my Dell 8900.  HELP! Anyone?

**Comment by eramdam** [comment]
@Philosocrat Is this happening without Better TweetDeck enabled? Because nothing in my code touches this part of TweetDeck.

**Comment by Philosocrat** [comment]
No, *with* Better TweetDeck. Thanks for replying.

**Comment by eramdam** [comment]
Okay. I will try to investigate, thx

**Comment by eramdam** [comment]
@Philosocrat I tried to RT ~20 tweets in a row and I could not reproduce. Next time it happens, can you open the [Chrome Console](https://developers.google.com/web/tools/chrome-devtools/console/) and show me what's on there? Thanks.

**Comment by Philosocrat** [comment]
The latest iteration of Better (?) TweetDeck has greatly diminished the frequency of the occurrence of this issue, although it happened at least a couple times earlier today. As you instructed, I opened Chrome Console and did quite a few RTs w/o the problem occurring -- many more RTs than I thought would be enough to "set it off". So I'll keep monitoring it and will post to you the saved Console file when (if?) it recurs. And thanks again so much for helping me out. :)

**Comment by Philosocrat** [comment]
I spoke too soon. Here's the log file after the problem just occurred again. I hope it's what you want. I renamed it from a LOG to a TXT file so this webpage would accept it. -- Thanks.
[tweetdeck.twitter.com-1495927765449.txt](https://github.com/eramdam/BetterTweetDeck/files/1033879/tweetdeck.twitter.com-1495927765449.txt)

.

**Comment by eramdam** [comment]
@Philosocrat it seems like it's an error on TweetDeck's side, as there's a [414 HTTP error](https://httpstatuses.com/414). Meaning your browser tried to perform a request with an URI too long for the server to handle. I don't know why it happened though, and nothing in my code would modify that so I guess you discovered a weird TweetDeck edge case :/ 

There's also a 404 error
```
api.twitter.com/1.1/statuses/retweet/868596722502598656.json Failed to load resource: the server responded with a status of 404 ()
```

So I guess it means that somehow the tweet you tried to RT does not exist anymore (?!?).

I don't know what to say, this all sound like weird TweetDeck/Twitter issue and I can't do much. Sorry!

**Comment by Philosocrat** [comment]
That's OK. You gave it a shot. I just have to reload TweetDeck when it happens -- pretty fast on my machine -- so I'll manage.  Thanks once again!
