### ISSUE TITLE
Display Replies, RTs and Likes numbers

### ISSUE THREAD

**Issue by kibeloko** [eramdam/BetterTweetDeck#160]
![image](https://cloud.githubusercontent.com/assets/29057292/26572397/2231818a-44f0-11e7-8c11-02294e6b00ae.png)

Having the ability to see those numbers without having to click inside the tweet would be amazing.

Cheers :)

**Comment by eramdam** [comment]
TweetDeck doesn't populate those data and there is no way for me to get them. Sorry 😞
