### ISSUE TITLE
Custom Link Shortening

### ISSUE THREAD

**Issue by denvoros** [eramdam/BetterTweetDeck#161]
So, a few years ago, Tweetdeck had the option of using your own Link Shortening service, as long as you had a proper URL and a GET request would return a text url. I know that TweetBot has this service, but I'd love to have it in Better Tweetdeck. Please and thank you!

**Comment by eramdam** [comment]
The thing is: I don't have a proper way to plug the extension into the tweet posting process. And even if it was possible I feel like this would raise understandable concerns regarding privacy. I could look into making that an option without having to handle personal data, but that doesn't seem very possible. 

@pixeldesu by any chance, did you play with that part of TweetDeck's code? 😛

**Comment by pixeldesu** [comment]
I did.

And...while I have read specifics for shortening services, I have no idea how easy it would be to plug another service in...and have TweetDeck support it.

---

Okay, I just checked...and there is no real modularity in there.

It would have to be patched in somehow, and getting that done...uhh, yeah, that would be adventurous.

**Comment by denvoros** [comment]
Well, thanks for looking into it. I appreciate it.
