### ISSUE TITLE
Disable "show more" in columns

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#164]
https://github.com/eramdam/BetterTweetDeck/pull/163#issue-235885770

> It's a nightmare to have that "feature".
> Make me lose plenty of time searching in my columns.
> More than one hour to find my last tweet replied.
> I'm sure you can disable that terrible thing.
> PLEASE I BEG YOU TO  HAVE AN OPTION TO DISABLE IT !
>
> ![image](https://user-images.githubusercontent.com/24864768/27135428-124f7138-50de-11e7-8b60-201302722e70.png)
>
> I've found this app can do that...
> https://chrome.google.com/webstore/detail/colordeck-for-tweetdeck/jgoilgghdiafcdpgaddhfnlnhjhiejjl/reviews?hl=en
> 
> But i trust in you more than any one.
> Please have this feature. I beg you.

**Comment by eramdam** [comment]
@rx65m further discussion regaring "show more" will continue here

**Comment by eramdam** [comment]
I inspected the way ColorDeck does this and they basically trigger a click on the "show more" button. This probably works but it is awfully dirty so I'll experiment with it but I don't like that way of doing.

**Comment by rx65m** [comment]
I'm using ColorDeck now (with this function only), together with
BetterTweetDeck. Although it is not a clean solution, it works fine for me.
At least I don't lose my last working tweet.
I know you'll find a better solution.
Thank you in advance.
By the way, you are doing a fantastic job!

**Comment by pixeldesu** [comment]
@eramdam quick rundown on how "show more" works internally:

* we basically have an event listening to clicks on `.js-expand-gap`
* when fired we are getting the nearest column, to get the column data key
* with which we get our respective column data model
* that we then use to run `column.fillGap(id)` where id is the chirp-id of the gap element, mostly a `gap_` based one with an unique ID at the end

Just from reading the relevant pieces of code, I couldn't track down when and how gaps are added into columns, so you'd still have to check on them being inserted.

**Comment by michaelfresco** [comment]
It's hard to read back 60 minutes now.
