### ISSUE TITLE
Add support for old icons

### ISSUE THREAD

**Issue by Scrxtchy** [eramdam/BetterTweetDeck#166]
Tweetdeck did a considerable design change, better tweetdeck still handles it well even so.
But I would like to see support for the old icon set, these outline Icons are drilling my head in

**Comment by eramdam** [comment]
I can not promise anything in that regard since it might require a lot of work and maintenance to keep up with the updates. And the day TweetDeck introduces new icons: I'm out of luck

**Comment by Zhangsun321** [comment]
id sell my firstborn to pay you....

**Comment by chylex** [comment]
Hey, Twitter keeps old icons on their servers, so until they remove them this'll work -- https://github.com/chylex/TweetDuck/blob/master/Resources/Plugins/edit-design/browser.js#L408-L504

**Comment by pixeldesu** [comment]
@chylex The problem with this approach is that we don't know how long these assets stay on their servers.

They probably purge really rarely, but if they do, this would work in a pretty bad way.

I thought about maybe writing like a asset mirror that irregularly saves files so it can be used by TD extension scripts. And to also keep track of what changes (like we already do with [DeckHack/deckcheck](https://github.com/DeckHack/deckcheck))

But that said, it seems like a bit of an over-ambitious idea right now.

**Comment by Scrxtchy** [comment]
You it hurt (or be compatible) to pack the font file into the Web extension archive?

**Comment by chylex** [comment]
If you download the file, you should be able to encode it to base64 and use that instead of the URL in case they remove it, right?

**Comment by Scrxtchy** [comment]
done;
https://gist.github.com/Scrxtchy/88172a9f1f08a9f41270a17eaab339af

**Comment by eramdam** [comment]
I already have a few backup copies of the old assets (CSS and fonts), in fact, I'm already re-embedding the old font so I can use the star icon when needed. So restoring the old icons would be a matter of re-adding CSS rules.
