### ISSUE TITLE
Decider override breaks TweetDeck

### ISSUE THREAD

**Issue by pixeldesu** [eramdam/BetterTweetDeck#172]
So, we are now getting this _fancy_ error output from TweetDeck, once in a while telling us that something is broken with `TD.decider.updateFromBackend()` and...yes, it is.

In the decider override, we are changing the function and so every call from TweetDeck itself is throwing an error because `updateFromBackend` now only seems to work specifically at the point BTD is using it for. (if that is even the case)

I suggest we switch over to the second method of overriding deciders (using `TD.config.decider_overlay`), which seems to be breaking less stuff..as we are not wrapping functions.

You can replicate this issue with running `TD.decider.updateFromBackend()` in the console. Or just leaving TweetDeck open for a while.

**Comment by eramdam** [comment]
Fixed by https://github.com/eramdam/BetterTweetDeck/pull/173 being merged
