### ISSUE TITLE
Ability to pause animated gifs from other sources

### ISSUE THREAD

**Issue by Ben-Lai** [eramdam/BetterTweetDeck#182]
Currently, the native handling of animated gifs in Tweetdeck allow for pausing of the animated gif. Could this functionality be included in the 'Display thumbnails from other sources' that BTD offers?

**Comment by eramdam** [comment]
Unfortunately, this would require said sources to serve the GIFs in the MP4 format like Twitter/TweetDeck does, otherwise there's no (easy) way to play/pause a gif.
