### ISSUE TITLE
Add support for other reverse image search engines

### ISSUE THREAD

**Issue by pixeldesu** [eramdam/BetterTweetDeck#183]
Fairly simple. Let's extend the button on images with more buttons!

There are not a lot other image searches, but...for our friends of digital artwork a search engine like [SauceNAO](https://saucenao.com/) would probably be appreciated.

Should be a fairly easy task, we just need to extend the template of the image search button, we have all stuff we need for building the URL there already.

_Why am I even opening issues for features I most likely implement myself?_

**Comment by EntranceJew** [comment]
some provider info:
```
https://saucenao.com/search.php?urlify=on&frame=1&hide=0&database=999&url=https://pbs.twimg.com/media/DKZnPRAW0AA_2VR.jpg:orig

https://iqdb.org/?url=https://pbs.twimg.com/media/DKZnPRAW0AA_2VR.jpg:orig

https://tineye.com/search/?sort=score&order=desc&url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FDKZOijnW4AAuxKs.jpg%3Aorig
```

`pluginver=chrome-1.2.0` tineye plugin uses this, also has:

```js
{
"best_match": "&sort=score&order=desc",
"most_changed": "&sort=score&order=asc",
"biggest_image": "&sort=size&order=desc",
"newest": "&sort=crawl_date&order=desc",
"oldest": "&sort=crawl_date&order=asc",
}
```

**Comment by eramdam** [comment]
Seems like TweetDeck removed the feature entirely? Do we want to keep this open? I don't think re-implementing the feature would be too hard but I know I didn't notice it was gone for a while 🙈

**Comment by pixeldesu** [comment]
Oh yeah, it's gone, didn't even notice that myself. I'll close this!
