### ISSUE TITLE
Random Black Box in Direct Messages

### ISSUE THREAD

**Issue by ipugsiehd** [eramdam/BetterTweetDeck#184]
While on Tweetdeck using The BetterTDeck extension, in either minimalistic mode or standard, in the box where you will write your reply, a random useless box will appear in the top left, this is NOT caused by any other extensions.
![image](https://user-images.githubusercontent.com/29990313/27979730-22272b1a-6370-11e7-8c58-8abe8259f84f.png)

**Comment by eramdam** [comment]
@ipugsiehd are you sure it's not caused by something else? Because I can't see anything on my end 
![image](https://user-images.githubusercontent.com/1409924/27981589-056fb38e-6343-11e7-9674-45e5d7ee205e.png)

**Comment by ipugsiehd** [comment]
Hmm. I'll check again.

**Comment by ipugsiehd** [comment]
It's still there with all extensions except BTD off, it's whenever you open
a conversation it can either appear randomly, or only when you open a
conversation.

**Comment by eramdam** [comment]
I'm closing this as I never got any other reports regarding this.
