### ISSUE TITLE
Fractions of a second display properly, then are zeroed out

### ISSUE THREAD

**Issue by JerryArr** [eramdam/BetterTweetDeck#188]
When new tweets are displayed, and when using custom timestamps with the S/SS/SSS, they show properly for a few seconds, change to "now", then turn to zero(es).

Fractional seconds in direct messages seem to work perfectly.

**Comment by eramdam** [comment]
@JerryArr hum, I feel like it's related to the re-render code TweetDeck pushed a few weeks ago. However, do the timestamps go back to your custom format after ~10seconds? That's the delay I use to re-apply timestamps when necessary.

**Comment by JerryArr** [comment]
No, they stay zeroed.

**Comment by eramdam** [comment]
@JerryArr I just understood what the issue was about 😅  😁  I just tried and I feel like tweet timestamps are not precise down to the miliseconds, at least TweetDeck's ones are not, hence why `S/SS/SSS` returns 0 everytime :/ There's not much I can do here.

**Comment by eramdam** [comment]
Just dug into the data models and yup, tweets have their timestamps precise down to the milliseconds while DMs don't. 

![image](https://user-images.githubusercontent.com/1409924/27990340-7536a8ce-6408-11e7-9f2a-da9c1c2594db.png)

**Comment by eramdam** [comment]
I'm closing the issue since there's literally nothing I can do about it.
