### ISSUE TITLE
Adding .gif support + Image replies

### ISSUE THREAD

**Issue by IncredibleOrb** [eramdam/BetterTweetDeck#191]
I absolutely LOVE BTD but the only reason I stray from the extension, and venture on to twitter.com at times *shudders*, is the fact that you can't add .gifs OR reply to incoming mentions with an image reply.

These two features would be awesome to have, especially since I communicate heavily with .gifs.

Thank you for all your hardwork!

**Comment by IncredibleOrb** [comment]
And being able to use emojis in mention replies as well!

**Comment by eramdam** [comment]
@IncredibleOrb Well, you can click the "popout" icon to take your reply inside the big composer. That's probably not what you want right now but adding the image upload/emoji stuff in the "small composer" is clearly no easy task 
![image](https://user-images.githubusercontent.com/1409924/28128050-431983e2-66e3-11e7-9b59-ee8785c8c6b2.png)
