### ISSUE TITLE
"Revert to the old replies style" broken with latest TweetDeck update

### ISSUE THREAD

**Issue by causio** [eramdam/BetterTweetDeck#194]
Looks like whatever TweetDeck changed in its last revision within the last day or two has broken the "Revert to the old replies style" feature. Tried to uncheck/recheck to re-apply it, but it doesn't work anymore.

**Comment by pixeldesu** [comment]
They got rid of a feature switch we were using to revert it. With the removal of that switch it now gets implemented without a real way for us to revert it, so we have to get in hard and change internal functions or templates to get the old style back-- in at least some way.

**Comment by eramdam** [comment]
This is a duplicate of https://github.com/eramdam/BetterTweetDeck/issues/155 in a way.

**Comment by eramdam** [comment]
Fixed by https://github.com/eramdam/BetterTweetDeck/pull/196 Will be in next release.
