### ISSUE TITLE
3.4.1: "Apply a custom width for columns" not working

### ISSUE THREAD

**Issue by Athanasius** [eramdam/BetterTweetDeck#199]
Since just now getting the update from 3.4 to 3.4.1 suddenly my columns are the, presumably, default width, rather than the 50% I have set via the Settings > Interface > "Apply a custom width for columns" option.

I've tried editing this to a different value and saving, toggling it off, saving then back on and saving, all with reloads after the save and it makes no difference.  Also trying 33% rather than 50% doesn't do anything.

This is on Windows 10 Chrome "Version 60.0.3112.78 (Official Build) (64-bit)" with the BTD extension.

There's an error on the JS console:

Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CgkvLwoJdmFyIEdhcSA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglHYXEucHJvdG90eXBlLk5hID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5PID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5TYSA9IG5vb3BmbjsKCUdhcS5wcm90b3R5cGUuVGEgPSBub29wZm47CglHYXEucHJvdG90eXBlLlZhID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fY3JlYXRlQXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0QXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2FxLnByb3Rv...ZuOwoJR2F0LnByb3RvdHlwZS5oYiA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUubGEgPSBub29wZm47CglHYXQucHJvdG90eXBlLm9hID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5wYSA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUudSA9IG5vb3BmbjsKCXZhciBnYXQgPSBuZXcgR2F0KCk7Cgl3aW5kb3cuX2dhdCA9IGdhdDsKCS8vCgl2YXIgZ2FxID0gbmV3IEdhcSgpOwoJKGZ1bmN0aW9uKCkgewoJCXZhciBhYSA9IHdpbmRvdy5fZ2FxIHx8IFtdOwoJCWlmICggQXJyYXkuaXNBcnJheShhYSkgKSB7CgkJCXdoaWxlICggYWFbMF0gKSB7CgkJCQlnYXEucHVzaChhYS5zaGlmdCgpKTsKCQkJfQoJCX0KCX0pKCk7Cgl3aW5kb3cuX2dhcSA9IGdhcS5xZiA9IGdhcTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://*.twitter.com https://*.twimg.com https://ssl.google-analytics.com https://api-ssl.bitly.com".

I have no idea if that's new or related.

**Comment by Athanasius** [comment]
A forced refresh and fully restarting Chrome hasn't helped either.

**Comment by Athanasius** [comment]
Aha, inspecting things the CSS shows:

"    width: 50%px !important;" with an error marker, the mouse-over of which correctly says "Invalid property value", i.e. the "px" shouldn't be there.  Is percentage not going to be supported for this any more ?

**Comment by Dragonchasers** [comment]
Yeah I had 500px in there and it stopped working,. Changing it to just 500 seemed to fix it.

**Comment by eramdam** [comment]
@Dragonchasers @Athanasius it was a bug in my code that was checking for valid CSS values. I removed the code in 3.4.2 which is deploying as I speak. Should be fixed.
