### ISSUE TITLE
Ability to change shortcuts?

### ISSUE THREAD

**Issue by dmix** [eramdam/BetterTweetDeck#20]
I'm an avid Vim user and would love to be able to switch from arrow keys to jkhl.

**Comment by eramdam** [comment]
I like the idea, I will look into the feasibility of this, but as noted it sounds like something tricky.

**Comment by leonstafford** [comment]
for anyone still in need of this, now works without needing to hit the mouse at all, jump straight into your h,j,k,l-smashing: [https://github.com/leonstafford/tweetdeck-homerow-shortcuts](https://github.com/leonstafford/tweetdeck-homerow-shortcuts) / [https://addons.mozilla.org/en-US/firefox/addon/tweetdeck-homerow-shortcuts/](https://addons.mozilla.org/en-US/firefox/addon/tweetdeck-homerow-shortcuts/)
