### ISSUE TITLE
Add the ability to sort tweets in a column by the amount of retweets/likes it has

### ISSUE THREAD

**Issue by llyyr** [eramdam/BetterTweetDeck#201]
And maybe also the ability to fetch x tweets in the column before sorting. Mostly useful for lists with anime girls, cats, dogs etc.

**Comment by pixeldesu** [comment]
Considering TweetDeck columns work with having two "storages" to hold tweets, this would be a pretty expensive action to take.

One storage holds the IDs, and with that the sorting. Another storage holds the actual tweets, mapped to the IDs.

So, to sort them, we would always need to check on new stuff coming in, then look through all tweets and their like/retweet counts and with those values at hand, sort the ID storage.

Looks like a bit too overblown for a feature for BTD.
