### ISSUE TITLE
Locking columns

### ISSUE THREAD

**Issue by Stanzilla** [eramdam/BetterTweetDeck#209]
Locking would disable being able to move columns (duh 😄 ) and (that's the important part) hide the move indicators. (they are really ugly) and as a bonus maybe hide the column number in the header, too.

**Comment by viki53** [comment]
The number in the header has different roles, as it's also used as a reminder for keyboard shortcuts. 

Though I agree locking a column could be a good idea, there's a lot to consider (can you still move an unlocked column before a locked one, for example?)
