### ISSUE TITLE
Add Tweetmarker

### ISSUE THREAD

**Issue by Twilightssuperb** [eramdam/BetterTweetDeck#22]
Hello. AFAIK, TweetDeck doesn't have connection with Tweetmarker service. Meanwhile it's so useful tool. Due to Tweetmarker I can jump to last unread tweet at next launch. It works like bookmark at any twitterfeed. Lots of mobile or OS X clients have support of Tweetmarker. For example, Plume and Janetter have (tweetmarker.net).

**Comment by Apph3x** [comment]
I have this in my local copy of this - it's lag but should I pull request ?

**Comment by Twilightssuperb** [comment]
Thaks for reply. :) I am not aware of API details etc. Nevertheless I suppose if you will add Tweetmarker it will be fork. It would be better if this function is been added to original extension for all users. Perhaps, you should talk with @eramdam...

**Comment by eramdam** [comment]
Do a pull request and I'll have a look at it :-)

**Comment by Twilightssuperb** [comment]
I am a nub and don't know what branches I should type there. Please sorry me. :) In "body" of request you can use my first comment. @Apph3x, I've read your comment one more time and just realise what you mean. Please sorry too. Of course, I will be very thankful if you would start pull request there.

**Comment by Apph3x** [comment]
Ok @eramdam should I upload my modified version then ? It crashes TweetDeck sometimes

**Comment by eramdam** [comment]
@Apph3x @Twilightssuperb One of you (or both), post a pull request, I'll have a look at it to do my own/improved implementation when I will have time :)

**Comment by Apph3x** [comment]
Yup lemme fix a few bugs then sure

**Comment by Natanji** [comment]
Any news, @Apph3x? The feature would be really great to have.

**Comment by nullr1ver** [comment]
Yeah looked at my pull, may make now @Natanji

**Comment by nullr1ver** [comment]
Can you close this ? API access for tweetmarker is $25.00/mo

**Comment by nullr1ver** [comment]
@eramdam thanks

**Comment by Twilightssuperb** [comment]
Guys, why are you so greedy?! BTD has more than 10k downloads from Chrome web store. Let's imagine - even when 100 persons will pay just 25 US cents at every month, @eramdam would buy and implement Tweetmarker developers API. Yep, it's expensive feature, but we're not alone. To my mind, @eramdam should make a poll, how many people are ready to donate extension for Tweetmarker. ¢25 ($0.25) or about $1 per month -  either of contributions we can afford to do. If there are less than 30 counts "yes" in a poll, we will suspend issue untill Tweetmarker reduces prices. Just take a point. We ought to discus this crowd-funding. 

Let me remind you, none of free Twitter clients for Windows PC is actually supports Tweetmarker. Janetter can't register new accounts no more because of Twitter token policy. Tweetro costs $9.99, though its UI can't compare to TweetDeck, Hootsuite or Janetter.

**Comment by nullr1ver** [comment]
But if no free client has tweet marker, why does this mean BTD needs it ? @Twilightssuperb

**Comment by Twilightssuperb** [comment]
@nullr1ver, I said "actually" and meant that application is available for newcomers. Janetter is free for Windows, but unfortunately it can't register new accounts. If we wanna have the almost best and the most comfortable desktop soft for Twitter, we should develop BTD. Tweetmarker is killer feature that may appoint BTD as leader. If you don't need Tweetmarker, this doesn't means that other people don't need too. I repeat, we can invent a solution to make developer plan as easy as possible for eramdam - though our feasible monthly contribution don't have to be more than $1, if there are about 30 BTD users who are ready to donate.
Also we can wait untill Twitter implements own bookmarking system to synchronize feed at every dashboard, even if it would be 3rd party application. But I hope not so.

**Comment by nullr1ver** [comment]
Still does't justify why people would donate $1.

**Comment by eramdam** [comment]
@Twilightssuperb @nullr1ver My 2cts:
+ First, I'm not sure how feasible it would be to add it given the "on top" nature of a Chrome extension. And I would have to somehow encrypt/hide my API keys, which is easy for a native app, not that much for a Chrome extension
+ I _could_ afford the 25$/mo subscription easily it's not a problem, but I'm not sure it would be the right thing to do to add for free something that will cost me money. I develop BTD on my free time and I don't want to need money to run it, so if at some point it costs me something, I need to get a ROI at some point.
This leads to the possibility of making it a donation-only feature, but I'm not sure it would be very efficient as anybody could easily fork the repo, disable the donation-lock and use its own credentials.

But overall I really think like @Twilightssuperb that TweetMarker integration would be a killer, given the fact it's present on a lot of third-party apps (Tweetbot, Twitterific, etc). And if I do this donation-only, I think it would be interesting to have other "advanced features" with it.

**Comment by Twilightssuperb** [comment]
@eramdam, I overlooked the API details and ability to fork BTD, I'm so sorry. One of probable solutions (for protect BTD key) is to hide some BTD data. Maybe, you could implement some kind of encryption or a script, that would verify BTD check-sum or something else - just to recognize fork, non-original BTD. And it will turn-off Tweetmarker support in these forks. However, Tweetmarker's key protection seems to be hard to do, because BTD is standalone. That's all I just can suppose.

**Comment by eramdam** [comment]
@Twilightssuperb my take would be to use a simple "**required**" stuff in my code, so only I could distribute a "legit" copy of BTD because I would be the only one with the correct API keys. It's the standard way of doing in node apps, so it could make sense here too

**Comment by eramdam** [comment]
This article might be helpful http://billpatrianakos.me/blog/2013/09/12/securing-api-keys-in-a-client-side-javascript-app/
