### ISSUE TITLE
Remove t.co redirection on links not working

### ISSUE THREAD

**Issue by Stanzilla** [eramdam/BetterTweetDeck#220]
From what I've seen it breaks when new tweets get streamed in, you have to CTRL+R to remove their redirection

**Comment by EntranceJew** [comment]
after tweets and previews load the UI sends the event named something like `uiMediaPreviewRefresh` that probably causes chirps to reload without their info changed on them

**Comment by eramdam** [comment]
I rewrote the way the t.co removal works. This will be in next release and should be way more reliable and immune from this bug. 

If you're interested https://github.com/eramdam/BetterTweetDeck/blob/5939fc4ae3467a9d5dab19363956dc79ec6ca5c4/src/js/inject.js#L9-L31
