### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by OnlinePlayer865** [eramdam/BetterTweetDeck#225]
Is there any plans on supporting Microsoft Edge for BetterTweetDeck soon? I would really like to see this available for Edge.

**Comment by eramdam** [comment]
@JMccormick264 It was actually planned since the v3.x. Unfortunately, there seems to be some weird bugs in Edge making the whole thing non-functional. I didn't try in a long time myself, I know @pixeldesu did recently so he might be able to weight in on this.

**Comment by JMccormick264** [comment]
Hopefully things get working again. Can definitely seeing this reaching users who only use Edge.

**Comment by pixeldesu** [comment]
@JMccormick264 I tried converting the extension over to Edge in the last couple of months, multiple times. And as extensions still are not the most stable thing in Edge, it might take a while until we fully get it working with the current setup we have.

**Comment by JMccormick264** [comment]
@pixeldesu alrighty. Hopefully things stable out with Edge. Thank you for the info.

**Comment by Scrxtchy** [comment]
Managed to get it working by adding the required manifest changes (author tags, persistent keys are required for background scripts), and replacing `chrome` with `browser` from a package downloaded from AMO

Settings page loads fine. 
Hiding the scrollbars actually removed the ability to scroll

**Comment by rogersachan** [comment]
This issue is no longer necessary now that edge is built on top of chromium and can install extensions from the Chrome Web Store. (https://www.microsoftedgeinsider.com/en-us/)

**Comment by Scrxtchy** [comment]
TRUE 😉

**Comment by dangeredwolf** [comment]
Well, Edge Chromium is still in beta, though.

**Comment by rogersachan** [comment]
yeah, but I figure you guys would rather spend time fixing bugs rather than adding support for another browser that is already being replaced.

**Comment by dangeredwolf** [comment]
Well, in my experience, porting chrome extensions to EdgeHtml-based Edge was easy, mostly the same as porting to Firefox: using browser instead of chrome.

**Comment by Scrxtchy** [comment]
It took me like ten minutes to port, but I didn't really do anything with it since TweetDeck doesn't Ru  very well on a Surface Pro.
Stutters on input heavily, not a BTD issue

**Comment by dangeredwolf** [comment]
EdgeHtml-based Microsoft Edge is really slow at running TweetDeck in general. I noticed it when I ported moderndeck over.

**Comment by eramdam** [comment]
Closing since Edge-Chromium is around the corner so this would make this unneeded AFAICT.
