### ISSUE TITLE
Preview of media seems to be broken

### ISSUE THREAD

**Issue by Twilightssuperb** [eramdam/BetterTweetDeck#23]
In my case I don't get any preview from Instagram at tweetdeck.twitter.com. But pic.twitter.com is OK.
<img src="http://savepic.su/4689091.png" border="0" alt="Изображение - savepic.su — сервис хранения изображений" />
Also, what about native Flickr shortener flic.kr? Now BetterTweetDeck doesn't support it: <img src="http://savepic.su/4674754.png" border="0" alt="Изображение - savepic.su — сервис хранения изображений" />
Finally, there's no one more preview. Gif isn't displayed: 
<img src="http://savepic.su/4654274.png" border="0" alt="Изображение - savepic.su — сервис хранения изображений" />

**Comment by Apph3x** [comment]
This is tweet deck not better tweetdeck
