### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Zhangsun321** [eramdam/BetterTweetDeck#234]
tweetdeck with better tweetdeck and enable trends script...

I ABSOLUTELY LOVE the 'mute by source' option..
but it does it 'across all columns..   any way to just have it apply on a selected group of columns, or just a single one?
that will be PERFECT!

thanks
Eddie

**Comment by eramdam** [comment]
@Zhangsun321 Unfortunately, it's not possible to filter stuff on a column basis. There may be a way by hacking very deep into TweetDeck's inner workings but it seems very complicated and risky as far as I can tell.
