### ISSUE TITLE
Tweets windows does not go in background

### ISSUE THREAD

**Issue by Kn0p3XX** [eramdam/BetterTweetDeck#240]
Clicking on a gif in this window does this, maybe it should go in the background instead stay in foreground.

What i did to reproduce:
Search for a profile or click on a profile on the timeline.
Find a gif in the Tweets window.
Click on it.

What should do it is the tweets window should not in the foreground, so we can look at it properly.

![2017-09-29_11-42-40](https://user-images.githubusercontent.com/16920375/31010637-cb01cec0-a50b-11e7-8088-c0fd5ef332c3.jpg)

**Comment by eramdam** [comment]
Can you tell me on which browser you’re running the extension? I doubt it’s a browser specific issue but just in case it is it might be useful to know :)

**Comment by Kn0p3XX** [comment]
I'm using Firefox 56.0 (I was using 55.0 minutes ago, but the bug is still there) with Better TweetDeck 3.4.6, latest version on AMO.
