### ISSUE TITLE
Button to remove column

### ISSUE THREAD

**Issue by noamross** [eramdam/BetterTweetDeck#241]
As Tweetdeck now has the habit of creating a column every time one does a search, it would be nice to have the option of a column-header button to remove a column, along the lines of the collapse buttons introduced in the last update.  Another option would be to be able to remove columns via some small "x" in the corner of the column icons in the left control dock.

**Comment by eramdam** [comment]
If we ever do this I think we'd rather do it with a header button in the columns' header.

**Comment by eramdam** [comment]
It's in v4 that just came out!
