### ISSUE TITLE
Move action buttons to bottom of large media previews in columns

### ISSUE THREAD

**Issue by ViTheDeer** [eramdam/BetterTweetDeck#244]
Right now, the action buttons (Like/RT/Reply) appear below the text but above the image when media previews are set to "Large"
This is unintuitive as it reverses the order compared to "Medium" or "Small" previews (Text->preview->AB)
Could this be changed or made an option so that the ABs appear below the media preview for all sizes?

**Comment by pixeldesu** [comment]
While it definitely is a change of order of features, they still give some visual presentation that media belongs to a post (that small white arrow pointing inwards)

This is done to reduce the leeway of interaction, as with large media, getting to the actions would take way longer than with other sizes. 

Also, the actions would look more out of place below large media, as the media sizing causes a clean cut in the interface and they don't directly show "hey, these actions belong to the tweet above". You could easily think the actions belong to the tweet below as they are way closer to that tweet.

**Comment by arnulfolg** [comment]
I was struggling with the same issue, It looks weird to me that only for large media the tweet actions appear above instead of below as in the others. 

But who knows, maybe pixeldesu is right. I would like to try it first anyways just to be sure.
