### ISSUE TITLE
Quoted tweets with full-size font

### ISSUE THREAD

**Issue by noamross** [eramdam/BetterTweetDeck#248]
It appears a recent update has resulted in quoted tweets having reduced-sized font:

<img width="298" alt="screen shot 2017-10-05 at 12 15 25 am" src="https://user-images.githubusercontent.com/571752/31210751-6e9ea86e-a962-11e7-87c7-569f21cf75d1.png">

It would be great to have the option to return back to full-sized font in the quoted tweets.

**Comment by eramdam** [comment]
I'm sure this was either fixed or changed completely so I'm closing this
