### ISSUE TITLE
[Suggestion] Add option to post 280-character tweet

### ISSUE THREAD

**Issue by rcmero** [eramdam/BetterTweetDeck#249]
So, as explained [here](https://www.howtogeek.com/327555/how-to-get-twitters-new-280-character-limit-now), it's possible, usng TweetDeck and a little bit of know-how, to post a 280-character tweet regardless of whether or not you can do so normally. My suggestion would be to add this functionality to Better TweetDeck.

I've noticed that you're already working on 280-related stuff, so I'm not already sure if you're planning on doing this.

**Comment by eramdam** [comment]
It's already in the work and available in a beta build. If everything goes well it should be available in the next stable build.
