### ISSUE TITLE
Can you make tab show a number when there are new tweets?

### ISSUE THREAD

**Issue by sithulol** [eramdam/BetterTweetDeck#250]
twitter tab does it. example - https://i.imgur.com/7smlpCe.png

can you make tweetdeck do this too? im not always on tweetdeck tab to see if theres new tweet and sometime i cant have sounds enabled / and sometimes i miss the 3-4 seconds notification when im focused on something else

**Comment by eramdam** [comment]
I'll look into how feasible it would be 🤔

**Comment by viki53** [comment]
In the meantime there's already an option to show an unread indicator in the tab (*Content* > first checkbox) 😉

**Comment by eramdam** [comment]
I think we discussed internally about this and I'm pretty sure this would be near impossible to have a perfect solution given the multi-columns nature of TweetDeck + you'd need to keep track of said tweets and everything, which I'd rather not do, counters are a mess in computing usually and I don't want to complicate Better TweetDeck more than it already is.
