### ISSUE TITLE
New badge displaced

### ISSUE THREAD

**Issue by shuuji3** [eramdam/BetterTweetDeck#258]
New badges seems to be displaced for multiline text. See `Settings > Interface` with narrow window size, for example.

<img width="370" alt="2017-10-28 2 17 30" src="https://user-images.githubusercontent.com/1425259/32141161-4f31c7e6-bcbc-11e7-97db-8f72486b785b.png">

**Comment by eramdam** [comment]
Yeah... 😅  I'll be working on a redesign of the settings page in the coming weeks for I'll fix this as well.
