### ISSUE TITLE
Last update TweetDeck update broke injected styles

### ISSUE THREAD

**Issue by LeoColomb** [eramdam/BetterTweetDeck#260]
TweetDeck has been updated, now some BTD styles are no more injected.

For example, ["hide scrollbar"](https://github.com/eramdam/BetterTweetDeck/blob/ee61102d539c8915330bbc26e5a4c10f8d997754/src/css/features/hide-scrollbars.css) feature results in:
![image](https://user-images.githubusercontent.com/846943/32328114-29162848-bfd9-11e7-8c35-7ed62c9f04a1.png)

But as some part are still injected, I suspect an error inside injection script.
![image](https://user-images.githubusercontent.com/846943/32328137-49a5adc2-bfd9-11e7-8025-4780fea2d42e.png)

(_Sorry for near empty issue first opening._)

**Comment by eramdam** [comment]
Seems like TweetDeck reverted the issue pretty quickly. Closing this.

**Comment by LeoColomb** [comment]
Confirmed! 👍

**Comment by LeoColomb** [comment]
Again, new update, it's coming back...
