### ISSUE TITLE
Feature to make text even smaller?

### ISSUE THREAD

**Issue by lvckv** [eramdam/BetterTweetDeck#264]
After 280 characters have been rolled out everywhere, it means there's even less space on Tweetdeck so some lists can only show 1 or 2 Tweets at a time if people are going to post Tweets that long.

Will it be possible to add a feature that makes the text smaller than TweetDeck's smallest size? Would be very helpful.

**Comment by eramdam** [comment]
Can't promise an ETA but basically I would put this under the Custom CSS feature. https://github.com/eramdam/BetterTweetDeck/issues/254
