### ISSUE TITLE
mute 140+character tweets

### ISSUE THREAD

**Issue by rpupkin** [eramdam/BetterTweetDeck#265]
i would greatly appreciate a feature that automatically screens out tweets of more than 140 characters.  gracias.

**Comment by eramdam** [comment]
You can already do that https://twitter.com/BetterTDeck/status/913033747460706305

**Comment by EntranceJew** [comment]
or you could do this as well: https://twitter.com/BetterTDeck/status/928336830902104066

**Comment by rpupkin** [comment]
and done!  much better.  thanks.
