### ISSUE TITLE
Feature request: truncate tweets longer than 140

### ISSUE THREAD

**Issue by AnneShirley** [eramdam/BetterTweetDeck#266]
I'm finding Tweetdeck looks so noisy right now with the long tweets. Is there a way we can opt to truncate them to the standard size with the option of expanding?

**Comment by eramdam** [comment]
I'll do this for quotes but doing so for tweets is something that would require a lot of hacking inside TweetDeck's UI so I can't promise anything right now.

**Comment by eramdam** [comment]
Now that the 280 tweets are actually avaiable to everyone I feel like a lot less people are asking for that so I'll close it for now as it would feel very weird to have this anyway.

Maybe next year if I find a clean way to do it I will implement it.
