### ISSUE TITLE
Suddenly very thin font -> "Use the system font in the UI"

### ISSUE THREAD

**Issue by cmdrfletcher** [eramdam/BetterTweetDeck#269]
Since 3.4.8 the font looks very thin and is difficult to read. I am using Windows 10. Is there an option to choose the font?

**Comment by pixeldesu** [comment]
That is not really the fault of BTD, a TweetDeck update added font-weight to the fonts, making them look very thin on Windows.

I'll be working out a fix for this soon!

**Comment by pixeldesu** [comment]
Looks like TweetDeck was faster than myself. The issue seems to be fixed now.
