### ISSUE TITLE
Favorite icon disappears upon favoriting tweet.

### ISSUE THREAD

**Issue by tehbasshunter** [eramdam/BetterTweetDeck#272]
Favoriting a tweet makes the icon hidden. Refreshing fixes this issue.  
  
[Bug in action](https://vid.me/R2kxR)

**Comment by eramdam** [comment]
@tehbasshunter does this happen when you _don't_ enable the setting to replace hearts by stars? I suppose it doesn't but I want to be sure.

**Comment by tehbasshunter** [comment]
Tested and it only happens when replacing the heart with stars. Hearts maintain visibility.

**Comment by eramdam** [comment]
@tehbasshunter ok, thx for the details. I'll try to get this fixed for the next release.

**Comment by tehbasshunter** [comment]
No problem.
