### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by SpacemanRiff** [eramdam/BetterTweetDeck#274]
Experiencing general lag and "frame drops" (if that's really a thing in this. anyways its jittery) when composing tweets and scrolling among columns. This was not there like a few weeks ago. Started being a problem around the time Twitter support 280 characters, although this may not be the cause.

My CPU has plenty of headroom so it's not my computer being slow (6th gen i5, 8gb of ram). 

If any additional information on my part is needed, let me know.

**Comment by eramdam** [comment]
Is it still an issue? I'm closing this, feel free to re-open if it is.
