### ISSUE TITLE
Chrome 'script-src' Error

### ISSUE THREAD

**Issue by cuweh** [eramdam/BetterTweetDeck#275]
Been seeing this error pop up in Chrome Canary for several weeks (previously extension has been flawless):
"Refused to load the script 'chrome-extension://micblkellenpbfapmcpcfhcoeohhnpob/js/background.js' because it violates the following Content Security Policy directive: "default-src ". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback."

**Comment by eramdam** [comment]
Given that the error seems to be happening on the `generated_background_page.html` file that I _do not_ have control over. I'll close this as a wontfix. Chrome Canary always has some weird bugs as it is not a stable release.
