### ISSUE TITLE
Previously viewed account avatars get "stuck" when viewing/zooming media 

### ISSUE THREAD

**Issue by dfkt** [eramdam/BetterTweetDeck#276]
When I open tweets with media in large view, account avatars from previously viewed tweets are "stuck" underneath the current account's avatar:

![2017-11-25_224827](https://user-images.githubusercontent.com/5091485/33235194-5111942e-d233-11e7-8634-cb69180a5265.png)
![2017-11-25_224912](https://user-images.githubusercontent.com/5091485/33235195-5133168a-d233-11e7-8586-d043aa763b7e.png)
![2017-11-25_224948](https://user-images.githubusercontent.com/5091485/33235196-514ea026-d233-11e7-9bee-eca5011a8da0.png)
![2017-11-25_225135](https://user-images.githubusercontent.com/5091485/33235197-516d8d10-d233-11e7-9218-bc2246050f32.png)

**Comment by eramdam** [comment]
I had this happen to me randomly as well. What was weird is that the duplicated avatar was disappearing after I switched away and came back from the tab so I think it's more a random Chrome glitch than anything else 🤷‍♂️
