### ISSUE TITLE
Req: smooth-scroll on insertion/deletion of tweets into column

### ISSUE THREAD

**Issue by jxyzn** [eramdam/BetterTweetDeck#280]
The instant jump that occurs when adding (or removing) tweets from each column violently interrupts reading and requires some effort to re-locate and continue reading tweets.

If the new content were inserted and adjusted position smoothly instead of jumping, it would make reading much easier as the display scrolls.

**Comment by eramdam** [comment]
I'm afraid there's little to no way for me to remove and replace the original behaviour of TweetDeck on this without seriously breaking something. Sorry.
