### ISSUE TITLE
Allow Firefox users to use Alt+[1-9] to switch Tabs.

### ISSUE THREAD

**Issue by kindfulkirby** [eramdam/BetterTweetDeck#282]
Currently Tweetdeck in Firefox "captures" keypresses of Alt+1, Alt+2, etc. (which are used to jump to the so-numbered tab (or the last tab for Alt+9) on Linux systems), and treats them as if just the number had been pressed, i.e. jumps to the corresponding column.

This is quite annoying, and I'd love for that "feature" to be patched out.

**Comment by eramdam** [comment]
I'm afraid there's not much an extension can do since TweetDeck propably already has event handlers for that, I can't remove those handlers :/

**Comment by ttheuer** [comment]
Fair enough, thanks!
