### ISSUE TITLE
Feature Request: Gif

### ISSUE THREAD

**Issue by Fen1xMonk3y** [eramdam/BetterTweetDeck#284]
Can we please have an add gif for original tweets, replies, and even quoted tweets? please? the actual twitter site has this, but ugh, i much prefer tweetdeck with better tweetdeck.

**Comment by EntranceJew** [comment]
If you use the popout button in the in-column reply bar then you are able to move your reply into the composer to use the "add gif" feature.

**Comment by eramdam** [comment]
Next release will add a GIF button for the popped out composer.
