### ISSUE TITLE
Feature Request: threaded messages

### ISSUE THREAD

**Issue by Fen1xMonk3y** [eramdam/BetterTweetDeck#285]
Can we please get the + button to add to a tweet and allow an entire thread to be sent at one time instead of having to reply to your own tweet over and over to get the thread?  it would be much appreciated. again, part of the original site, but again i much prefer all of the wonderful of tweetdeck with better tweetdeck for those extra things.

**Comment by eramdam** [comment]
This requires an awful lot of UI work + requires hacking deep into TweetDeck's inner code to even think about having something that works so I won't attempt to do it.
