### ISSUE TITLE
Like from accounts 

### ISSUE THREAD

**Issue by mariposalinda** [eramdam/BetterTweetDeck#288]
Hey guys! Thanks for a great plugin!

I just noticed the popup screen for the like from accounts stopped working properly. Each time I click on a like,  the popup disappears, so I would have to go to the dropdown menu and click on each like button again to use the multiple accounts. I don't recall updating anything, I am using Chrome on Mac.

Thank you

**Comment by eramdam** [comment]
It's a TweetDeck bug that we most likely cannot fix. Sorry. We notified the devs about it so they'll likely release a fix in the coming days/weeks.

**Comment by mariposalinda** [comment]
Talk about a speedy response! Thank you eramdam!
