### ISSUE TITLE
Re-requesting notification perms

### ISSUE THREAD

**Issue by tombh** [eramdam/BetterTweetDeck#29]
Would you be interested in a PR to re-request notification perms?

Really this is something that Tweetdeck themselves should sort out (ha, but the same could be said for the whole of BetterTweetDeck!): whenever I use Tweetdeck on a new browser notifications stop working because Tweetdeck don't check `window.Notification.permission` :( Once perms have been granted they assume your good for life.

To be fair there is a quick fix by just pasting `window.Notification.requestPermission()` into the JS console.

BTW awesome work on this, I love it. Also it works perfectly in Opera :D

**Comment by nullr1ver** [comment]
THIS \^^^

**Comment by nullr1ver** [comment]
Not a bad idea

**Comment by tombh** [comment]
Will it get merged though?

**Comment by eramdam** [comment]
I will look at it when developing 3.0. I just hope there won't be somekind of sandboxing issues because it sounds typically like something that could be sandboxed :)

**Comment by eramdam** [comment]
@tombh I just re-tried and it seems like TweetDeck is now smart enough to display a banner when it lost notifications permissions? Can you confirm ?

**Comment by eramdam** [comment]
Closing this until confirmed really needed
