### ISSUE TITLE
Closes window automatically after following one account

### ISSUE THREAD

**Issue by brianleejackson** [eramdam/BetterTweetDeck#297]
This issue just started happening with the lastest version or so.. I am also running latest version of Chrome (63).

When you click on an account... I can follow someone. I click follow and the window closes (the popup for the follow itself) and puts me back to main tweetdeck page. 

I used to be able to click on a profile and follow from multiple profiles. This was very handy as I follow a lot of accounts from my personal and work Twitter accounts.

Let me know if you need more information. This has become very annoying as I now have to re-open it multiple times... Sometimes I even follow from 4+ more accounts and now I have to open it 4 times.

Thanks for taking a look into this. Appreciate it and keep up the great work.

**Comment by eramdam** [comment]
That's a change from TweetDeck they did to act on spam and stuff. I won't be doing anything to work around that to stay within Twitter's rules

https://twitter.com/TweetDeck/status/943198401604325376
https://twitter.com/BetterTDeck/status/943199581340295169
