### ISSUE TITLE
Entering message column, name not fully shown

### ISSUE THREAD

**Issue by orschiro** [eramdam/BetterTweetDeck#299]
Dear @eramdam,

When entering the message column, the name is not fully shown as demonstrated in the below screenshots. 

Do you have any advice for me?

Thank you very much!

![image](https://user-images.githubusercontent.com/170947/34431176-09f54708-ec6d-11e7-90c0-bd3647c2559d.png)
![image](https://user-images.githubusercontent.com/170947/34431180-150e89ce-ec6d-11e7-8ae4-f5b876f10957.png)

**Comment by eramdam** [comment]
Are you sure another extension is not conflicting and causing some styling issues?

**Comment by orschiro** [comment]
Dear @eramdam thanks for your reply. I will close this as invalid. 

I just tried TweetDeck in incognito mode with all extensions disabled but it's still occurring. 

Must be an issue with Linux Mint 18.3 Cinnamon and 63.0.3239.108 (Official Build) (64-bit).

![peek 2017-12-29 17-20](https://user-images.githubusercontent.com/170947/34441560-cbe6c91e-ecbc-11e7-923d-d5d09867c6a2.gif)
