### ISSUE TITLE
shortcodes do not work in DM column

### ISSUE THREAD

**Issue by kathakatze** [eramdam/BetterTweetDeck#301]
When composing a reply in the direct messages column, the emoji preview bar does not show up after typing the start of a :shortcode:. Completing the shortcode doesn't help. Shortcodes do work everywhere else, including the usual compose area, so clicking the popout button is a possible workaround.

**Comment by pixeldesu** [comment]
Features are not included in the DM columns.

This is not to mock the user. As confirmed by the TweetDeck team itself, the implementation of the direct messages in TweetDeck is quite hacky.

As it has shown several performance issues, all features (thumbnails etc.) are not applied in this section. Maybe at some point DMs reach a state where the base implementation is clean again and it's safe to add the features.

But yeah, as you mentioned yourself, using the pop-out is the only workaround right now!

**Comment by kathakatze** [comment]
Yeah, I noticed the lag issues. Meh.

**Comment by eramdam** [comment]
Shortcuts should work in the DMs column with v4
