### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by Stanzilla** [eramdam/BetterTweetDeck#304]
Chrome 64.0.3282.39 (Official Build) beta (64-bit)
BTD: 3.5.1

Videos have actually not been playing for a while, just remembered to report and check console now, getting the following: 

```
build.min.js:148 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.
build.min.js:148 Refused to create a worker from 'blob:https://twitter.com/af84d7d6-327d-469d-bea0-ab9509bbd14e' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self' http://localhost:* http://localhost.twitter.com:* https://*.twitter.com https://*.twimg.com https://vine.co https://*.vine.co https://*.periscope.tv https://*.pscp.tv". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

t.exports @ build.min.js:148
```

Tweet was this one https://twitter.com/Methodsco/status/947608746854944768/video/1

I does not work without BTD either, so I think it might be chrome://flags/#autoplay-policy set to "require user gesture" that breaks this. Although it should play, since I clicked it. So not really a BTD bug but maybe worth mentioning to users?

**Comment by eramdam** [comment]
Probably related to the autoplay policy yeah. But I'm afraid I can't do much, Twitter themselves might have to fix that 😅  And hopefully it's just a mis-hap of Chrome Beta and will not happen when 64.x goes into stable.
