### ISSUE TITLE
TweetDeck logo is broken

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [eramdam/BetterTweetDeck#306]
When the menu is not expanded, the display of the TweetDeck logo is strange. I am using the Chrome version.
![image](https://user-images.githubusercontent.com/11265280/34466633-bc66ccd8-ef1d-11e7-8cf1-164d41aec29e.png)

**Comment by ShintakuNobuhiro** [comment]
I’m Japanese. And I'm using Google Translate...
I'm sorry if it is strange syntax.

**Comment by pixeldesu** [comment]
@ShintakuNobuhiro are you using an additional extension that does stuff on TweetDeck? Or a custom style?

BetterTweetDeck does not touch that logo at all, as far as I can tell.

**Comment by JuanjoSalvador** [comment]
Which version of BetterTweetdeck?

Check it on [chrome://extensions/](chrome://extensions/)

**Comment by eramdam** [comment]
Gonna close for inactivity, feel free to re-open when you get more details.
