### ISSUE TITLE
Copy link to tweet feature/suggestion

### ISSUE THREAD

**Issue by sandymanu** [eramdam/BetterTweetDeck#310]
Hi,

In tweetdeck when you press options and then copy link to tweet the user window box closes and a separate copy link box opens. This becomes irritating and you need to open the user again,

In the normal web version, when you press copy link to tweet it directly copies to clipboard without affecting current window. Is that possible in deck ?

**Comment by eramdam** [comment]
The timestamp of every tweet is a link to the said tweet, you can use that as a better way to copy the link quickly 
![image](https://user-images.githubusercontent.com/1409924/35197222-53926bd0-fe91-11e7-9bd5-1c80d8b1d5d8.png)

**Comment by sandymanu** [comment]
Thanks, that's more helpful.
