### ISSUE TITLE
Display problem due to TweetDeck column width...

### ISSUE THREAD

**Issue by GitHubCommunityProjects** [eramdam/BetterTweetDeck#312]
When the column width selected from the TweetDeck options is "Narrow" and when, in addition, it is selected from the BetterTweetDeck options, adding all the available buttons, such as the media content download, among others, do not all enter a single line, but one of them "the three-point button" is in a second line, and when you select it, the menu is partially hidden, impossible to select any option of it.

**Comment by eramdam** [comment]
Can you post a screenshot of your issue? I tried re-reading a few times and I can't make any sense of it 😓

**Comment by GitHubCommunityProjects** [comment]
The same happens with Firefox, Chrome and Opera; both in Linux and in Windows 10 (everything is updated)

Here with the Medium or Wide columns, from the TweetDeck settings ...






Here with Narrow columns...




I was going to give you a Power Point presentation but it seemed too 😋


De: Damien Erambert
Enviado: sábado, 3 de febrero de 2018 10:38
Para: eramdam/BetterTweetDeck
CC: GitHubCommunityProjects; Author
Asunto: Re: [eramdam/BetterTweetDeck] Display problem due to TweetDeck columnwidth... (#312)

Can you post a screenshot of your issue? I tried re-reading a few times and I can't make any sense of it 😓

**Comment by eramdam** [comment]
Hum, it seems like your screenshots are not showing 😅
