### ISSUE TITLE
'Show 'verified' badges on top of avatars' positioning bug

### ISSUE THREAD

**Issue by Mohamed3on** [eramdam/BetterTweetDeck#318]
After the new TweetDeck update, the positioning of the badge is no longer right.
![image](https://user-images.githubusercontent.com/12295159/35860395-2f52e0dc-0b44-11e8-98e9-364e66786f2b.png)

**Comment by eramdam** [comment]
Already fixed by https://github.com/eramdam/BetterTweetDeck/commit/2cb6e29032c467dcd3358418543fea2dbb4afbed

I will push an update later today.
