### ISSUE TITLE
TweetDeck Chrome app

### ISSUE THREAD

**Issue by franga2000** [eramdam/BetterTweetDeck#32]
Hi, I love the extensoin, but I found a problem: It doesn't work with the [chrome app](https://chrome.google.com/webstore/detail/tweetdeck-by-twitter/hbdpomandigafcibbmofojjchbcdagbl).
The fix shouldn't be that hard, just add this URL to the list of sites to modify: 
`chrome-extension://hbdpomandigafcibbmofojjchbcdagbl/web/templates/default.html`

I'd send a PR, but I have no idea how this works

**Comment by eramdam** [comment]
> The fix shouldn't be that hard, just add this URL to the list of sites to modify: 
chrome-extension://hbdpomandigafcibbmofojjchbcdagbl/web/templates/default.html

This is not how it works. Chrome doesn't allow extensions to modify another extension/app. it was the first thing I ever tried when I began the development of BTD.

**Comment by franga2000** [comment]
Oh, I didn't know that. Too bad
