### ISSUE TITLE
Restore Multi-Retweet/Like Functionality

### ISSUE THREAD

**Issue by KatherineFtw** [eramdam/BetterTweetDeck#326]
When you used to use Tweetdeck/BTD, you could Retweet/like from multiple accounts at once. For some reason, this functionality is gone. It's incredibly inconvenient. If you could restore it, you'd have some of my bigger thanks.

(Sorry, I'm new to this. Please, tell me if I'm doing anything wrong or if there's anything I could add/subtract)

**Comment by eramdam** [comment]
https://twitter.com/BetterTDeck/status/966368548854444032
