### ISSUE TITLE
Better gif preview

### ISSUE THREAD

**Issue by Arlefreak** [eramdam/BetterTweetDeck#33]
Currently one of the most annoying things on tweetdeck is that if you want to see a twitter GIF it opens in a new tab, would be better a popup with the GIF in a bigger size.

**Comment by eramdam** [comment]
@Arlefreak is this supposed to be about Twitter's gifs? If so, the issue is somewhat obsolete now that TweetDeck supports gifs :stuck_out_tongue:

**Comment by Arlefreak** [comment]
Yes, but currently the gifs don't have a popup like the images to see it in real size, but is better than before

**Comment by eramdam** [comment]
Fair point :smile:
