### ISSUE TITLE
Easier access to "Undo Retweet"

### ISSUE THREAD

**Issue by colonyoo** [eramdam/BetterTweetDeck#331]
More a quality of life thing than anything else, but it'd be handy if you could undo a retweet from the actual retweet pop-up instead of having to do it from the drop-down tweets menu.

The pop-up already has a display letting me know that it's been retweeted once before, but the option to undo it is so far down the tweets menu that it actually goes off of my screen most of the time (so much so that for a long while I didn't even know it was an option outside of opening the tweet in a new tab and manually unretweeting it).

**Comment by eramdam** [comment]
Note to self: check why it's hidden in a specific menu, there might be a technical reason that i can't work around.

**Comment by eramdam** [comment]
Ok it turns out i misunderstood this issue back then. I can't easily hack into the retweet box so I can't do much, sorry 😞
