### ISSUE TITLE
hashtag column settings button issue

### ISSUE THREAD

**Issue by stekost** [eramdam/BetterTweetDeck#338]
when adding a hashtag column, it is impossible to close it (or open the menu) because the text box maybe has fixed width and cross the column border, and with narrow column the button is hidden. 

![screenshot_20180504_141719](https://user-images.githubusercontent.com/38980404/39627350-e5ab7e20-4fa5-11e8-8a40-622641d20ece.png).

it should have relative width  in accordance to the value set in the BetterTweetdeck Option page.

![screenshot_20180504_142553](https://user-images.githubusercontent.com/38980404/39627726-19d3fd3e-4fa7-11e8-9c47-6d23271d8c94.png)

Following, the same column with the extension disabled.

![screenshot_20180504_142221](https://user-images.githubusercontent.com/38980404/39627584-ae6ee612-4fa6-11e8-8432-2cf86b52ed50.png)

Chromium Version 66.0.3359.117 (Developer Build) built on Debian 9.4, running on Debian 9.4 (32-bit)

**Comment by eramdam** [comment]
Will be fixed by the next release
