### ISSUE TITLE
Buttons were lost...

### ISSUE THREAD

**Issue by GitHubCommunityProjects** [eramdam/BetterTweetDeck#339]
The buttons of the title bar of each column to collapse them (button in the form of a hyphen) no longer appear, they simply disappeared, "from the last update"

**Comment by eramdam** [comment]
Are you sure you're running the last version? Because I published 3.7.1 yesterday that fixes this.

**Comment by GitHubCommunityProjects** [comment]
Sorry and thanks, it happens that the Firefox browser did not work the automatic update of add-ons; I already updated it manually and it works fine now.

**Comment by bontchev** [comment]
Sadly, it's broken again, although in a different way. Yes, it was fixed for a while, but with the latest TweetDeck update the button for clearing the column (added by BTD) is now smack over the (standard) button for configuring the column.

**Comment by bontchev** [comment]
Aaaand, TweetDeck changed the format again. :( The button to clear the column added bt BTD is still visible, but now the original button for opening the column configuration menu has become a dot and doesn't work.

Something is wrong with the HTML tags of the column title, too - even if I don't tell BTD to put a column-clearing button there.

**Comment by eramdam** [comment]
I'm working on releasing a fix right now.
