### ISSUE TITLE
BTD causes Columns to snap to the bottom

### ISSUE THREAD

**Issue by KatherineFtw** [eramdam/BetterTweetDeck#342]
It appears at random, I can't seem to find out what exactly causes this. I can confirm BTD is doing this due to it not happening when it's turned off. This started with the lasted TD update.

**Comment by eramdam** [comment]
Does it still happen now? Because I think this correspond with the time when TweetDeck messed up a bit of their columns code so maybe there's something in the way BTD and TweetDeck interacted back then that was weird.

**Comment by eramdam** [comment]
Gonna close for inactivity. Feel free to re-open if still relevant.

**Comment by KatherineFtw** [comment]
Yea, sorry about that (And thanks). It was a Tweetdeck issue, not a BTD issue.
