### ISSUE TITLE
Request: an option to skip "Copy link to Tweet" dialog window

### ISSUE THREAD

**Issue by hachi8833** [eramdam/BetterTweetDeck#344]
I always feel that the following "Copy link to Tweet" dialog window is redundant: I'd just like to copy the link without that.

I'd be very glad if you add an option to skip the dialog window on BetterTweetDeck.

<img width="530" alt="20180516_181645_8fzlpa" src="https://user-images.githubusercontent.com/4289625/40108560-3ec90290-5936-11e8-9425-df0b0d18654b.png">

Regards,

**Comment by eramdam** [comment]
Right click on the date of a tweet, then copy that link, and boom you have a link to a tweet without using this menu :)
