### ISSUE TITLE
Activity column stops updating

### ISSUE THREAD

**Issue by BrosephJ** [eramdam/BetterTweetDeck#348]
After a short while my activity column feed will stop showing new events. This has always been an issue for me ever since installing the addon. This column will function normally when I disable BetterTweetDeck. On the sidebar a blue dot appears to signal that I have new activity to view but clicking the top of the column won't show anything new. Refreshing TweetDeck will allow the column to work again for a short while.

Informations
>Version: 3.7.2
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.97.1183.3

Settings dump
> {
  "clear_column_action": false,
  "collapse_columns": false,
  "collapse_columns_pause": true,
  "css": {
    "actions_on_hover": true,
    "actions_on_right": false,
    "bigger_emojis": true,
    "character_count": true,
    "collapse_dms": false,
    "hide_context": false,
    "hide_like_rt_indicators": false,
    "minimal_mode": false,
    "no_bg_modal": true,
    "no_col_icns": true,
    "no_scrollbars": false,
    "og_dark_theme": false,
    "round_pic": false,
    "show_provider_indicator": false,
    "show_verified": true,
    "slim_scrollbars": true,
    "small_icns_compose": true,
    "system_fonts": false,
    "usrname_only_typeahead": true
  },
  "ctrl_changes_interactions": {
    "enabled": false,
    "mode": "owner"
  },
  "custom_columns_width": {
    "enabled": false,
    "size": "250px"
  },
  "custom_css_style": "",
  "custom_ts": {
    "full": "",
    "short": ""
  },
  "download_filename_format": "{{postedUser}}-{{tweetId}}-{{fileName}}.{{fileExtension}}",
  "download_item": false,
  "edit_item": true,
  "favstar_item": true,
  "flash_tweets": {
    "enabled": true,
    "mode": "mentions"
  },
  "full_aft_24": false,
  "hotlink_item": false,
  "installed_date": 1526747432275,
  "installed_version": "3.7.2",
  "keep_hashtags": true,
  "make_search_columns_first": false,
  "mute_hashtags": true,
  "mute_source": true,
  "need_follow_banner": false,
  "nm_disp": "both",
  "no_gif_pp": false,
  "no_hearts": false,
  "no_tco": true,
  "old_replies": false,
  "pause_scroll_on_hover": false,
  "share_item": {
    "enabled": true,
    "short_txt": false
  },
  "thumbnails": {
    "500px": true,
    "bandcamp": true,
    "cl_ly": true,
    "dailymotion": true,
    "deviantart": true,
    "dribbble": true,
    "droplr": true,
    "flickr": true,
    "gfycat": true,
    "giphy": true,
    "gyazo": true,
    "imgur": true,
    "instagram": true,
    "miil_me": true,
    "mixcloud": true,
    "moby_to": true,
    "nicoseiga_jp": true,
    "nicovideo_jp": true,
    "photozou": true,
    "pixiv_net": true,
    "plus": true,
    "skitch": true,
    "soundcloud": true,
    "spotify": true,
    "streamable": true,
    "ted": true,
    "tinami": true,
    "tumblr": true,
    "twitch_tv": true,
    "universal": true,
    "vimeo": true,
    "worldcosplay_net": true,
    "yfrog": true,
    "youtu_be": true
  },
  "ts": "absolute_us",
  "uncollapse_columns_unpause": false,
  "update_title_on_notifications": true
}

**Comment by eramdam** [comment]
Is this still happening? I'm gonna close this issue for inactivity. Feel free to re-open if this still happens.

**Comment by BrosephJ** [comment]
Yes, this is still happening! I've changed to Chromium Version 69.0.3481.0 (Official Build) (64-bit). Newest version of the addon. =(

**Comment by eai04191** [comment]
Previously, I had the same problem.
The cause was a Mute. When I deleted all mute words, problems no longer occur. This may be useful for solving.

**Comment by BrosephJ** [comment]
My muted words list is actually pretty huge. There doesn't appear to be a way to import/export or else I'd remove all my mutes to try this. ;( I actually had forgotten I created this issue until I received an e-mail saying @eramdam had replied to it. I've been using another TweetDeck program since this issue had happened. I hope it gets fixed! I love BetterTweetDeck! <3 (I can't find the option to re-open this issue..)

**Comment by AmazingArcher23** [comment]
This happens for me also, but it's only my main Home tab for my main account, which is following over 1000 people. 

(MAJOR BUMP)

**Comment by eramdam** [comment]
Anyone has this happened to them again? I haven't had any reports since July/August?

Feel free to object and I'll re-open (even though I'm still not sure what part of BTD could even break that..)
