### ISSUE TITLE
New tweets pile on top

### ISSUE THREAD

**Issue by WcDuck** [eramdam/BetterTweetDeck#35]
How about a feature that would pile new tweets on top of the most recent tweet? In other words, a feature that would prevent Tweetdeck from pinning to top and allow users easily to read new tweets, right from where left off.

There is a "workaround" to scroll just a bit down so Tweetdeck doesn't automatically keep timeline in the uppermost position, but it's tedious in a long term.

**Comment by nullr1ver** [comment]
+1 would be very handy

**Comment by eramdam** [comment]
I'm pretty sure it's something being hard-coded in the TweetDeck's code so it might be hacky/unstable to do that.

**Comment by nullr1ver** [comment]
@eramdam Self-Assigned: In progress then ?

**Comment by eramdam** [comment]
@nullr1ver It's on my roadmap, but I'm not actively on it right now. And as I said before it might be verrrrryyyyyy hacky so I might end up not doing it.

**Comment by nullpixel1** [comment]
Oh. So you gave up?

**Comment by eramdam** [comment]
Yup. Totally forgot to comment why but basically it would mean kill and hijack what's meant to be a performance improvement from TweetDeck's side. We'll see in the future if I can do it at all but I have other priorities :)
