### ISSUE TITLE
Feature request: display account avatar on column header

### ISSUE THREAD

**Issue by babolivier** [eramdam/BetterTweetDeck#359]
I use BTD with several accounts, and try to group columns by account. However, some columns, such as searches, can't be created by another account than my main one, so for example I'll have a couple of columns (timeline and notifications) linked to my non-profit's account, and a search column on the non-profit's name so I don't miss a tweet, or on a hashtag we're interacting with, which are de facto linked to my personal account.
Sometimes it's easy to forget which column is linked to which account (especially on search columns which don't display that piece of info), so I sometimes find myself interacting with a tweet with the wrong account. I think it'd be an interesting feature to allow displaying in columns' header the avatar of the account the column is linked to.

**Comment by eramdam** [comment]
Added in [4.3.0](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.0)!
