### ISSUE TITLE
custom columns width css to be injected in head before custom css

### ISSUE THREAD

**Issue by HuskerDoggo** [eramdam/BetterTweetDeck#362]
Currently the css for the custom columns width option under interface gets injected into the head after btd custom css.
![chrome_2018-07-06_00-23-58](https://user-images.githubusercontent.com/39703646/42351023-407c5750-80b3-11e8-8565-6d03077de179.png)

This makes using responsive columns width in the custom css never apply
![chrome_2018-07-06_00-24-17](https://user-images.githubusercontent.com/39703646/42351064-689bacf4-80b3-11e8-86dd-dedb33ad69a1.png)
![chrome_2018-07-06_00-28-24](https://user-images.githubusercontent.com/39703646/42351104-88ff974e-80b3-11e8-8d99-4a1bc1c13801.png)

Please switch this around.

Can there also be an option for thinner column v-scrollbar that doesn't make the page h-scrollbar smaller? So I don't have to write custom css for that either.

**Comment by eramdam** [comment]
If you intend to change the column width with custom CSS I would advice to disable the option entirely and just use your custom CSS. That sounds like the most sensible option.

> Can there also be an option for thinner column v-scrollbar that doesn't make the page h-scrollbar smaller? So I don't have to write custom css for that either.

I'm not adding yet another level of granularity for this settings, so no, sorry.

**Comment by HuskerDoggo** [comment]
Oh yeah right i'm retarded
