### ISSUE TITLE
Feature Request: Enable "Like from accounts" option for all tweets

### ISSUE THREAD

**Issue by preethamvishy** [eramdam/BetterTweetDeck#363]
Request to add the good old "Like from accounts" feature to BTD.

**Comment by eramdam** [comment]
Doing so would break Twitter's API terms and the last thing I need is trouble with Twitter so no, sorry https://twitter.com/BetterTDeck/status/966368548854444032

**Comment by preethamvishy** [comment]
Oh I understand. Great work with BTD, Damien!
