### ISSUE TITLE
Expanding an image that was generated from a link in a tweet makes the expansion window exist "behind" other windows

### ISSUE THREAD

**Issue by peterdodds** [eramdam/BetterTweetDeck#368]
Steps to reproduce:

1\) Take a tweet with a link to an image, but which does not have an image uploaded directly to the tweet itself. This is how such a tweet looks with BTT and on Twitter

![chrome_2018-07-24_12-37-38](https://user-images.githubusercontent.com/15932191/43153436-4e785260-8f3f-11e8-8813-08ed5a32a1fb.png)

![2018-07-24_12-45-50](https://user-images.githubusercontent.com/15932191/43153548-91e14d4a-8f3f-11e8-9a8c-870f071c5b6c.png)

2\) Expand the image by clicking on it

![2018-07-24_12-38-07](https://user-images.githubusercontent.com/15932191/43153633-cc581bac-8f3f-11e8-9a84-47b444c537f1.png)

3\) Close this window by **clicking outside** of the content window, rather than clicking the X in the upper-right

4\) Open up something different, such as a user's list of tweets or another image that *was* uploaded to Twitter.

![2018-07-24_12-39-07](https://user-images.githubusercontent.com/15932191/43153709-0788f462-8f40-11e8-847e-e13afa097bfc.png)

![2018-07-24_12-39-39](https://user-images.githubusercontent.com/15932191/43153716-0d3225b4-8f40-11e8-9049-ffe88c1b7bc5.png)

As you can see, the first tweet's media will appear behind other, smaller windows such as a list of tweets. For other tweets with images, there will be an avatar and like/retweet markers from the original tweet overlapping the new tweet's information. This can only be solved by refreshing the page or manually closing the original tweet with the X button, either when it's exposed behind a tweet list or when you're viewing that tweet itself again. If you have a list of tweets open, this will close both the original tweet and the list.

This issue does not exist without BTT as the linked image's preview will not exist. This has existed for at least several months in my memory.

<details>
<summary>Debug info</summary>
Version: 3.7.8

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Settings dump
{
  "btd_logo": false,
  "clear_column_action": false,
  "collapse_columns": false,
  "collapse_columns_pause": true,
  "css": {
    "actions_on_hover": false,
    "actions_on_right": true,
    "bigger_emojis": true,
    "character_count": true,
    "collapse_dms": false,
    "hide_context": false,
    "hide_like_rt_indicators": false,
    "minimal_mode": false,
    "no_bg_modal": false,
    "no_col_icns": false,
    "no_scrollbars": false,
    "og_dark_theme": false,
    "round_pic": false,
    "show_provider_indicator": false,
    "show_verified": true,
    "slim_scrollbars": false,
    "small_icns_compose": true,
    "system_fonts": false,
    "usrname_only_typeahead": false
  },
  "ctrl_changes_interactions": {
    "enabled": false,
    "mode": "owner"
  },
  "custom_columns_width": {
    "enabled": true,
    "size": "325px"
  },
  "custom_css_style": "",
  "custom_ts": {
    "full": "MMM D YYYY, h:mm:ss A",
    "short": "MMM D YYYY, h:mm:ss A"
  },
  "download_filename_format": "{{postedUser}}-{{fileName}}.{{fileExtension}}",
  "download_item": false,
  "edit_item": true,
  "favstar_item": true,
  "flash_tweets": {
    "enabled": true,
    "mode": "mentions"
  },
  "full_aft_24": true,
  "hotlink_item": false,
  "installed_date": 1490914771375,
  "installed_version": "3.7.8",
  "keep_hashtags": false,
  "make_search_columns_first": false,
  "mute_hashtags": true,
  "mute_source": true,
  "need_follow_banner": false,
  "need_update_banner": false,
  "nm_disp": "both",
  "no_gif_pp": false,
  "no_hearts": false,
  "no_tco": true,
  "old_replies": false,
  "old_search": false,
  "pause_scroll_on_hover": false,
  "regex_filter": false,
  "share_item": {
    "enabled": true,
    "short_txt": false
  },
  "stop_gifs": true,
  "thumbnails": {
    "500px": true,
    "bandcamp": true,
    "cl_ly": true,
    "dailymotion": true,
    "deviantart": true,
    "dribbble": true,
    "droplr": true,
    "flickr": true,
    "gfycat": true,
    "giphy": true,
    "gyazo": true,
    "imgur": true,
    "instagram": true,
    "miil_me": true,
    "mixcloud": true,
    "moby_to": true,
    "nicoseiga_jp": true,
    "nicovideo_jp": true,
    "photozou": true,
    "pixiv_net": true,
    "plus": true,
    "skitch": true,
    "soundcloud": true,
    "spotify": true,
    "streamable": true,
    "ted": true,
    "tinami": true,
    "tumblr": true,
    "twitch_tv": true,
    "universal": true,
    "vimeo": true,
    "worldcosplay_net": true,
    "yfrog": true,
    "youtu_be": true
  },
  "ts": "relative",
  "uncollapse_columns_unpause": false,
  "update_title_on_notifications": true
}
</details>

**Comment by eramdam** [comment]
I can't repro this so I'll assume it's not happening anymore. Closing.
