### ISSUE TITLE
Req: Add support for inline images from imagehost mltshp.com

### ISSUE THREAD

**Issue by jxyzn** [eramdam/BetterTweetDeck#370]
Sample tweet including image:
https://twitter.com/Best_of_MLTSHP/status/1029814375098400768

Image "page" URLs look like:
https://mltshp.com/p/1EF7M

Direct image URL derived from page URL:
https://mltshp.com/r/1EF7M

Image URL will return a GIF, PNG, or JPEG image.

**Comment by eramdam** [comment]
Fixed in next release now that https://github.com/eramdam/BetterTweetDeck/pull/371 is merged
