### ISSUE TITLE
keyboard shortcut doesn't work with some IME modes

### ISSUE THREAD

**Issue by hibiyasleep** [eramdam/BetterTweetDeck#376]
This set of input events work as normal, for example in **English (US)** / **Japanese (Romaji)** keyboard:
```
keydown  keyCode=74  (J)   which=74  (J)   charCode=0
keypress keyCode=106 (j)   which=106 (j)   charCode=106 (j)
keyup    keyCode=74  (J)   which=74  (J)   charCode=0

keydown  keyCode=75  (K)   which=75  (K)   charCode=0
keypress keyCode=107 (k)   which=107 (k)   charCode=107 (k)
keyup    keyCode=75  (K)   which=75  (K)   charCode=0
```

but on some IMEs input non-alphabet directly, for example **Korean**, doesn't work:
```
keydown  keyCode=74  (J)   which=74  (J)   charCode=0
keypress keyCode=12627     which=12627     charCode=12627
keyup    keyCode=74  (J)   which=74  (J)   charCode=0

keydown  keyCode=75  (K)   which=75  (K)   charCode=0
keypress keyCode=12623     which=12623     charCode=12623    
keyup    keyCode=75  (K)   which=75  (K)   charCode=0
```

as you can see, `keypress` doesn't really handled on such kind of IME. Maybe this can be fixed with imitating `keypress` event on weird keycode?

ps: Of course this is bug of TweetDeck itself; but I'm posting here because I saw this 2013, reported this 2014, reported again at 2015, *still not fixed* in 2018.

(outputs tested/copied from [here](https://unixpapa.com/js/testkey.html), on Chrome/macOS & Windows)

**Comment by eramdam** [comment]
If it's a TweetDeck bug I'd avise you to forward it to https://twitter.com/andrs on Twitter, they've been pretty receptive about bugs in the past. Even though I of course can't tell you for sure they'll fix it 😅

**Comment by hibiyasleep** [comment]
They didn't responded, so I posted here as feature request ;( well, I'll try report once more.

**Comment by eramdam** [comment]
I understand 😞 The thing is, I don't know if we can hijack the keyboard code in TweetDeck without breaking something :/
And even if we do, I can't think of an elegant way to fix this. I'd be curious to see what happens on other browsers because it definitely sounds fishy that only the keypress event has different data 🤔
