### ISSUE TITLE
Expanding media overflows for small screens/windows

### ISSUE THREAD

**Issue by arontx** [eramdam/BetterTweetDeck#380]
Expanding media overflows for small screens/windows e.g.

![before](https://user-images.githubusercontent.com/1565924/45833777-25998080-bccb-11e8-8d24-ec15405bb862.PNG)

Issue seems to be with this:
https://github.com/eramdam/BetterTweetDeck/blob/6c97232780c8539d5ec4f8768a6094420830cf2f/src/css/features/no-bg-modal.css#L40

I submitted #379 to remove the minimum width entirely.

Alternatively, you can override it by adding this to your Custom CSS
html.btd-on .btd__no_bg_modal .med-embeditem{min-width:0px}

e.g.

![after](https://user-images.githubusercontent.com/1565924/45833814-3d710480-bccb-11e8-9683-7aee5be90c0d.PNG)

**Comment by eramdam** [comment]
Will be fixed by next release now that https://github.com/eramdam/BetterTweetDeck/pull/379 is merged
