### ISSUE TITLE
Trending column

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#382]
I see the trending column seems to has any enhacement via better tweetdeck.

Some ideas can be:
- Make it collapsable (it isn't at this moment).
- Make it collapsable, and show some info about the trendings in some way in the collapsed part of the column.
- Show the trendings directly in the trending icon bar tooltip.
- Show the trendings in a floating div when clicking an icon (something like the search option).

(Only for pointing out, IMHO the best way to show the trendings is not showing them in a column)

Other ones more difficult can be some sort of "news bar" or alert of new trendings entering in the list, more descriptions and info of each one, more trendings than ten (Twidere App shows normally more than twenty, how? i don't know https://github.com/TwidereProject/Twidere-Android).

I'm only opening the talk, because the costumization of that column can be useful.

**Comment by eramdam** [comment]
> Some ideas can be:
> 
>     * Make it collapsable (it isn't at this moment).
> 
>     * Make it collapsable, and show some info about the trendings in some way in the collapsed part of the column.
> 
>     * Show the trendings directly in the trending icon bar tooltip.
> 
>     * Show the trendings in a floating div when clicking an icon (something like the search option).
> 
> 

Not sure what the 3rd item is about, and I definitely can't do the 4th one, but the first two items are fixed in v4 that just came out!

**Comment by LukasThyWalls** [comment]
> Not sure what the 3rd item is about, and I definitely can't do the 4th one, but the first two items are fixed in v4 that just came out!

Thanks!

I was refering to this: 

![BTDeck_TrendIconTooltip](https://user-images.githubusercontent.com/1467366/113629249-7218f180-9666-11eb-8bd3-baec14c31d01.png)

However, if you can't do the 4th, i don't think it can be possible that one too.

The main thing i'm talking about is to see the trending topics easily without scrolling to the trending column, normally i don't have it in the first screen, so something to see the trending list (a hovering an icon with popup, a news bar, i don't know...) i see useful. But maybe is impossible to extract that data from the column...

**Comment by eramdam** [comment]
Yeah no all the Trending column code lives in its own part of TweetDeck's code so it's all out of reach 😬
