### ISSUE TITLE
[Feature] Horizontal menu

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#383]
I tried this https://userstyles.org/styles/137211/tweetdeck-horizontal-menu but maybe is outdated because it tries but it does wrong.

Maybe can be added a working one. Do you think it could be done only with css or maybe needs others kind of changes?

**Comment by eramdam** [comment]
I'd have to look into it. I honestly don't know what it would take.

**Comment by eramdam** [comment]
cc @dangeredwolf i feel like you might have an opinion on this :D

**Comment by dangeredwolf** [comment]
yes, for the longest time, ModernDeck used a horizontal menu :D 

Though, since 7.3 as I recall, the traditional Left position is the default now.

**Comment by dangeredwolf** [comment]
So it is doable but it has side effects that can't be resolved that caused me to discourage it.

Scrolling messes up, at least in chrome, so if you implement it properly you have to hold Shift to scroll.

Clicking and dragging icons will not work right.

So what I've found is that while it looks good, it's not a great experience.

I might remove it entirely in version 8.1 to simplify code.
