### ISSUE TITLE
Add support for Bookmarks

### ISSUE THREAD

**Issue by davecranwell-adestra** [eramdam/BetterTweetDeck#385]
Twitter seem determined not to add support for Bookmarks to Tweetdeck, despite the recent news of Jack dumping the Like system - everyone's previous way of bookmarking.

Are there any plans to add it in BTD?

**Comment by davecranwell-adestra** [comment]
I see now that there is no endpoint for bookmarks. Good job Twitter, what a mess.

**Comment by pixeldesu** [comment]
@davecranwell-adestra yeah, unfortunately a lot of new features don't get public API endpoints.

Developers have to use the most basic information, which has been provided for years by now, there only have been adjustments/deprecations in existing endpoints, so we can't implement new features on our own.

The TweetDeck team itself is really speeding up in development pace recently, so we might just have Bookmarks pop up at random sooner or later!

**Comment by Julianoe** [comment]
Came here to add same thing. I really don't understand the choices made by twitter for Bookmarks. Available on mobile but not on desktop or Tweetdeck... and no real API integration either. Annoying. It could be a good feature.
