### ISSUE TITLE
Columns stuck on loading

### ISSUE THREAD

**Issue by Mohamed3on** [eramdam/BetterTweetDeck#389]
For some reason, TweetDeck is stuck on loading for all columns when I use BTD. Disabling it solves the issue.
My BTD version is: 3.8.0

**Comment by eramdam** [comment]
1. Are you sure you don't have a filter that might mute too many tweets somehow?
2. Can you open the console of your browser and see if there are any errors when BTD is enabled? I can't really help with a vague "Stuff is not loading".

**Comment by Mohamed3on** [comment]
Btw, this is on Chrome 71. Not sure what other info I can give, but feel free to ask!

**Comment by Mohamed3on** [comment]
I just tried with another account, and it worked fine. So it's a problem with my account somehow. Clearing the cookies and signing in again doesn't help it either (from my account)._

**Comment by eramdam** [comment]
Some people had something similar, check your mutes https://twitter.com/DenaghDesign/status/1068248940104114176

**Comment by Mohamed3on** [comment]
Yeah, I also had "3" muted for some reason, although I never did that. What could've caused that?

**Comment by eramdam** [comment]
@Mohamed3on I'm not sure, my theory is that somehow we messed up when merging https://github.com/eramdam/BetterTweetDeck/pull/387 and it caused some mix-up in mutes because we were changing the key of an already existing filter and I didn't notice :/ (cc @pixeldesu )
