### ISSUE TITLE
Add "disable emojis" option

### ISSUE THREAD

**Issue by phiphou** [eramdam/BetterTweetDeck#39]
I dont'like emojis. I'm probably not the only one. What about a option that allow us to disable them ?

**Comment by eramdam** [comment]
Idea is interesting, should they simply be removed from the tweets or should we put something instead of them? (Because if I do this, there is no way I'm just hiding them, it would be stupid and most likely kill the meaning of some tweets)

**Comment by nullr1ver** [comment]
TBH, you could replace them with the alien box that appears when you type an emoji that doesn't yet exist

**Comment by eramdam** [comment]
@nullr1ver Yeah.. After rethinking about it I think it's a broken idea from start, but I could add a "hide emojis" at some point.
