### ISSUE TITLE
RT/Like indicators not working 

### ISSUE THREAD

**Issue by IanFHood** [eramdam/BetterTweetDeck#392]
It appears the html is not being injected on tweets (other than on the detail view)

![selection_999 498](https://user-images.githubusercontent.com/1206311/50383643-1977e300-066d-11e9-887b-983f954bcbe6.png)

![selection_999 500](https://user-images.githubusercontent.com/1206311/50383658-6956aa00-066d-11e9-9fff-791ca28a1b7a.png)

![selection_999 499](https://user-images.githubusercontent.com/1206311/50383676-b2a6f980-066d-11e9-9fc5-25ad0631f1de.png)

**Comment by eramdam** [comment]
As far as I can tell this works now.
