### ISSUE TITLE
[Feature] One click delete 

### ISSUE THREAD

**Issue by Julianoe** [eramdam/BetterTweetDeck#393]
Just an idea because i did not see any Firefox extension that did it: an tickable option to allow the appearance of a trash bin icon to delete a tweet in one click.

What do you think?

**Comment by eramdam** [comment]
Hum, given the streaming nature of TweetDeck, i feel like it would be easy to click on the delete button by mistake so we'd need a confirmation alert, but that would defeat the point 😅
