### ISSUE TITLE
unable to tweet and reply on DM

### ISSUE THREAD

**Issue by smilodooon** [eramdam/BetterTweetDeck#398]
im having problems with the addon on firefox when im tweeting something it stays loading, but if i disable the addon it works, also getting a DM and try to reply it acts crazy and takes me back to all my DMs but without the addon works
![image](https://user-images.githubusercontent.com/46630777/51076391-e6ba7c80-1665-11e9-989a-b99339a71baa.png)

**Comment by eramdam** [comment]
Is it still happening? I haven't had other reports of this. I'm closing the issue, feel free to ping me/re-open if that's still an issue.
