### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by sejour-a** [eramdam/BetterTweetDeck#4]
Problems with Emojis in tweets pre-visualisations during answering, but not in columns :
![Example](https://cloud.githubusercontent.com/assets/6839286/2690933/d010c914-c36b-11e3-9b18-4f974027fa04.png)

**Comment by eramdam** [comment]
Testing __stuff__ out because I can do [that](https://frontapp.com)

**Comment by eramdam** [comment]
<a href="http://apple.com">TESTING</a>

**Comment by rodrigopolo** [comment]
That's odd, the function that does that should replace it, maybe it is an emoji out of the ones that Twitter/Twemoji have available, I replaced that function in the fork I did and it works great:
![emoji](https://cloud.githubusercontent.com/assets/1511174/10505022/96b9947e-72c5-11e5-8c2e-ae53818926e4.png)
