### ISSUE TITLE
Clear option in the header

### ISSUE THREAD

**Issue by symac** [eramdam/BetterTweetDeck#40]
Hello,
i have discovered BTD while searching for a way to have a directly accessible "Clear" button. At the moment I have to show the drop menu then click clear and I would find it quite interesting to have this button in the header of the column to be able to clear the column in one click.

I assume it wouldn't be that hard to add this as an option given everything the extesnion is already doing!

**Comment by eramdam** [comment]
I will look at it but doing this in a safe way might be tricky, but I'm adding it to the 3.0 roadmap

**Comment by symac** [comment]
Hi @eramdam it has been a long time but even if the issue has been closed, I can't find how the commit fixed that. And I can't see any way in the option to have the "clear" button to be shown in the columns header without opening the dropdown menu.

**Comment by eramdam** [comment]
Hum, I must have closed this because I was on a closing spree and mis-clicked. Sorry about that. I didn't look into that yet. **Hopefully** it should not be too hard to do, the tricky part will be to hook to some private TweetDeck function that does the clearing.

**Comment by eramdam** [comment]
@symac happy to announce this is now a feature in the last release!

**Comment by symac** [comment]
Thanks @eramdam that's great!
