### ISSUE TITLE
Feature Request: Likes Order + Unicode 11

### ISSUE THREAD

**Issue by petitbambi** [eramdam/BetterTweetDeck#401]
Hello, 
I really love the change twitter has implemented where likes on a person's profile are shown in the order that the person has liked them, rather than the order that the tweet was made in. 
I'd really love it if this feature could be brought to tweetdeck as it's super helpful to me when I want to bookmark things or find them on mobile and want to retweet it to another account. 
Ofcourse if it's an old tweet it's hard to find, but having the likes arranged in a way that shows the latest liked tweet first regardless of when it was created on tweetdeck as well would be extremely helpful !

As a sidenote, twitter's emoji picker has also been updated with the lastest unicode, and I'd really love it if they could be brought to tweetdeck as well so I don't have to switch to basic twitter or google for them in order to use them. 

Thank you in advance !

**Comment by eramdam** [comment]
Closing with `wontfix` for the above reasons.
