### ISSUE TITLE
Hide scrollbars not working - latest Waterfox

### ISSUE THREAD

**Issue by plisskenrd** [eramdam/BetterTweetDeck#402]
Just as the title says. Hide scrollbars function suddenly stopped working. there was no browser update or add-ons changing at that moment, so idk what triggered it... Checking the settings option off and on doesn't change anything now, scrollbars visible all the time.
After that I installed latest Firefox just to check and it's working OK there.

**Comment by eramdam** [comment]
I don't know what version of Firefox Waterfox is using but it needs to be at least 64 since this is when Firefox started supporting CSS scrollbars.

If it's based off an older version I can't do anything, sorry.
