### ISSUE TITLE
BTD not working anymore with Firefox Dev Edition

### ISSUE THREAD

**Issue by druxstr** [eramdam/BetterTweetDeck#405]
Hi,

BTD used to work with Firefox Dev Edition, but not anymore.

I tried with all other addons deactived, still no luck.

I can access settings, check some boxes, but it doesn't affect my Tweetdeck tab at all.

I'm using FF 66.0b9 (64 bits).

**Comment by eramdam** [comment]
I just tried on 66.0b9 on macOS and it works just fine. Can you show me how it looks? Do you at least get the settings icon in the sidebar? 
<img width="68" alt="image" src="https://user-images.githubusercontent.com/1409924/53256489-e0fc8180-367c-11e9-8bf8-babe6d43134d.png">

Are there any errors in the console that could be relevant?

**Comment by druxstr** [comment]
It looks like regular Tweetdeck, with no BTD enhancement.

I get this error in the console : 

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [read more] inject.js:18:12428

[Read more] unfolds these 4 lines :

    350 moz-extension://061c6271-8a2b-4279-ae22-268668fa4120/js/inject.js:18
    n moz-extension://061c6271-8a2b-4279-ae22-268668fa4120/js/inject.js:1
    <anonymous> moz-extension://061c6271-8a2b-4279-ae22-268668fa4120/js/inject.js:1
    <anonymous> moz-extension://061c6271-8a2b-4279-ae22-268668fa4120/js/inject.js:1

Where 061c6271-8a2b-4279-ae22-268668fa4120 is BTD internal UUID

**Comment by eramdam** [comment]
Again, I can not reproduce on my end when running Firefox Developer Edition, so I can't really help you here. 
![screen shot 2019-03-06 at 7 25 26 am](https://user-images.githubusercontent.com/1409924/53892372-06747e00-3fe1-11e9-82fe-d83c9315e7f1.png)

**Comment by eramdam** [comment]
I'll close for staleness, let me know if this is still an issue.
