### ISSUE TITLE
feature request: share to telegram

### ISSUE THREAD

**Issue by mortyobnoxious** [eramdam/BetterTweetDeck#406]
is it possible to embed optional share to telegram icon into tweets?

example:
![image](https://user-images.githubusercontent.com/42044258/53666394-0b52ce00-3c7f-11e9-997c-f80571de3092.png)

**Comment by eramdam** [comment]
I barely use Telegram so I have no idea how a "share to Telegram" action would work/be possible 😅

**Comment by mortyobnoxious** [comment]
basically adding a prefix:  `https://telegram.me/share/url?url=example.com`
