### ISSUE TITLE
TweetDeck update break extension load

### ISSUE THREAD

**Issue by LeoColomb** [eramdam/BetterTweetDeck#407]
Error on Version 4.0.190305152530-a83c3c7 (web) on Chrome latest

<img width="345" alt="capture d ecran 2019-03-05 a 17 22 00" src="https://user-images.githubusercontent.com/846943/53820083-6af4f600-3f6b-11e9-9ec6-e5f1bd190095.png">

<img width="935" alt="capture d ecran 2019-03-05 a 17 28 23" src="https://user-images.githubusercontent.com/846943/53820479-20c04480-3f6c-11e9-8a58-b5ab641ecd7b.png">

**Comment by catright** [comment]
I got a different error just after update tweetdeck to same version.
I'm using firefox.

![screenshot_2019-03-06 tweetdeck](https://user-images.githubusercontent.com/31341582/53820757-c5b04100-3faf-11e9-943a-2dd279c20950.png)

**Comment by key-moon** [comment]
It seems to caused by 'keep_hashtags' settings.
The same problem occurred, but it turned out if you turned off 'keep_hashtags' settings.
My environment:
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

**Comment by LeoColomb** [comment]
@key-moon Indeed, turning off 'keep_hashtags' "resolves" allows TweetDeck to load.

**Comment by eramdam** [comment]
It seems like TweetDeck reverted that update as I'm now getting another version number that seems to be older than the one listed in the issue (I saw it reverting in a matter of minutes).


Let's hope it won't break again 😬 🤞
