### ISSUE TITLE
Tweetdeck Update broke emoji support // Firefox, Waterfox, Chrome

### ISSUE THREAD

**Issue by ElDiablo74** [eramdam/BetterTweetDeck#409]
Hello. 

I have a Win 10 with October Windows Update and use mainly Waterfox and strangely got the 3.8.2. update for Waterfox as well, even if everywhere the 3.8.1 is being promoted as the newest Version. 
Since that Update I have lost emoji Support, no matter which Browser I use (Waterfox 56, Firefox 65, or Chrome 72,xxx) 
As seen in the Screenshot, the Button for emojis seems to have gone. 
I understand, that with Waterfox there might be an Issue as it has to support Version 65 from Firefox. 
Nowhere is though mentioned, that emoji Support would be broken with actual FF and Chrome Releases. 
I have tried disabling other addons, but same result. Any help, or what can I do, to help debug? (I'm not a coder though) 

thank you

**Comment by ElDiablo74** [comment]
![grafik](https://user-images.githubusercontent.com/47400393/54029842-23a87880-41aa-11e9-9e89-eb0803f329c4.png)

**Comment by janimuze** [comment]
Noticed this morning too. There's [a thread for this on twitter](https://twitter.com/BetterTDeck/status/1103693397699620865) already.
It seems to be a known issue with the latest update.

**Comment by eramdam** [comment]
I have a PR in the work that'll fix this https://github.com/eramdam/BetterTweetDeck/pull/408

**Comment by eramdam** [comment]
Forgot to close this when the corresponding PR was merged.
