### ISSUE TITLE
"Remove t.co redirection on links" is removing the link itself

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#415]
This is happening to me with this tweet https://twitter.com/motorpuntoes/status/1107680668518100992

With "Remove t.co redirection on links" activated the link is gone, there is no link at all. With "Remove t.co redirection on links" Off the link is there.
This is the first time i see this, seems other links are showing normal. I don't know why this one is not showing the link at all.

![imagen](https://user-images.githubusercontent.com/1467366/54556695-b373d100-49b9-11e9-948e-430ed93b3ef4.png)

Thanks in advance.

**Comment by eramdam** [comment]
Is this still happening? Otherwise I'll close this for inactivity.

**Comment by LukasThyWalls** [comment]
I revisited the tweet and the link is there now. Thanks!
