### ISSUE TITLE
Reorganize tweets and replies

### ISSUE THREAD

**Issue by aek** [eramdam/BetterTweetDeck#417]
It's there a way to reorganize in a Tweet the way the replies are displayed?
Meaning that I wanna be able to display the whole tree of replies to the tweet they belong to be able to better visualize how the thread was build.
Something like this:
http://twitter.theinfo.org/114718659942940672#id114718931704483840
Or at least the way Reddit works to display replies.
It's there a way?

**Comment by eramdam** [comment]
As useful as it would be, this would require a big amount of changes into the way TweetDeck lists tweets and renders them and would be very complex to do 😕 Can't really afford to do that without potentially breaking a lot of things 😞
