### ISSUE TITLE
feature:Warn a specific words

### ISSUE THREAD

**Issue by kgtkr** [eramdam/BetterTweetDeck#418]
I want a feature to register a word and warn the tweets containing that word before the tweets.
You can avoid posting personal information etc. by mistake.

**Comment by eramdam** [comment]
I'll consider it but honestly given the amount of work needed UI/UX-wise and the few amount of people who requested it, it won't be very high up my priorities list.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
