### ISSUE TITLE
Firefox CSS Issue

### ISSUE THREAD

**Issue by wes-jordan** [eramdam/BetterTweetDeck#419]
Firefox is showing fat white lines where the scrollbar would normally be (right, bottom) on the top left panel (search, all columns, add column). I corrected it using the Custom CSS setting & so far I've not seen that my fix created any additional issues.

Here's the Custom CSS fix I added:
`html.dark .antiscroll-inner { overflow: auto; }`

**Comment by eramdam** [comment]
Is that still happening? I'm on Firefox on macOS and I don't think I've noticed anything. 

I'm gonna close this, let me know if I need to re-open.
