### ISSUE TITLE
feature request: reply to tweet specified by URL

### ISSUE THREAD

**Issue by iconmaster5326** [eramdam/BetterTweetDeck#420]
As a person with multiple accounts, I get the problem a lot:

1. I'm on account A, and I open the web client to look through someone's timeline.
2. Many tweets in, I find something I want to reply to... From account B.

The only solution is to log out of account A on the web client, log into account B, and bring up the same tweet. TweetDeck, which holds both accounts A and B, cannot help me here. There is no way I can easily get an arbitrary tweet in the composer so I can reply to it. But what if it could?

Some feature so that, if you have a tweet's URL, you can pull it up in the composer, would be really useful. Furthermore, I also find this happening with likes and RTs, too, so maybe a general "interact with tweet specified by URL" feature is in order?

**Comment by eramdam** [comment]
I remember that @EntranceJew mentioned something along those lines, a feature to open a given tweet in TweetDeck by its URL. I admit I don't know how feasible that is however 🤔
