### ISSUE TITLE
Add an option to prevent GIFs from autoplaying

### ISSUE THREAD

**Issue by babolivier** [eramdam/BetterTweetDeck#421]
I use TD's account and search columns to keep track of what's happening on a few projects I'm working with.
I recently had to move one of these because it's tracking an account that's not very active and posted a GIF a few weeks ago, and it was next to a few columns that most of the time produce long tweets I'm interested in reading, and having the GIF looping over and over on the side was preventing me from focusing on the tweets I was reading. I know I can pause the GIF, but obviously it starts playing again as soon as I refresh TD.
It would be nice if BTD provided an option that makes TD not autoplay GIFs by default, and plays them only when the user clicks on them (basically the opposite of what it currently does).

**Comment by NuroDev** [comment]
TweetDeck has this option available natively. If you check your TweetDeck settings there is a toggle for auto playing gifs.
<img width="444" alt="Screenshot 2019-06-10 at 13 07 25" src="https://user-images.githubusercontent.com/4991309/59194393-ce9d4980-8b80-11e9-8c1d-ea7b490cdc1a.png">

**Comment by babolivier** [comment]
Ah, I spent some time looking for this setting but apparently not at the right place. Thanks, and sorry for the noise.

**Comment by Neurotoxin001** [comment]
Video is still auto playing when open a replies.
