### ISSUE TITLE
"Download media" button not working

### ISSUE THREAD

**Issue by plisskenrd** [eramdam/BetterTweetDeck#422]
"Download media" suddenly stopped responding. Clicking does nothing; on mouse hover the browser shows it leads to https://tweetdeck.twitter.com/# url. 

![image](https://i.imgur.com/ohruzmz.png)

    Version: 3.9.4
    User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.11

**Comment by eramdam** [comment]
Yup, am aware of it. Looks like TweetDeck updated their CSP (Content Security Policy) to block those network calls, I'll need to work around this somehow.

**Comment by plisskenrd** [comment]
much appreciated!

**Comment by eramdam** [comment]
This will be fixed in the next release
