### ISSUE TITLE
"Keep tweeted hashtags" crashes TweetDeck  

### ISSUE THREAD

**Issue by anein** [eramdam/BetterTweetDeck#423]
Greetings!

I just came across a bug: TweetDeck stops working when I turn on the "Keep tweeted hashtags" option.

![Screenshot from 2019-07-10 16-03-44](https://user-images.githubusercontent.com/435658/60971722-7eefa080-a32d-11e9-90de-1869ac454f4e.png)

**Comment by eramdam** [comment]
What version of the extension are you running? This has been fixed months ago.
