### ISSUE TITLE
Instagram previews sometimes doesn't show

### ISSUE THREAD

**Issue by jackie-chan** [eramdam/BetterTweetDeck#43]
Sometimes instagram previews don't show up, but in other cases they do.
![image](https://cloud.githubusercontent.com/assets/277094/10560066/a49ce0e6-74cd-11e5-8e64-842f6ca9bb9a.png)
Thumbnails have been enabled in both columns too.
Thanks!

**Comment by Revod** [comment]
I have the same problem
![captura de pantalla de 2015-10-18 13 32 56](https://github-cloud.s3.amazonaws.com/assets/10109689/10565546/d6e3024a-759c-11e5-960f-9dc2d198874c.png)
![captura de pantalla de 2015-10-18 13 33 19](https://github-cloud.s3.amazonaws.com/assets/10109689/10565548/daf53ed4-759c-11e5-9480-81b6b161996e.png)

**Comment by rubin110** [comment]
Having the same issue however it seems to be all the time. Same issue with Flickr links in posts.
