### ISSUE TITLE
[Request] Option to make video player larger

### ISSUE THREAD

**Issue by Neurotoxin001** [eramdam/BetterTweetDeck#430]
It's too small now. 

![image](https://user-images.githubusercontent.com/39812401/62070072-6b579b80-b242-11e9-8f73-4155944813c4.png)

**Comment by Neurotoxin001** [comment]
Bump?

**Comment by eramdam** [comment]
Will be fixed in the next release.

**Comment by eramdam** [comment]
Fixed in [4.5.2](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.2)!
