### ISSUE TITLE
Feature Request: Disable twitter video autoplay

### ISSUE THREAD

**Issue by YoderofKansas** [eramdam/BetterTweetDeck#431]
When I click a twitter video, the video starts playing before player actually finishes popping up, causing me to miss a little over the first second of video.  I'd like to see an option that disables all video playing until I actually hit the play button.

Video tweet in question for an example: https://twitter.com/shazyreplicant/status/1155199007364407296

**Comment by Neurotoxin001** [comment]
bump

**Comment by WizardShotTheFood** [comment]
I'd like to see this as well.

**Comment by eramdam** [comment]
This doesn't apply anymore with TD's new HTML5 video player.
