### ISSUE TITLE
[Feature] all mentions tab not loading

### ISSUE THREAD

**Issue by alimeigeni** [eramdam/BetterTweetDeck#434]
I've never had an issue with this function until now. I recently was logged out due to a Chrome browser update, but when I logged back in, this column was no longer loading tweets from any of my accounts. It continues to have a spinning icon that says "Loading". I've also checked my muted words and nothing out of the ordinary or odd that would result in tweets not loading. Any possible ideas on why or how to resolve?

**Comment by NuroDev** [comment]
This sounds like it could be more of an issue with TweetDeck issue than BetterTweetDeck issue but just to be sure, can you try opening your Chrome Dev tools (F12 on Windows | Cmd+Shift+I on Mac) and see if there are any errors being logged in the `Console` tab.

**Comment by eramdam** [comment]
Gonna close this, it's been half a year so i'm going to assume whatever was going on has been fixed.
