### ISSUE TITLE
multiline regex mute filtering

### ISSUE THREAD

**Issue by isuldor** [eramdam/BetterTweetDeck#435]
Is there a way to filter over an entire tweet with a regular expression, including line breaks?  I have the following filter to mute hashtag spam: `([#$]\w+.*){3,}`  That filter works on most tweets which are on a single line, but many tweets still break up their hashtag spam on separate lines. Here's an example that isn't filtered by that rule:
```
test
#one
#two 
#three 
```
I understand this might be a limitation on whatever regex engine that is used, or I might just be oblivious as to the correct way of filtering over multiple lines. I tried adding variations of my filter with `\n` and `\r` and didn't have any success.

**Comment by eramdam** [comment]
I guess this might be helpful? https://twitter.com/BetterTDeck/status/928336830902104066
