### ISSUE TITLE
Download media shortcut weird behavior

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#436]
Latest update fixed broken download media shortcut but now it acts strange, only works until the browser is closed. Add-on needs to be re-installed each time browser is started for it to work. 
Browser is Waterfox/56.2.13

**Comment by plissken1138** [comment]
Currently trying out Waterfox 68, supposedly based on new Firefox. While scroll issue isn't present, Download Media shortcut shows the same behavior.

**Comment by eramdam** [comment]
Going to close since it was established I can't really chase down the support because of how old of a Firefox version it uses.
