### ISSUE TITLE
Hide scrollbars - no mouse wheel scroll?

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#437]
Not sure if it is feature or a bug, but when Hide scrollbars is selected scrolling columns with mouse wheel doesn't work in Waterfox 56.2.13. Would be nice to have mouse scroll with Hide scrollbars if possible. Thanks!

**Comment by plissken1138** [comment]
Thanks for checking! I'm migrating stuff to Waterfox Alpha 68, that'll solve these nuisances.

**Comment by eramdam** [comment]
Going to close since it was established I can't really chase down the support because of how old of a Firefox version it uses.
