### ISSUE TITLE
[Feature] Remember collapsed/uncollapsed columns

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#438]
Collapsed columns do remain collapsed after page reload, I thought it would be practical if collapsed columns would remain so after browser restart. A global setting for "remember collapsed/uncollapsed columns" or individual one in column preferences,

**Comment by eramdam** [comment]
It's already the case. We save them in LocalStorage, but if for some reason your browser erases that then it's gone.

**Comment by eramdam** [comment]
https://github.com/eramdam/BetterTweetDeck/blob/5c2e4510388c78b32651476719f3de75be185ccb/src/js/inject.js#L1260-L1263
