### ISSUE TITLE
Ability to change colors of columns for easier multi account management

### ISSUE THREAD

**Issue by wingless1** [eramdam/BetterTweetDeck#44]
It would be a great addition to the BetterTweetDeck if there was an option to change colors of columns.

I manage 3 account (One personal, two company) and i find it a little bit hard to seperate their related columns. I use different columns for all the accounts notifications, messages etc. You might imagine there is a lot of clutter :)

**Comment by eramdam** [comment]
I like the idea a lot, I'm adding this to the 3.x features "roadmap"

**Comment by viki53** [comment]
Any new on this? It's 3.4.7 already and I don't see any option for this.

Any idea where to get started for a PR?

**Comment by EntranceJew** [comment]
The best way to go about this would be to utilize `.js-column` for the column header and scroll bar and `.js-stream-item` for the individual tweets. If you follow the methods that were laid out to map a column key in the header to a permanently addressable column ID for the column collapse code you could find a way to map a color to a column. [here's a good bit of code that references other pieces of code that does things similar to what i mention](https://github.com/eramdam/BetterTweetDeck/blob/master/src/js/inject.js#L616-L628)

**Comment by GaryJones** [comment]
As a quick and dirty hack, you can use Settings -> Custom CSS:

```css
html.dark .column:nth-of-type(1) .column-header {
    background: red;
}
html.dark .column:nth-of-type(2) .column-header {
    background: white;
}
```

![screenshot 2018-07-01 00 38 13](https://user-images.githubusercontent.com/88371/42129787-2ddf4390-7cc7-11e8-82c6-6caacd3a553e.png)

- The colours are applied per current column order. If you re-order, the different colours will stay where they are (red for first, white for second etc.). You'd need to update the `nth-of-type` value as necessary.
- I've only amended the column headers, but different CSS will target the whole column background and text color.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
