### ISSUE TITLE
Favicon "hijacked" when enabling the "Delete t.co redirection"

### ISSUE THREAD

**Issue by skid9000** [eramdam/BetterTweetDeck#440]
Hello,

I have noticed (and @Luclu7 too) a weird thing with the favicon in TD, which was the Pixiv one instead of the TD for some reason...

So i investigated and it seems like it's when you use the option to delete the t.co redirection that for some reason, when a pixiv link is loaded somewhere it use it's favicon 🤔
Also the pixiv icon is loaded after the TD one. 
![image](https://user-images.githubusercontent.com/26208369/64986394-36250c80-d8c7-11e9-8f65-8480f5e1df95.png)

When you disable the option, it keeps the TD icon.

**Comment by eramdam** [comment]
I have a merged a PR that fixes this. It’s not live yet but it probably be later this week https://github.com/eramdam/BetterTweetDeck/pull/439
