### ISSUE TITLE
Keyboard shortcut to toggle column collapse

### ISSUE THREAD

**Issue by Scrxtchy** [eramdam/BetterTweetDeck#443]
How do you feel about adding to the keyboard shortcuts within tweetdeck?
Being able to toggle this will add to the feasibility of keyboard actions while columns are collapsed

**Comment by eramdam** [comment]
I'm looking into it and it looks like TweetDeck doesn't actually keep track of whatever column is focused at a given time, and I feel like requiring a tweet to be focused would defeat the purpose of that keyboard shortcut 😕 

I'm closing for now, if I can think of something I'll re-open and work on it.
