### ISSUE TITLE
Add emoji and gif icons within 'reply' or 'retweet shortcuts

### ISSUE THREAD

**Issue by josesa** [eramdam/BetterTweetDeck#444]
Related with   #386  ([Enhancement] Add emoji and gif icons within 'reply' or 'retweet)

Maybe something got broken along the way but the gifs/emoji buttons is not available in quick reply window.

There are  workarounds:
 - For emojis, using :shortcodes:
 - For gifs and emojis, click the Popout button which access the full compose screen.

But for consistency I suggest to be added directly for faster integration.

**Comment by llrs** [comment]
Agreed, came here to ask that! Hope it won't be too much work. Many thanks for all the other amazing features it provides already.

**Comment by eramdam** [comment]
Fixed in the recent 4.6.2
