### ISSUE TITLE
Possible to add a 'Copy Link to this Tweet' as a Tweet Action?

### ISSUE THREAD

**Issue by wcawcawcawca** [eramdam/BetterTweetDeck#446]
hey,

so i link to tweets a lot and share them out given my company's workflow. i can't just retweet. therefore, i was hoping it'd be possible to add 'Copy Link to this Tweet' as an option to the Tweet Actions.

thanks!

**Comment by eramdam** [comment]
There’s already an item for that in the tweet menu (three dots) and you can copy the link on the time stamp of a tweet.

**Comment by wcawcawcawca** [comment]
thanks for the response.

yes, i know it is in the tweet menu. but i was curious if it'd be possible to have the ability to make it one of the icons that appears on hover. like, ultimately, would it be possible to customize which tweet actions appear on hover. there are the three options, so would it be possible to have a fourth, fifth, etc.

and if not, would it be possible to have it so that when you click a tweet, and it 'comes into focus' for lack of a better way of phrasing it, could there be a keyboard shortcut to copy the link to that tweet?

**Comment by wcawcawcawca** [comment]
thanks! i know it seems silly given it's one click versus two, but speed is pretty vital for our use case. basically, i'm reposting tweets to our slack, which we then use for our purposes. we created a plugin that allowed us to RT tweets from each of our accounts into the slack, but there was a significant delay.

so yea. basically i'm just looking to copy a tweet's link to the slack as fast as humanly possible, and putting it in that hover would be a godsend. i understand if you feel it's not worth it given this is so edge-case, but i can't tell you how highly appreciated it'd be.

thanks for considering.
