### ISSUE TITLE
Unable to view tick box checks in settings

### ISSUE THREAD

**Issue by rubin110** [eramdam/BetterTweetDeck#45]
![20151026092714-selection](https://cloud.githubusercontent.com/assets/222551/10735149/cf9fbce4-7bc3-11e5-86e2-024d6941cedc.png)

When viewing settings for BetterTweetDeck, I can't see which boxes of ticked and which ones I haven't. They are clickable but don't show a tick after clicking.

Running BetterTweetDeck 2.1.4, Chrome Unstable 48.0.2541.0 dev (64-bit), on Debian Sid.

**Comment by eramdam** [comment]
Any error in the console when on this page? Is it happening on stable as well?

**Comment by rubin110** [comment]
Works fine on stable.

The only error I saw was...

Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAYAAACprHcmAAAAAXNSR…PGcbYLzh91vdkXSHDDBk+0gxussS3rNcMCs+D6E18/9gLPPhbDshfzLgAAAABJRU5ErkJggg==' because it violates the following Content Security Policy directive: "img-src 'self' *".

...which I don't see happen on stable.

**Comment by gravygoat** [comment]
Same issue on Version 48.0.2564.23 beta (64-bit) running on Mac OSX 10.11.1.  Also on Chromebook running ChromeOS version 47.0.2526.74 beta (64-bit).

**Comment by rubin110** [comment]
Fix verified on version 2.1.6, Chrome Version 49.0.2593.0 dev (64-bit).
