### ISSUE TITLE
[Feature Request] Add bookmarked tweets to column

### ISSUE THREAD

**Issue by rmzab** [eramdam/BetterTweetDeck#454]
As a user I would like to add a column of my bookmarked tweets so when I open BetterTweetDeck I can access them easily.
I assume it would be the same setup as adding other columns:
1. Click the + (Add Column)
2. Select Bookmarks
3. The column is added to the current display of columns.

**Comment by eramdam** [comment]
I agree this would be nice but this is all Private Twitter API territory and I can't do that.
