### ISSUE TITLE
Download media and Copy links to media buttons

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#455]
Looks like these pesky things constantly refuse to cooperate in Waterfox (2019.10). Even after latest BTD update this two are still functional only until the browser is closed. Only working if add-on is re-installed, until next browser shutdown. It's a regular default install of latest Waterfox.

**Comment by hotcoldcoffee** [comment]
I've been having the same problem on the current version of Firefox (71.0 64-bit).

**Comment by eramdam** [comment]
> I've been having the same problem on the current version of Firefox (71.0 64-bit).

I'm running Firefox 71 and those buttons work fine so I really don't know what to tell you 😕 

Can y'all try without any other addon enabled? Maybe another addon is conflicting somehow?

**Comment by a21937189** [comment]
> > I've been having the same problem on the current version of Firefox (71.0 64-bit).
> 
> I'm running Firefox 71 and those buttons work fine so I really don't know what to tell you 😕
> 
> Can y'all try without any other addon enabled? Maybe another addon is conflicting somehow?
I had the same problem recently...
And I just found out that some chrome extension such as "flash video downloader" extension will cause this function not working properly, maybe try to disable some extension that is related to media download 😊

**Comment by kasmide** [comment]
In my case(Firefox Developer Edition 77.0b9), setting `security.csp.enable` to `false` in <about:config> could avoid this bug (Though this can cause some security vulnerabilities)

**Comment by eramdam** [comment]
So it seems that 77 broke that specific feature. I have a branch that addresses related things anyway so I'll squeeze a fix for that at the same time.

**Comment by eramdam** [comment]
Closing this as it has been fixed for FF 77.
