### ISSUE TITLE
Hide secondary name if it's the same

### ISSUE THREAD

**Issue by Commenter25** [eramdam/BetterTweetDeck#458]
I like the "@Username Full name" display style, since usually the @ is more identifying while the full name can still be helpful. But, something that's a little annoying with this style is when accounts have both the same. Some great examples are [halflife_txt](https://twitter.com/halflife_txt) and [jacksfilms](https://twitter.com/jacksfilms), who at the moment have their @ and full name _exactly_ the same.

I'm thinking maybe there could be an option to check whether or not both of them match, and just show the primary one selected? It would look far cleaner, and no information would be lost. If you want to make the system reach further, you could also hide the secondary name if the only differences are spaces/underscores, capitalization, and/or a YT at the end. This would make it also affect accounts like [Mate_Desktop](https://twitter.com/Mate_Desktop) and [TechLinkedYT](https://twitter.com/TechLinkedYT).

**Comment by eramdam** [comment]
After thinking about it, I'd rather not do this, the usernames formatting code is already very convoluted and this would make it even more complicated. Sorry 😅
