### ISSUE TITLE
Download specific media

### ISSUE THREAD

**Issue by lc-guy** [eramdam/BetterTweetDeck#459]
Would be nice to only download the specific pic being previewed when a tweet has multiple pic (leaving the multi-download to clicking on 'download' while in the general feed). Currently, there's no way to download a single pic from a multi-media tweet, apart from trying to guess which download opens first, which is prone to race conditions.

**Comment by eramdam** [comment]
I know it's a bit of a hack in a way but in the meantime you could use the "copy links to media" button and go from there?

I'll look into doing something like this for the next major version for there are a few things to figure out to do this properly so it will take time.

**Comment by lc-guy** [comment]
Given this was on the 4.0 milestone, was anything done for this issue?

**Comment by eramdam** [comment]
Unfortunately not. I'm still not sure how the UI for this would even work.

**Comment by lc-guy** [comment]
![image](https://user-images.githubusercontent.com/5222114/113606619-8ea63100-9648-11eb-8a5c-2f1803aedd67.png)

How about putting the button either in the bottom bar on a zoomed-in media, or somewhere in the extra options dropdown? This one would only download the displayed media, while the button in the general timeline would download them all (as it does now already).
