### ISSUE TITLE
Line break in smaller icons mode.

### ISSUE THREAD

**Issue by TopoR** [eramdam/BetterTweetDeck#46]
Hi! I've noticed, that when you use smaller icons in the compose panel, it's adds two line breaks (covering last two buttons in "div" blocks). Is this plugin issue?

![2015-12-13_13-30-36](https://cloud.githubusercontent.com/assets/4129779/11766561/e44c7942-a19e-11e5-8dfa-1ea721afc964.jpg)

![2015-12-13_13-30-47](https://cloud.githubusercontent.com/assets/4129779/11766562/e6d1fd36-a19e-11e5-82a8-fba5c50525f7.jpg)

**Comment by eramdam** [comment]
Hum, yeah, something changed in the Tweetdeck's code recently. You can untick the "smaller icon in composer" option as a quick fix.
