### ISSUE TITLE
What are all these domain permissions for?

### ISSUE THREAD

**Issue by tbodt** [eramdam/BetterTweetDeck#461]
I just went to install the extension and got this popup:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/5678977/73117174-6e340000-3ef6-11ea-9a6d-b9e38c443e61.png">
That's a lot of domains, and apparently there's 22 more that I can't see. Are they really all necessary?

**Comment by eramdam** [comment]
Those are all the domains necessary to display the thumbnails from the various sites supported. They are all listed in https://github.com/eramdam/BetterTweetDeck/blob/master/tools/manifests/commonHosts.js

So yes, I know it's annoying but yes they are necessary. I don't want to just put the domain to a random proxy that I:
- would need to maintain
- would need to host
- would be even more opaque and weird for users

🤷‍♂
