### ISSUE TITLE
[Featrue request] Add option to hide timestamp completely 

### ISSUE THREAD

**Issue by Valdaria** [eramdam/BetterTweetDeck#464]
In a process to be not time dependent, i try to avoid having the time and date displayed.
So it would be nice if I can have an options to hide timestamp from tweets

**Comment by eramdam** [comment]
It's a bit of a hack but you can do that by specifying a custom time format that's just a space 😁 
![image](https://user-images.githubusercontent.com/1409924/73613025-515a9500-45a6-11ea-8736-878b4690edc0.png)
![image](https://user-images.githubusercontent.com/1409924/73613030-61727480-45a6-11ea-8b57-202a0276d23c.png)

A cleaner way to do this would be to just use this in the `Custom CSS` field
```css
.tweet-timestamp.js-timestamp {
    display: none !important;
}
```

**Comment by Valdaria** [comment]
Thank you
