### ISSUE TITLE
Fleets Support

### ISSUE THREAD

**Issue by NiciusB** [eramdam/BetterTweetDeck#465]
Hi! Today Twitter announced Fleets (Twitter's take on Stories). See: https://techcrunch.com/2020/03/04/twitter-starts-testing-its-own-version-of-stories-called-fleets-which-disappear-after-24-hours/

Knowing how they treat tweetdeck, it'll probably take a very long time to get any kind of support on tweetdeck. In case the API for them becomes available, I wonder if BetterTweetDeck could add Fleets (maybe as a column type?) by itself.

Just thinking out loud, tho, since I don't know anything about the limitations and codebase

**Comment by eramdam** [comment]
Not really.

Like every new feature, Twitter's Fleets are probably going to be available only through a private API. While it may not be impossible to reverse engineer (I almost did that for picture captioning), I got it from good sources that if I started using private APIs in BetterTweetDeck, I'd be in some troubles with Twitter, so I'd rather not attempt it 😅
