### ISSUE TITLE
[Request] Add settings import/export

### ISSUE THREAD

**Issue by JaxxArmstrong** [eramdam/BetterTweetDeck#467]
I wouldn't mind a simple way to import/export the specific Tweetdeck settings including the custom CSS, please.

**Comment by Athanasius** [comment]
Seconded.  I found 'Debug Info' to at least copy/paste a record of my settings, but that leaves no easy way to just set them in another browser.

Presumably I could in theory find where Firefox stores the settings on Linux and it would be a JSON file I could copy into ?

**Comment by eramdam** [comment]
That's something I want to include in the next major version but I'll see if I can throw something together for BTD 3.x also.

**Comment by eramdam** [comment]
It's in v4 that just came out!
