### ISSUE TITLE
[Feature Request] Being able to increase the width/height of the compose area

### ISSUE THREAD

**Issue by soheiil** [eramdam/BetterTweetDeck#469]
Hi,

If it is possible would be great to have an option to increase the width/height of the compose area; similar to the "Apply a custom width for columns" in the interface section of the settings.

Thanks.

**Comment by droidgoo** [comment]
you can change the width at least by installing another extension that gives you greater control over the column widths and heights... look for multi-row on the firefox add-on page

both extensions seem to play well together so far (2 days of real world testing).
