### ISSUE TITLE
Option to add "clear" button in column headers

### ISSUE THREAD

**Issue by Maijin** [eramdam/BetterTweetDeck#470]
Possibility to add the clear button on column header would be really handy instead of having to click on settings then clear.

**Comment by eramdam** [comment]
You mean like this?
<img width="1017" alt="Screen Shot 2020-05-02 at 8 59 21 AM" src="https://user-images.githubusercontent.com/1409924/80869102-3d7d0880-8c53-11ea-84b5-35333824efa2.png">
<img width="345" alt="Screen Shot 2020-05-02 at 8 59 45 AM" src="https://user-images.githubusercontent.com/1409924/80869115-479f0700-8c53-11ea-8ab5-aa36556a7fca.png">

**Comment by Maijin** [comment]
Awesome guess I missed it :S
