### ISSUE TITLE
Keyboard navigation ceases to function.

### ISSUE THREAD

**Issue by Athanasius** [eramdam/BetterTweetDeck#472]
Unfortunately I've no idea if this is specifically a BTD issue, or also present in base TD, as I'd not want to use BTD-less TD for long enough to trigger it.

I often use the cursor keys/F/T etc shortcuts whilst reading twitter in BTD.  Sometimes this completely stops working.  No amount of clicking in a tweet, going into one, using the mouse to perform operations etc enables it again.  A reload of the tab always brings it back.

It just happened again and the only things in the Firefox (latest stable) console for that tab are:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
Storage access automatically granted for tracker “moz-extension://3fadbee3-009d-4207-a237-c6174b84f86e” on “https://tweetdeck.twitter.com”.```

I'm somewhat technically savvy, so any points on things to look at in the FF web developer stuff to see if I can track down what's happening ?

**Comment by eramdam** [comment]
I do notice that sometimes... Not sure what's up with that. I'll see if it happens on the v4 branch.

**Comment by eramdam** [comment]
I switched back to Firefox as my main browser. I will see if it happens again.

**Comment by eramdam** [comment]
Haven't seen this happen and even if it did I don't think I could do much about it.
