### ISSUE TITLE
[ Feature Request ] Bookmarks column

### ISSUE THREAD

**Issue by rosskdavis** [eramdam/BetterTweetDeck#474]
Cannot find a way to add a Bookmarks column. Perhaps you could add that please. Thank you for a great product.

**Comment by eramdam** [comment]
Bookmarks are a private API from Twitter that I can't implement because it's not documented 😞 
Sorry.

**Comment by rosskdavis** [comment]
Thanks for replying Damien. As a by the way, I once tweeted you for a way
to regex out GIF posts and couldn't find a way for months. I had a
brainwave to use uBlock Origin and this
filter in my filter settings in case anyone else wants to filter posts.

https://github.com/gorhill/uBlock
tweetdeck.twitter.com##.js-show-detail.item-box.js-stream-item-content:has(.js-media-gif-container)


Ar Luan 11 Beal 2020 ag 22:27, scríobh Damien Erambert <
notifications@github.com>:
