### ISSUE TITLE
[feature request] addition of a "Remove" button to each column

### ISSUE THREAD

**Issue by droidgoo** [eramdam/BetterTweetDeck#482]
When looking into a trending hashtag (by clicking on it), a new column opens up directly after the Trending column which displaces other columns in the layout.

When finished with the hashtag, getting back the original layout requires you to "Remove" the column, but the Remove button is buried in the settings drop down, just like the "Clear" button.

Neither of these buttons should be buried, they should both be in the header as their Use Case is completely different that the other items in there.

Short of a dedicated button, a hotkey would be just as helpful (Alt-C or something).

thx

**Comment by eramdam** [comment]
It's in v4 that just came out!
