### ISSUE TITLE
[feature request] Tweet content filter "show images" to exclude gifs 

### ISSUE THREAD

**Issue by n-a-a** [eramdam/BetterTweetDeck#485]
![image](https://user-images.githubusercontent.com/66688115/84168480-5c9b6100-aa6f-11ea-961e-8afc7cdaeb19.png)
Gifs still show up in Images filter even though there is a seperate filter for Gifs - Image filter should contain still images only
An option to select several filters at the same time would also be useful.

**Comment by eramdam** [comment]
That's something on TweetDeck's backend so I can't really do much on my side unfortunately.
