### ISSUE TITLE
Add option to display like dialog when liking a tweet

### ISSUE THREAD

**Issue by casperOne** [eramdam/BetterTweetDeck#486]
Currently, I do a lot of liking of tweets from accounts that are not related to account that is associated with the column it appears in.

To do that, I have to open the menu for the tweet, and select "Like this tweet from accounts".

I see this as a disparity, as when RT *any* tweet, it brings up a dialog to select an account to RT from.

It would be great if this behavior was aligned.

Because it is already baked in behavior for a lot of people, I suggest that it goes behind a feature flag in settings (although if you wanted to make this suggested behavior the default, I wouldn't complain 😀)

Thanks for the work that's been done and thanks in advance.

**Comment by eramdam** [comment]
It's in v4 that just came out!
