### ISSUE TITLE
[Feature Request] Media Display

### ISSUE THREAD

**Issue by kuroshibolt** [eramdam/BetterTweetDeck#488]
Hi,

I would like to know if there is a way to change the media display to something like Twitter's one.

![A](https://user-images.githubusercontent.com/66945856/84643060-b4a0f000-aed3-11ea-99c4-123aec290744.PNG)

![B](https://user-images.githubusercontent.com/66945856/84643065-b66ab380-aed3-11ea-8e50-42f3b73e9f62.PNG)

Thank you for the hard work!

**Comment by eramdam** [comment]
Not right now but I'm considering getting rid of the tweet in the fullscreen preview entirely in a future version 🤔

**Comment by eramdam** [comment]
So I ended up looking into this, and I can't figure out how Twitter computes the color for the background, and I'm pretty sure they do some server-side logic so reverse engineering this would take a lot of work for a very small result 😓

**Comment by eramdam** [comment]
Re-opening as I managed to implement this by pulling Twitter's color data and reverse-engineering how the Twitter Web client chooses the right color for a given image. It will be in BTD v4.

**Comment by eramdam** [comment]
It's in v4 that just came out!
