### ISSUE TITLE
[feature request] add access to twitter bookmarks

### ISSUE THREAD

**Issue by droidgoo** [eramdam/BetterTweetDeck#490]
there are options to add several items to the extended menu under the (...) like "add to collections"

but there is no "add to bookmarks" so we can have access to twitter bookmark feature from tweetdeck.

**Comment by eramdam** [comment]
Bookmarks are one of the features that Twitter gates behind their private API so I can't implement that on my side without getting in trouble with Twitter, unfortunately.

**Comment by droidgoo** [comment]
we have access to some thing called "collections" and i don't even know
what those are... it's unfortunate that twitter treats developers this way.
