### ISSUE TITLE
Ability to mute "replying to" messages addressed to a specific user. 

### ISSUE THREAD

**Issue by Maijin** [eramdam/BetterTweetDeck#491]
Ability to mute "replying to" messages addressed to a specific user. 

I've tried muting the user, muting the quotes and muting the retweet but I keep getting the replying to messages in the feed.

**Comment by eramdam** [comment]
I'm not sure I understand what you mean by "replying to" messages? Muting the user shouldn't definitely mute any mentions they might send to you 🤔

**Comment by Maijin** [comment]
Thanks for answering @eramdam, here is a concrete example:

I have a specific search column for `fireeye OR $FEYE`

Despite having muted everything from the user @LV_FireEye which has nothing to do with this company. The feed still contain  "replying to @LV_FireEye" messages from other users:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1408600/86440349-9841e780-bd0a-11ea-8041-ee8c64cf6fb6.png">

**Comment by pixeldesu** [comment]
It should be enough to mute the phrase "@LV_FireEye", all mentions should disappear then.

Replying to is just a visual sham for the list of users mentioned in the beginning of the tweet.

**Comment by Maijin** [comment]
Aha that worked @pixeldesu 👍, I didn't thought about this one. I was trying with the `excluding` but it didn't work. 

Then maybe as a different/alternative suggestion for this issue, what about adding a suggested "mute @LV_FireEye" as a suggestion. Similar to how better tweetdeck suggested muting hashtag when it detects it?

**Comment by pixeldesu** [comment]
Not sure if that's possible really, especially since we can have multiple mentions.

Would we then show:
* Mute mentions to all users in this conversation (awfully long text already)
* Mute @\x, Mute @\y, ...

Both options are not really preferable, I'd say.

**Comment by Maijin** [comment]
Right then not sure what's the best solution here, maybe having it as an additional option when you open the profile? 

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1408600/86452929-4eaec800-bd1d-11ea-8d35-41302cd15dd6.png">

**Comment by Maijin** [comment]
Got another one here where muting the user via the settings doesn't work. I have a the following query:

fin7 OR Carbanak OR Anunak OR "Carbon Spider"

The query is hitting on https://twitter.com/azureggukie, I've tried mutting the reply to to this user using mute on: @ azureggukie, azureggukie, fin⁷. 


But so far no success.
