### ISSUE TITLE
Cannot open extension options for BetterTweetDeck

### ISSUE THREAD

**Issue by silversurfer60** [eramdam/BetterTweetDeck#492]
Since the last update, I can no longer open the extension options in Opera.  I can click on the link but nothing happens and I have no pop-up blocker in use.  I want to alter some settings and I can't.

**Comment by eramdam** [comment]
I can open the settings just fine on the latest version of Opera and Better TweetDeck. 

Please make sure you're up-to-date 🙇‍♂️

**Comment by silversurfer60** [comment]
Hi, I don' know what the problem was then?  It was only after you last updated Better Tweetdeck but I can get into them now.  I didn't have a problem using Chrome, it was probably Opera, they've been a lot of things lately after their last update, sometimes they are blocking certain domains that will open correctly in chrome.  Thanks anyway.
