### ISSUE TITLE
Emoji detection logic should not detect ASCII smilies as shortcodes

### ISSUE THREAD

**Issue by jaxidian** [eramdam/BetterTweetDeck#494]
Hi. Thanks for all of your hard work and this awesome tool!! :-)

The Emoji shortcode detection logic will detect ASCII smilies as emoji shortcodes. A couple examples are :-P and :-D

This is generally not too bad, but when paired with some other functionality, it results in an awkward experience when I try to type and send the following Tweet by hitting CTRL+Enter to send it:

> I'm making a funny comment. :-P

I think my request would be to either a blacklist of ASCII smilies to be checked against that would prevent the emoji window/logic from being engaged, or for the CTRL+Enter sequence to still send the tweet with my ASCII smilie rather than replacing my ASCII smilie with the emoji.

This request is a naive request, and there certainly might be some negative consequences to this request. Just putting this out there from a user perspective to describe the problem I'm actually running into.

Side note: It doesn't seem like this was a problem for me before ~1 month ago. I've been using BTD daily for years and it seems like something changed somewhat recently. I'm told this code hasn't changed in ages, so I wonder if something changed in Windows or Edge (chromium) that has added a new dynamic to my specific situation.

https://twitter.com/BetterTDeck/status/1291747126939013120

**Comment by eramdam** [comment]
Should be fixed in v4 that just came out!
