### ISSUE TITLE
"Spoiler mode" to hide all tweets' text

### ISSUE THREAD

**Issue by Thex-PiedDroit** [eramdam/BetterTweetDeck#496]
Hi there!

I'd like to request a feature that would work like the following:
- All the text in every tweet is hidden with black (color and background-color of the text is set to black), so that the only things visible are pictures and videos.
- Hovering the text with your cursor reveals it. Removing your cursor from the text hides it back.
- You can add users to a list of "trusted users" from whom the tweets will not be affected.

The idea behind this is to provide an easy way to reduce information overload and to not be bombarded all the time with all the negativity that news can carry, while still being able to enjoy art and stuff.

I hope this sounds appealing to you and not too difficult to make.

Have a beautiful day!

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
