### ISSUE TITLE
[Feature Request] Automatic Dark Mode

### ISSUE THREAD

**Issue by boop5** [eramdam/BetterTweetDeck#497]
Add a setting to enable automatic darkmode. That means that ie from 6am to 8pm daylight theme will be used and from 8pm to 6am dark mode will be used. 

Should I really add more explanations?

**Comment by ai** [comment]
The best option is to use [`prefers-color-scheme`](https://web.dev/prefers-color-scheme/) media query (which use OS dark/light theme):

```js
  window.matchMedia('(prefers-color-scheme: dark)').addListener((e) => {
    if (e.matches) {
      enableDarkTheme()
    } else {
      disableDarkTheme()
    }
  })
```

@eramdam I can try to make a pull request if you will tell me where it will be the best place to keep that trigger above

**Comment by eramdam** [comment]
@ai i actually have this implemented for v4 which will come Soon ™️

**Comment by boop5** [comment]
nice. then this ticket can be closed. thanks

**Comment by eramdam** [comment]
It's in v4 that just came out!
