### ISSUE TITLE
Better TweeDeck as User script

### ISSUE THREAD

**Issue by qorg11** [eramdam/BetterTweetDeck#498]
I use the Palemoon browser (and Better TweetDeck is not available for palemoon). But Palemoon can run any kind of user script with Greasemonkey (for example)

Is/Will be BetterTweetDeck  available as user script?

**Comment by eramdam** [comment]
It's not available as an user script and I don't think it ever will, the code of BTD is way too complex in the way it's laid out to fit in a single file and be usable IMO.

Is there any way to develop add-ons for Palemoon? Their website wasn't very useful when I tried looking for that information..

**Comment by qorg11** [comment]
Well, only way to develop add-ons for palemoon is to develop an addon for firefox 28 i guess

**Comment by eramdam** [comment]
Ah 😬 Yeah I'm not doing that... the whole reason I waited for Firefox Quantum was because of the support for WebExtensions so I didn't have to maintain two codebases 😅
