### ISSUE TITLE
Mute Retweets of tweets done by the same account

### ISSUE THREAD

**Issue by Fen1331** [eramdam/BetterTweetDeck#499]
So not an issue nor a bug, but would be very interested in a way to mute retweets from a person, but only their retweets of their previous tweets. 

basically person A tweets out tweet 1, 2, 3, then next day retweets their own tweets 1, 2, 3 and does this repeatedly, but also retweets others tweets which are useful/helpful info. so muting all their retweets isnt helpful, but muting only when they retweet their own personal tweets from their own account would be super helpful.

100% understand if this is not possible. have tried the googles, the searches, and all the things with nothing that works for this specific problem (and its not just 1 account that does this).

**Comment by eramdam** [comment]
@pixeldesu I feel like that's something that could be added in the AME part of BTD, right?

**Comment by pixeldesu** [comment]
Yeah, should be pretty easy to add a check for the user of a tweet (the retweet) and the retweet entity user matching.

**Comment by Fentist1x** [comment]
thank you for looking into it. appreciate it

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
