### ISSUE TITLE
[Feature Request] Back button in dialogs for tweet actions

### ISSUE THREAD

**Issue by TheOpponent** [eramdam/BetterTweetDeck#501]
When going through tweets in an dialog displayed as an Add a user column window (such as viewing a user's tweets or likes), opening another dialog through a tweet menu to do something like add a tweet to a collection closes that dialog. This is not ideal when going far down a list of tweets or replies, and especially if a user intends to do this more than once and doesn't want to add another column just for this task, as it causes them to lose their place. Is it is possible to add a back button for dialogs opened from another dialog, or to keep multiple dialogs open so higher level ones aren't lost?

**Comment by eramdam** [comment]
Unfortunately that would require keeping quite a lot of internal TweetDeck state, most of which are essentially contained in a blackbox 😕 

I can't promise I could implement such a thing, and given that this is one of a very few reports I've had about this over the course of 7 years, I'll assume it's a small edge-case. Sorry!
