### ISSUE TITLE
"Download file name format" not working correctly

### ISSUE THREAD

**Issue by hotcoldcoffee** [eramdam/BetterTweetDeck#505]
I noticed after updating Firefox, the custom file name format I had set for the "Download file name format" option has been ignored when I use the download all media button, instead just using the base filename. I have tried reinstalling the add-on and clearing my cookies, but the problem still perists. I suspect something may have changed with Firefox or Windows?

I am currently using Firefox 81.0.

**Comment by lc-guy** [comment]
Getting this issue too, latest Arch Linux.

**Comment by newzorensia** [comment]
noticed this problem too
Windows 10 at Firefox version 81.0 
Better Tweetdeck 3.9.16

**Comment by eramdam** [comment]
I was about to release a workaround but apparently Firefox 82 doesn't have the issue anymore because i just upgraded and it works fine now. Can you folks check?

**Comment by lc-guy** [comment]
yup, fixed for me

**Comment by newzorensia** [comment]
Thanks now it work as usual
