### ISSUE TITLE
Pause column scrolling on hover makes columns wobbly

### ISSUE THREAD

**Issue by DikUl** [eramdam/BetterTweetDeck#510]
If you enable "Pause column scrolling on hover" option columns start to jump by a few pixels on hover.

Sample: https://youtu.be/ap7beQsdVRc

**Comment by eramdam** [comment]
Unfortunately, that's how the feature works. TweetDeck interrupts auto-scroll on new tweets whenever you scroll so we shift the scroll by a few pixels on hover 😅

**Comment by DikUl** [comment]
Wow genius! O_O
