### ISSUE TITLE
[Feature Request] Block/Hide Tweets based on Source Labels

### ISSUE THREAD

**Issue by unbekannt3DE** [eramdam/BetterTweetDeck#512]
It would be nice to have an option in BTD for muting or hiding Tweets based on the source labels it comes from. For example i follow @xdadevelopers but hate their stupid Huawei ad tweets which are always created through "Twitter for Advertisers" other than their normal news tweets which comes from "Buffer".

**Comment by eramdam** [comment]
It's already a feature of TweetDeck. Create a mute with `Tweet Source` as the type 
![image](https://user-images.githubusercontent.com/1409924/102274717-2c7ac200-3ed9-11eb-887b-1c39c9f7d4ae.png)
