### ISSUE TITLE
[Feature Request] Link previews in timeline with selected sources

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#515]
Hello. I was wondering if it could be a good idea to add to the timeline...
![Tweetdeck_SteamReleasesTweets](https://user-images.githubusercontent.com/1467366/103712201-79722580-4fb9-11eb-9cd8-6357fea5bd92.png)

...The link previews from when you open a tweet:
![Tweetdeck_SteamReleasesTweetPreview](https://user-images.githubusercontent.com/1467366/103712207-7c6d1600-4fb9-11eb-9371-79f220cd152e.png)

As like when it previews images or other medias, but with links. And you click in the preview and it opens the link in a new tab.

However, I'm aware this could bring some issues, for example, it can add a lot of more elements to the timeline, making every tweet with extra height. Maybe can be an option to add domains allowed to have previews, to make only the desire ones to have them, and also something to control what to do if there is more than one link in a tweet (Show all stacked, only the last one, anyone...).

In my case, i am interested in the Steam ones (to look the name and banner image from a game), but a lot of other sites can be good with this behaviour.

Thanks.

**Comment by eramdam** [comment]
It's in v4 that just came out! (as a global setting)
