### ISSUE TITLE
Allow muting by regex on the tweet author, not just the content

### ISSUE THREAD

**Issue by d4rky-pl** [eramdam/BetterTweetDeck#516]
Very often low quality tweet / troll accounts are doing the least amount of work possible when creating an account so they end up with accounts that look like [Some common name][Bunch of numbers], for ex. `Marlena09775026`, `Miriamm20516627`, `Przemek60474612` etc.

It would be amazing if there was an option to filter out all this noise so browsing replies to a popular tweets feels less like going for a swim in a sewage tank.

**Comment by eramdam** [comment]
@pixeldesu that sounds like what you wanted to do, wasn't it? 😛

**Comment by pixeldesu** [comment]
Exactly what I mentioned a few days ago! If I get the okay, I'll work on a filter for regex muting on usernames! (which could be useful not just for `\/w/d{6,}\` but also some other patterns of usernames 👀

**Comment by eramdam** [comment]
Forgot to close this when releasing 4.1.0.
