### ISSUE TITLE
Select language for tweets translations

### ISSUE THREAD

**Issue by Qeenon** [eramdam/BetterTweetDeck#517]

**Comment by kongbaiye** [comment]
wait for fix it.

**Comment by eramdam** [comment]
How would you imagine that feature to work in practice? Like, choose a language for translation on a per-tweet basis or a global settings to translate tweets into a language that's not the language of your account?

**Comment by Qeenon** [comment]
global setting, @eramdam I'm not sure what's "language of account" I haven't found that in settings
actually I prefer English interface but need to translate all to Russian...

**Comment by eramdam** [comment]
After digging into TweetDeck's JS code, it seems like it uses the browser's language to figure out what language to translate to.

I'll try to figure something to configure that in BTD for v4 that should come later this year.

**Comment by Qeenon** [comment]
@eramdam "browser's language" that's very weird design choice but at least now I understand how to control it...
