### ISSUE TITLE
Remove handle from self-replies

### ISSUE THREAD

**Issue by tamasys** [eramdam/BetterTweetDeck#52]
Most Twitter clients don't autoinclude your own handle when you reply to yourself. This would be a nice time-saver.

**Comment by eramdam** [comment]
Huuum, like, you mean remove it from the composer when replying?

**Comment by tamasys** [comment]
Yeah! Like in this screenshot of me replying to myself, it's included my handle. Which isn't necessary, as it's a continued reply to someone else.
![Twitter reply to self](http://i.imgur.com/UxFshOD.png)

**Comment by eramdam** [comment]
Makes total sense, I will add it to the v3 milestone but I will handle it once v3 will be feature compete with v2.

**Comment by eramdam** [comment]
@tamasys I've been noticing TD somehow made this a feature officially, so I guess I don't need to implement that anymore.
