### ISSUE TITLE
Safari 14 feedback

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#520]
## Finally!

I finally managed to make a Safari 14 build of Better TweetDeck, and I need feedback.

## Wanna help me test it? 

Cool! Then follow the instructions:

1. Be on macOS 10.14 or above **and** use Safari 14 or above.
1. [Download the app](https://github.com/eramdam/BetterTweetDeck/files/5825384/btd-safari.zip)
2. Move it to the /Applications folder
3. Open the app at least once and quit it
4. Open Safari
5. Safari > Preferences > Extensions and make sure it is enabled [see screenshot](https://user-images.githubusercontent.com/1409924/104828556-872c7400-581f-11eb-8077-5235f2f13d09.png)
6. Go on https://tweetdeck.twitter.com, click the toolbar icon that the extension and allow it to run **at least** on the current site ("Allow to run on all websites" is necessary for thumbnails to work at all), [see screenshot](https://user-images.githubusercontent.com/1409924/104828571-b6db7c00-581f-11eb-8b52-33da7e14e1e2.png)
7. You're done! 

Known issues:
- Some small CSS glitches (I'd need to double-check if it's TD's fault or mine 😬)
- The "Share on TweetDeck" contextual menu item seems to be limited by the host permissions, I need to figure out what to do with it
  - Either disable it on Safari completely (not great)
  - Allow Better TweetDeck to run on all websites (worse because Safari displays a big warning and I don't want to seem fishy 😅 )

If you run into any issues please make sure of the following:

- The extension is properly enabled/authorized to run on TweetDeck
- Make sure any adblocker is not active on TweetDeck (I've had issues with Clean Links specifically)
- Try to disable the extension to see if the issue still happens, if it does, then it's a vanilla TweetDeck bug

**Please** keep any Safari 14 specific issue confined in this thread while the testing is in progress.

**Comment by dertuxmalwieder** [comment]
Testing on Big Sur with 1Blocker. Seems to work fine yet. :-)

**Comment by eramdam** [comment]
Alright, closing this as I'll submit it for review on the App Store soon.
