### ISSUE TITLE
YouTube embedded preview opens at 144p?

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#521]
Clicking on YT thumbnail previously opened 480p (I think) video embedded but at some point recently it started opening the smallest window imaginable, making the preview feature pretty much unusable. I don't know if it's a bug or done on purpose. 
Can it be selectable value or at least 480p?
BTD on latest Waterfox

![](https://i.imgur.com/isxiK3K.png)

**Comment by eramdam** [comment]
It's definitely not on purpose, I can assure you 😓 
It looks loke NoEmbed started reporting very small sizes for YouTube videos.. I'll try to look at it.

https://noembed.com/embed?callback=%3Cesi%3Ainclude%20src%3D%22%2Fesi%2Fjsonp-callback%22%2F%3E&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DbDOYN-6gdRE

```
{
  "thumbnail_height": 360,
  "height": 150,
  "version": "1.0",
  "html": "<iframe width=\"200\" height=\"150\" src=\"https://www.youtube.com/embed/bDOYN-6gdRE?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>",
  "title": "dragons. geese. Michael Vick. (ft. T-Pain) // Auto-Tune the News #8",
  "url": "http://www.youtube.com/watch?v=bDOYN-6gdRE",
  "provider_name": "YouTube",
  "provider_url": "https://www.youtube.com/",
  "width": 200,
  "type": "video",
  "author_url": "https://www.youtube.com/c/songify",
  "author_name": "schmoyoho",
  "thumbnail_width": 480,
  "thumbnail_url": "https://i.ytimg.com/vi/bDOYN-6gdRE/hqdefault.jpg"
}
```

**Comment by eramdam** [comment]
Alright, I have a fix on master, it will be in the next release, I will try to release it by the end of the week.

**Comment by plissken1138** [comment]
> 
> 
> Alright, I have a fix on master, it will be in the next release, I will try to release it by the end of the week.

king!
