### ISSUE TITLE
Is it possible to fix this original tweetdeck feature

### ISSUE THREAD

**Issue by Taemaly** [eramdam/BetterTweetDeck#524]
I was wondering if this is possible to fix (or is it something I am not doing right). In the search tips on the tweetdeck it says, if you make a custom column in the content filter you can filter tweets that contain 2 separate words like these:
"love OR hate | containing either "love" or "hate" (or both)"  .However when i use two filter words with OR in the middle , no twitter results are given. However if I use only one of these words , tweeter results are given and the filter works. So is it at all possible to fix it so that double word filter actually displays results correctly?

**Comment by eramdam** [comment]
Unfortunately not, whatever search issue you're describing probably happens on TweetDeck's backend and I obviously don't have access to that 😅

**Comment by pixeldesu** [comment]
Late reply, but multi-word filters work like this:

```
one word OR two words
// filters for "one", "word" or "two" and "words"

"one word" OR "two words"
// filters for "one word" or "two words"
```

so, wrapping multiple words in `"` makes OR filters work just fine again.
