### ISSUE TITLE
Setting sync overwrites computer specific settings

### ISSUE THREAD

**Issue by supermurs** [eramdam/BetterTweetDeck#526]
Hi,

Is it possible to somehow disable the settings getting synchronized in Microsoft Edge?

In my case I have the column width in Interface settings set at 525px on my home laptop. On my work laptop I have it set at 400px. Now every morning I get the setting from my home laptop sent to my work laptop and vice versa when I leave work.

If it is possible to somehow set the value so that it would not get overwritten, it would be really great.

**Comment by eramdam** [comment]
There's no way to disable it, but iirc Custom CSS isn't being synced (since i can't easily control the amount of data there) so you could use the Custom CSS setting with

```css
.column {
width: 400px !important;
}
```
