### ISSUE TITLE
[Feature Request] Mute follower users in Activity column

### ISSUE THREAD

**Issue by ssss404** [eramdam/BetterTweetDeck#529]
Someone made an extension for this already. Unfortunately it doesn't work anymore and hasn't been updated since 2015.

https://chrome.google.com/webstore/detail/tweetdeck-activity-muter/miaoojdjohgmgkibpkidjcmokjcbanle?hl=en
https://github.com/outime/tweetdeck-activity-muter

"This extension will block certain annoying users from appearing in the Activity column in TweetDeck.

Twitter power users [...] often use TweetDeck and follow a good bunch of people. While we're interested in people's tweets, they may be filling the Activity column with useless content such as nonsense favs [...] or massive follows.

Without this extension, you'd need to either unfollow the person who's executing the actions (follows/favs) or block/mute the receiver of these actions one by one. Since that's way too much work, I made this free extension so you can mute these annoying individuals' activity while still being able to read their tweets."

**Comment by Triplicats** [comment]
At some point the aforementioned extension broke again even though I also would really like this as a feature
