### ISSUE TITLE
"US style" date swaps month and day

### ISSUE THREAD

**Issue by kenners5** [eramdam/BetterTweetDeck#53]
"US Style" date is described in the settings as mm/dd/yyyy (in my American opinion, the docs are correct), but in tweets shows up as dd/mm/yyyy.

![us-style](https://cloud.githubusercontent.com/assets/424898/14584187/c4094db0-03ee-11e6-89fe-544ed60d7c76.PNG)

**Comment by kenners5** [comment]
Another detail -- the month/day are correct on first render, but once I scroll a column up and down, they switch before my eyes...

**Comment by eramdam** [comment]
Hum. I will address this in v3. I'm stopping development on v2 to focus on the big rewrite that is v3. [More details](https://github.com/eramdam/BetterTweetDeck/tree/v3) here.
