### ISSUE TITLE
Require alt text for images option

### ISSUE THREAD

**Issue by ethanwhite** [eramdam/BetterTweetDeck#530]
As discussed in #271 supporting the use of alt text for accessibility is important. While TweetDeck has implemented the ability to add alt text, it is easy for folks to forgot to add it when adding an image. Providing an option in BetterTweetDeck to stop the user from posting before providing alt text would be helpful for preventing this. Browser extensions for doing this exist for twitter.com (e.g., https://addons.mozilla.org/en-GB/firefox/addon/twitter-required-alt-text/) but they do not currently work with TweetDeck.

**Comment by eramdam** [comment]
Added in [4.3.0](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.0)!

**Comment by ethanwhite** [comment]
Thanks!
