### ISSUE TITLE
[Feature Request] Allow quote tweet with media

### ISSUE THREAD

**Issue by eduardomps** [eramdam/BetterTweetDeck#531]
Right now, we can't use the feature of quote-style RT with media attaching, as it wasn't allowed in the official app until sometime in 2020, if I'm not mistaken.
Now that it is allowed, I wonder if BT can add this feature on top of the original client.
We have the option of copy+pasting the link of the original tweet (it is accepted by twitter as if it was a quote) but it would be easier to use it directly.

**Comment by eramdam** [comment]
It's in v4 that just came out! However there's a weird TweetDeck bug and I only do it for quote tweets with videos/images and not GIFs.
