### ISSUE TITLE
[Feature Request] Option for an inverted timeline for columns.

### ISSUE THREAD

**Issue by CyanSlinky** [eramdam/BetterTweetDeck#534]
Would it be possible to add an option to display tweets in a column in reverse order? oldest first and newest last?

I think it makes more sense to read the timeline in this order; when you clear a column and come back, you pick up where you left off with older tweets, and then catch up on the latest tweets as you scroll down.

I wouldn't be surprised if this was not possible but I figured I'd ask since this would be really useful to me.

**Comment by eramdam** [comment]
Unfortunately this would require massive changes in both TweetDeck's internal code and in their own API so I'm fairly certain this is not something I can do as a browser extension 😞

**Comment by CyanSlinky** [comment]
totally understandable, hopefully they'll make some changes in the future that could make this a possibility.
