### ISSUE TITLE
Option to change text size for tweets on a column basis.

### ISSUE THREAD

**Issue by CyanSlinky** [eramdam/BetterTweetDeck#535]
I am currently using a Tampermonkey script to achieve this on a per column basis already so I know it's possible, It'd be nice if it was a part of this extension though.

**Comment by eramdam** [comment]
Are you willing to share the script? Is there any kind of UI for it? This would be the main challenge.

**Comment by CyanSlinky** [comment]
Here's the Tampermonkey script I'm using:

```
// ==UserScript==
// @name         Tweetdeck Changes
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       CyanSlinky
// @match        https://tweetdeck.twitter.com/
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    setTimeout(func1,2000)

    function func1() {
        var x = document.getElementsByClassName("column"); // Get columns
        x[0].style.fontSize = "25px"; // set first column font size to 25 pixels
    }
})();
```

**Comment by eramdam** [comment]
Adding actual UI inside of TweetDeck might be tricky, but you can easily do that with a piece of custom CSS. I added a snippet in the wiki page https://github.com/eramdam/BetterTweetDeck/wiki/Custom-CSS-snippets#font-size-for-a-specific-column
