### ISSUE TITLE
Implementing "Who can reply?" options in v.4?

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#537]
Can "Who can reply?" options be implemented in v.4?

![Reply Options](https://i.imgur.com/y4CoAXu.png)

**Comment by eramdam** [comment]
Unfortunately this is gated at the server level by Twitter/TweetDeck's API so I can't even sneak around and add the necessary parameters to the request 😞 

![image](https://user-images.githubusercontent.com/1409924/114656784-8df24800-9ca3-11eb-904c-b5fe152a61b2.png)

**Comment by plissken1138** [comment]
bummer. thanks for giving it a shot, though.
