### ISSUE TITLE
collapse tweet body of consecutive, identical RT/Like notifications

### ISSUE THREAD

**Issue by zspitzer** [eramdam/BetterTweetDeck#54]
The official clients do nice combining of notifications to be less verbose, in tweetdeck these all take up a lot of space. A simple improvement would be to hide the body of consecutive tweet notifications for the same tweet

XYZ Retweeted
blah blah let's not display this text over and over
ABC Retweeted
DEF Liked
HIJ Liked

**Comment by eramdam** [comment]
So after rewriting BTD for v3, I digged a lot into TD's internal representation and I don't think there is a really satisfying way to do that. Even if I only do it visually, the whole point of that would be kinda lost imo. Will close for now and re-open if I find something,
