### ISSUE TITLE
Scrollbar hide/show on hover

### ISSUE THREAD

**Issue by Stanzilla** [eramdam/BetterTweetDeck#543]
**Is your feature request related to a problem? Please describe.**

I don't want to see scrollbars all the time but I do want to see them occasionally 

**Describe the solution you'd like**

An option to only show the scrollbar on hover and/or when not scrolled to the top

**Comment by eramdam** [comment]
You probably don't want that because hiding the scrollbar will change the width of the columns content. See the video below, I don't think this would be a good experience.

https://user-images.githubusercontent.com/1409924/113539354-7d9ae880-9592-11eb-8f85-31c6cc74a1fb.mov

**Comment by Stanzilla** [comment]
Could you not do them as an overlay? Only change the visibility and not hide/show?

**Comment by eramdam** [comment]
> Could you not do them as an overlay? Only change the visibility and not hide/show?

No, that's not how scrollbars work in browsers, unfortunately.

**Comment by Stanzilla** [comment]
https://www.bennadel.com/blog/3864-copying-slacks-brilliant-virtual-scrollbar-and-overflow-container-in-angular-9-1-12.htm

**Comment by eramdam** [comment]
I'm sorry but I'm not reimplementing a custom scrollbar in a complex app such as TweetDeck just for this 😄
