### ISSUE TITLE
More Options menu appears below neighboring columns

### ISSUE THREAD

**Issue by alefnull** [eramdam/BetterTweetDeck#544]
**Describe the bug**
when clicking on a tweet in a column, then clicking the "more options" action item, the menu popout appears *under* the neighboring column.

**To Reproduce**
1. Open TweetDeck (w/ BetterTweetDeck enabled)
2. Click on a tweet to view its expanded form in the column
3. Click the multi-dotted "more options" action item at the bottom of the tweet

**Expected behavior**
menu popout should appear above all other items.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 87.0

**Screenshot**
![image](https://user-images.githubusercontent.com/1663704/113523719-7c0ff700-9577-11eb-82b8-b5e23774bfda.png)

**Comment by 1stator** [comment]
Same happened to me. To stop it from happening I only have the default tweet actions enabled (reply/retweet/like) whilst I assume they work on a fix.

**Comment by AdamasFR** [comment]
![CleanShot 2021-04-06 at 17 05 49](https://user-images.githubusercontent.com/3597738/113733162-80b0e880-96fa-11eb-97dc-db4412ee01ec.png)

I'm reproducing this on Safari in the latest version, yes.

**Comment by eramdam** [comment]
This is due to the fact that TweetDeck hardcodes the position of the dropdown to be on the left side of the anchor (the button that summons it), i'm not sure it's easily fixable, to be completely honest... I'll have to look into it.

**Comment by AbuMaia** [comment]
I'm not sure if your commit that fixes this does this, but I thought that ensuring that any new icon added by the extension to the bottom of a tweet came after the ellipses icon, making sure it didn't move, would also solve this problem.

**Comment by eramdam** [comment]
> I'm not sure if your commit that fixes this does this, but I thought that ensuring that any new icon added by the extension to the bottom of a tweet came after the ellipses icon, making sure it didn't move, would also solve this problem.

That's a good way to do it yeah. My commit actually fixes a bit of code I've had in the codebase all along to put all the icons on one line

![image](https://user-images.githubusercontent.com/1409924/114323894-305fcf00-9adc-11eb-8388-9331a845c016.png)
