### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by zspitzer** [eramdam/BetterTweetDeck#55]
sometimes when you do a screen grab, it's annoying that you have to save the image to tweet it

It would be great if you could automatically paste an image from the clipboard into a tweet

**Comment by eramdam** [comment]
Huuum. sounds like something TweetDeck would have to do on their side. I will see but it may be very hard for my extension to hookup on TD's code that deeply.

**Comment by mkzero** [comment]
Actually, that _might_ be possible - you can hook into the clipboard(not sure about images though..), then temporarily save that image, which might just be possible with the newer HTML5 file APIs. Finally, just put that image into the image upload for new tweets.

**Comment by eramdam** [comment]
@mkzero yup. I think I will try to experiment on that when I'll be done porting BTD to Edge.

**Comment by eramdam** [comment]
Fixed by https://github.com/eramdam/BetterTweetDeck/pull/112 🎉

**Comment by Neurotoxin001** [comment]
I think we need this feature for videos too. Even default twitter can do it (.mp4 files can be copy-pasted).
