### ISSUE TITLE
BetterTW is loading link previews on columns that have "Media hidden" set

### ISSUE THREAD

**Issue by xPaw** [eramdam/BetterTweetDeck#550]
**To Reproduce**
1. Set "Media hidden" preference on a column
2. Observe link previews being loaded

EDIT: `Show tweet cards inside columns` option is causing this.

**Expected behavior**
Do not load link preview. This worked fine in <4.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 89

**Comment by Athanasius** [comment]
Indeed, I had to turn off "Show tweet cards inside columns" to get the GitHub preview from BTD's own tweet to not show with 'median hidden' active.

**Comment by eramdam** [comment]
Good point, will fix in the next release.
