### ISSUE TITLE
Horizontal scrollbar doesn't span all the way down anymore

### ISSUE THREAD

**Issue by lc-guy** [eramdam/BetterTweetDeck#551]
The horizontal scrollbar used to span all the way down the visible page content before, so I could simply move my mouse to the very bottom of the screen and click-hold to move it around. Now, it seems there's 1 or 2px of margin between the scrollbar and the bottom that prevents me from doing that.

**Comment by eramdam** [comment]
Hum, I don't remember something like that. Could you show me a screenshot and tell me what browser/OS you're on?

**Comment by lc-guy** [comment]
![image](https://user-images.githubusercontent.com/5222114/113606379-340cd500-9648-11eb-9ed3-c658bc8293d4.png)
See the tiny margin below the scrollbar.
Latest Firefox, tried on both Linux laptop and Windows desktop.

**Comment by eramdam** [comment]
@lc-guy I'll have a fix for this in the next release, in the meantime you can add this as a bit of custom CSS

```css
html .app-columns-container {
bottom: 0 !important;
}
```
