### ISSUE TITLE
Buttons aligned differently with bigger column size

### ISSUE THREAD

**Issue by lc-guy** [eramdam/BetterTweetDeck#552]
![image](https://user-images.githubusercontent.com/5222114/113607370-68cd5c00-9649-11eb-988b-117349243947.png)

I remember the buttons being aligned differently before 4.0 when using larger column sizes than the default... was it right-align? Anyway, it looks off currently.

**Comment by eramdam** [comment]
I don't think there was any change? I launched v3 and here's how that specific tweet looks 
![image](https://user-images.githubusercontent.com/1409924/113609833-313ac180-9601-11eb-9d71-030daa242a93.png)

Looks the same to me 🤷

**Comment by lc-guy** [comment]
Heh, must have been my imagination. Sorry for the rubbish report.
