### ISSUE TITLE
[Question] "Custom CSS" data location in Firefox Profile

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#553]
Hello

With v4, all the settings went away and i have some Custom CSS in Better Tweetdeck which was wiped out (as all the other settings).

Because i have a copy of my Firefox profile with the old Better Tweetdeck, i want to ask if anyone knows where the settings from the extensions (specifically Better Tweetdeck) are stored in the Firefox profile to restore my Custom CSS. I can see the json and sqlite files, but i searched and didn't find them yet.

I could also restore the profile, but i'm curious to try to find them in this way first.

Thanks.

**Comment by JaxxArmstrong** [comment]
Just had Tweetdeck updated and all my custom CSS was also wiped out. It was a lot of code that went away and no way to get back. This is inexcusable.

Suggestions?

**Comment by eramdam** [comment]
> Hello
> 
> With v4, all the settings went away and i have some Custom CSS in Better Tweetdeck which was wiped out (as all the other settings).
> 
> Because i have a copy of my Firefox profile with the old Better Tweetdeck, i want to ask if anyone knows where the settings from the extensions (specifically Better Tweetdeck) are stored in the Firefox profile to restore my Custom CSS. I can see the json and sqlite files, but i searched and didn't find them yet.
> 
> I could also restore the profile, but i'm curious to try to find them in this way first.
> 
> Thanks.

Honestly you'd be better off disconnecting from the network, launching the old profile and grab the CSS from there because I'd assume Firefox encrypts the stored data in some way, or at least obfuscates it 😕

**Comment by JaxxArmstrong** [comment]
You helped me once before with the CSS code to customize the width of the Twitter 'compose' drawer, but that adding that code back does no longer work.

Secondly, I had CSS code to just adjust the first Tweetdeck column and leave the other ones at default.

If you wouldn't mind advising me what custom CSS code is necessary, please.

**Comment by eramdam** [comment]
> Just had Tweetdeck updated and all my custom CSS was also wiped out. It was a lot of code that went away and no way to get it back. This is inexcusable.
> 
> Suggestions?

None. I'm sorry that happened but I can't magically restore data that wasn't backed up in some way.

v4 now has an export/import feature so feel free to use that, and back up your CSS customization if it's very valuable. Even if I handled the migration, data get lost all the time and backing that up is just good habit.

**Comment by eramdam** [comment]
> You helped me once before with the CSS code to customize the width of the Twitter 'compose' drawer, but adding that code back does no longer work. #456

I copy paste the code in the last comment I posted in that issue and it works just fine.

> 
> Secondly, I had CSS code to just adjust the first Tweetdeck column and leave the other ones at default.
> 
> If you wouldn't mind advising me what custom CSS code is necessary, please.

You could probably do something like this

```css
.js-column.column:nth-child(n) {
width: 300px;
}
```
change `n` by a (starts from 1) and the width to whatever you want.

**Comment by LukasThyWalls** [comment]
> Honestly you'd be better off disconnecting from the network, launching the old profile and grab the CSS from there because I'd assume Firefox encrypts the stored data in some way, or at least obfuscates it 😕

I did like that because it seems it is impossible to read them normally. Funny enough, Cookies, passwords (user and passwords are encrypted, but the list with the sites is there), and a lot of other content are there in json and readable DBs, but those settings... no.

Thanks!

PD.: Cool the improved CSS editor!

**Comment by JaxxArmstrong** [comment]
> > Honestly you'd be better off disconnecting from the network, launching the old profile and grab the CSS from there because I'd assume Firefox encrypts the stored data in some way, or at least obfuscates it confused
> 
> I did like that because it seems it is impossible to read them normally. Funny enough, Cookies, passwords (user and passwords are encrypted, but the list with the sites is there), and a lot of other content are there in json and readable DBs, but those settings... no.
> 
> Thanks!
> 
> PD.: Cool the improved CSS editor!

If you have sync activated in your Firefox profile you can find the _Better Tweetdeck_ settings in the file _storage-sync-v2.sqlite_, for instance.

Just use a sqlite browser and open the file up.

**Comment by LukasThyWalls** [comment]
> If you have sync activated in your Firefox profile you can find the _Better Tweetdeck_ settings in the file _storage-sync-v2.sqlite_, for instance.
> 
> Just use a sqlite browser and open the file up.

I look it up, i use Fx Sync, and there is config data from other extensions (some of them are installed anymore) but not for BTD. I don't know...
