### ISSUE TITLE
Can't change column width

### ISSUE THREAD

**Issue by squidofman88** [eramdam/BetterTweetDeck#554]
Hey, new stuff looks great! Having trouble with my column width though, it doesn't matter what value I put in the custom width field, the column width never changes

**Comment by Athanasius** [comment]
Did you reload the tab/window after changing it and saving?  It seems to require that.  I have mine at my usual '49%' to have two columns visible.

**Comment by squidofman88** [comment]
Around 50 times, removed it, reinstalled it, tried numerous values, nothing.

Should add this is the chrome version!

**Comment by eramdam** [comment]
Works just fine here (Chrome 89 on macOS), I don't know what to tell you. Do you have something like an adblocker/ghostery that could conflict somehow?

**Comment by squidofman88** [comment]
Tried them disabled, now removed, still doesn't work. Weirdly I'm getting the same issue with standard Tweetdeck and even in Edge as well as Safari, so...guess I have some bizarre localised problem!

**Comment by squidofman88** [comment]
UPDATE: Fixed! I have no idea how, but a previous install of modern tweetdeck was responsible, once I reinstalled that and changed the width I could then change it in better tweetdeck.
