### ISSUE TITLE
Firefox - CPU / Memory Usage / Account Locking

### ISSUE THREAD

**Issue by v8dave** [eramdam/BetterTweetDeck#557]
Since the latest update, BTD has caused my CPU usage of Firefox (I only use Firefox for Twitter) to sit constantly between 3-5%, and the memory usage to ramp up over the period of an hour to several GB's before the entire computer becomes unresponsive and I have to kill Firefox in the task manager.

This morning I awoke to my Twitter account being locked due to suspected compromise, I am almost certain this is related.

running on Windows 7, Firefox 87.0 (64-bit).

I'm sorry it's not a more useful bug report, but i'm going to have to disable BTD for the time being :/, let me know if there is anything I can do to help debug this.

**Comment by eramdam** [comment]
Hum, TweetDeck by itself already has memory issues because I suspect it rarely does a cleanup of its internal state, I don't think BTD should make this worse but I can try to look into ways to avoid such memory leaks.

**Comment by v8dave** [comment]
7am - 1:30pm - used no more than 750mb of memory (without BTD)
1:30pm - 4:30pm - upto 3.2gb and still climbing

**Comment by eramdam** [comment]
> 7am - 1:30pm - used no more than 750mb of memory (without BTD)
> 1:30pm - 4:30pm - upto 3.2gb and still climbing (with BTD)

I see. I'll try to look into it, it might have to wait later this week because of my day job.

**Comment by eramdam** [comment]
@v8dave if you're willing, it be helpful for you to get a heap snapshot so we can try to see what exactly takes memory. Here is Mozilla's documentation of the Memory tool https://developer.mozilla.org/en-US/docs/Tools/Memory

**Comment by eramdam** [comment]
It also would be useful to know what kind of setup you have column-wise. I have TweetDeck opened right now (it's been only a few minutes) and the tab is steadily around 32MB of memory only but my columns are fairly quiet.

**Comment by v8dave** [comment]
> @v8dave if you're willing, it be helpful for you to get a heap snapshot so we can try to see what exactly takes memory. Here is Mozilla's documentation of the Memory tool https://developer.mozilla.org/en-US/docs/Tools/Memory

I've just rebooted, i'll run it for a couple of hours and then get a snapshot :)

**Comment by v8dave** [comment]
> It also would be useful to know what kind of setup you have column-wise. I have TweetDeck opened right now (it's been only a few minutes) and the tab is steadily around 32MB of memory only but my columns are fairly quiet.

I follow ~16k of people, i run 7 tabs.
1. Complete feed, mostly just flashes by
2. Notifications, just mentions/quoted/followers
3. Notifications, all
4. Messages
5. Possibly interesting list, contains ~3000 people who I don't normally follow
6. Debate/science list, about 50% of the people in this list i follow, the rest I usually disagree with.
7. Fun people,, list of a few hundred people I interact with a lot.

**Comment by eramdam** [comment]
> > It also would be useful to know what kind of setup you have column-wise. I have TweetDeck opened right now (it's been only a few minutes) and the tab is steadily around 32MB of memory only but my columns are fairly quiet.
> 
> I follow ~16k of people, i run 7 tabs.
> 
>     1. Complete feed, mostly just flashes by
> 
>     2. Notifications, just mentions/quoted/followers
> 
>     3. Notifications, all
> 
>     4. Messages
> 
>     5. Possibly interesting list, contains ~3000 people who I don't normally follow
> 
>     6. Debate/science list, about 50% of the people in this list i follow, the rest I usually disagree with.
> 
>     7. Fun people,, list of a few hundred people I interact with a lot.

😵 

Could you also share your settings file as well? (Settings -> Import/Export -> download settings), I have my suspicions of what might cause the leaks but having your settings could help me replicate your setup.

**Comment by v8dave** [comment]
[better-tweetdeck-settings-4.0.0-2021-04-06_19.38.53.json.txt](https://github.com/eramdam/BetterTweetDeck/files/6266903/better-tweetdeck-settings-4.0.0-2021-04-06_19.38.53.json.txt)

**Comment by v8dave** [comment]
> > @v8dave if you're willing, it be helpful for you to get a heap snapshot so we can try to see what exactly takes memory. Here is Mozilla's documentation of the Memory tool https://developer.mozilla.org/en-US/docs/Tools/Memory
> 
> I've just rebooted, i'll run it for a couple of hours and then get a snapshot :)

Not sure how helpful this is, as you can see from the the task manager to the right, the firefox process that is running the tweetdeck tab is running at 2.7gb, but the snapshot only show's it showing 558mb.

![FirefoxMemoryDump](https://user-images.githubusercontent.com/19746621/113768029-46a20f80-9717-11eb-8c53-0e987ab8ce80.png)

**Comment by eramdam** [comment]
@v8dave i would advise you look at the `about:performance` tab instead, it's supposed to be more accurate.

**Comment by eramdam** [comment]
@v8dave random thought: can you try disabling the "Show tweet cards inside columns" setting? I'm wondering if the huge "#document" blob are somehow iframes from the cards that TweetDeck doesn't free up from the memory

**Comment by v8dave** [comment]
> @v8dave random thought: can you try disabling the "Show tweet cards inside columns" setting? I'm wondering if the huge "#document" blob are somehow iframes from the cards that TweetDeck doesn't free up from the memory

That's got it, made a huge difference, not gone above 700mb since i restarted.

**Comment by eramdam** [comment]
> > @v8dave random thought: can you try disabling the "Show tweet cards inside columns" setting? I'm wondering if the huge "#document" blob are somehow iframes from the cards that TweetDeck doesn't free up from the memory
> 
> That's got it, made a huge difference, not gone above 700mb since i restarted.

Nice! At least I have a path to investigate 😁

**Comment by v8dave** [comment]
> @v8dave is your list with 3000 people in it public? If so I could add a column for it in my TD instance to make sure my bugfix actually works

unfortunately not, some people seem to not like being lists and I just use them for organising what i see in tweetdeck, i've found some i'm apparently on....

1.1k - https://twitter.com/i/lists/178786010
1.4k - https://twitter.com/i/lists/90939992
1.5k - https://twitter.com/i/lists/1091113082988814337
2.6k - https://twitter.com/i/lists/1121418658322890755
2.8k - https://twitter.com/i/lists/1121419891427299331
4k - https://twitter.com/i/lists/1051479648050106368
4.1k - https://twitter.com/i/lists/1118348149482041344
4.8k - https://twitter.com/i/lists/86047115

**Comment by eramdam** [comment]
@v8dave can you try this build and tell me how it goes? I made some changes that hopefully should reduce the memory usage while still being able to have the cards being loaded.

[better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6267823/better_tweetdeck-4.0.1.zip)


You'll have to sideload it because it's not signed https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by v8dave** [comment]
> @v8dave can you try this build and tell me how it goes? I made some changes that hopefully should reduce the memory usage while still being able to have the cards being loaded.
> 
> [better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6267823/better_tweetdeck-4.0.1.zip)
> 
> You'll have to sideload it because it's not signed https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

ok, this is performing better, but it's memory usage is still growing quite quickly, after a little over an hour i'm upto 1.2gb

**Comment by eramdam** [comment]
> > @v8dave can you try this build and tell me how it goes? I made some changes that hopefully should reduce the memory usage while still being able to have the cards being loaded.
> > [better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6267823/better_tweetdeck-4.0.1.zip)
> > You'll have to sideload it because it's not signed https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/
> 
> ok, this is performing better, but it's memory usage is still growing quite quickly, after a little over an hour i'm upto 1.2gb

I see. It's already a good step forward. I guess in your specific situation the cards might not be that useful anyway since you wouldn't have time to look at everything so disabling them isn't out of the question? 😁

**Comment by eramdam** [comment]
@v8dave I think I fixed the problem for good. It turns out I wasn't properly unmounting cards (they're rendered using React so if the corresponding component is never unmounted then it takes memory in React's tree) when their DOM elements was leaving the app. Try this build and let me know if it's better
[better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6268502/better_tweetdeck-4.0.1.zip)

**Comment by v8dave** [comment]
> @v8dave I think I fixed the problem for good. It turns out I wasn't properly unmounting cards (they're rendered using React so if the corresponding component is never unmounted then it takes memory in React's tree) when their DOM elements was leaving the app. Try this build and let me know if it's better
> [better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6268502/better_tweetdeck-4.0.1.zip)

2.5gb after running for a few hours :/

**Comment by eramdam** [comment]
@v8dave does it climb as fast as when you first opened the issue? Curious to know if my most recent change affects it. I guess I'll need to be more aggressive with it.

**Comment by eramdam** [comment]
@v8dave try this build. It removes the card on tweets as soon as they exit the viewport (before even they get removed from the DOM), it's a bit aggressive but I think it should work better in your case.

[better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6273633/better_tweetdeck-4.0.1.zip)

**Comment by v8dave** [comment]
> @v8dave try this build. It removes the card on tweets as soon as they exit the viewport (before even they get removed from the DOM), it's a bit aggressive but I think it should work better in your case.
> 
> [better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6273633/better_tweetdeck-4.0.1.zip)

Memory on the previous version was upto 1.2gb after an hour,  will try this latest version :)

**Comment by v8dave** [comment]
> > @v8dave try this build. It removes the card on tweets as soon as they exit the viewport (before even they get removed from the DOM), it's a bit aggressive but I think it should work better in your case.
> > [better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6273633/better_tweetdeck-4.0.1.zip)
> 
> Memory on the previous version was upto 1.2gb after an hour, will try this latest version :)

latest one 1.3gb in just over 2 hours, so improving I think :)

**Comment by eramdam** [comment]
@v8dave how did it go after ~5h? I'm thinking about merging my fix so I'm curious to hear from you.

**Comment by v8dave** [comment]
> @v8dave how did it go after ~5h? I'm thinking about merging my fix so I'm curious to hear from you.

Sorry, I didn't leave it open overnight, I will let you know in 5hrs heh :)

**Comment by v8dave** [comment]
> > @v8dave how did it go after ~5h? I'm thinking about merging my fix so I'm curious to hear from you.
> 
> Sorry, I didn't leave it open overnight, I will let you know in 5hrs heh :)

At 4hrs, it was upto 1.3gb, however it had became unresponsive, the console was showing....
going to run for a few hours without show tweet cards in col's disabled and see if it hits the same errors

![Error](https://user-images.githubusercontent.com/19746621/114022157-62b5c600-9869-11eb-8da2-32aa359877f2.png)

**Comment by eramdam** [comment]
@v8dave Here's an updated build which fixes some issues around infinite loops (if a tweet with a card was at the very bottom of the screen then it would re-render the cards everytime a new tweet appeared).

[better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6279965/better_tweetdeck-4.0.1.zip)

**Comment by v8dave** [comment]
> @v8dave Here's an updated build which fixes some issues around infinite loops (if a tweet with a card was at the very bottom of the screen then it would re-render the cards everytime a new tweet appeared).
> 
> [better_tweetdeck-4.0.1.zip](https://github.com/eramdam/BetterTweetDeck/files/6279965/better_tweetdeck-4.0.1.zip)

At about 2 hours, 1.1gb of memory used,  some repeated warnings, I've no clue if they are related to BTD, but thought i'd give you a screenshot.

![Error](https://user-images.githubusercontent.com/19746621/114080747-a62d2600-98a3-11eb-88ed-1507cb5c3d93.png)

**Comment by eramdam** [comment]
Nah those warnings are "normal", I see those even without BTD enabled. I think I will merge the fix later today and release tomorrow.

**Comment by eramdam** [comment]
@v8dave I plan on using a different way to render link previews and I'd like to get some feedback on the memory usage with a lot of columns. Would you be willing to try the below build for a few hours and tell me how it goes? 
[better-tweetdeck-4.3.2.firefox.zip](https://github.com/eramdam/BetterTweetDeck/files/6833808/better-tweetdeck-4.3.2.firefox.zip)

**Comment by v8dave** [comment]
> @v8dave I plan on using a different way to render link previews and I'd like to get some feedback on the memory usage with a lot of columns. Would you be willing to try the below build for a few hours and tell me how it goes?
> [better-tweetdeck-4.3.2.firefox.zip](https://github.com/eramdam/BetterTweetDeck/files/6833808/better-tweetdeck-4.3.2.firefox.zip)

Will do, will leave it running overnight and let you know in the morning :)

**Comment by v8dave** [comment]
Memory usage on 4.3.2 is fantastic :)

**Comment by eramdam** [comment]
> Memory usage on 4.3.2 is fantastic :)

Neat!
And you have the link previews enabled, right?

**Comment by v8dave** [comment]
> > Memory usage on 4.3.2 is fantastic :)
> 
> Neat!
> And you have the link previews enabled, right?

urm, what are link previews?, is that show tweet cards inside columns?, 
if so, no,
I'll enable it now and let it run for a few hours

**Comment by eramdam** [comment]
> > > Memory usage on 4.3.2 is fantastic :)
> > 
> > 
> > Neat!
> > And you have the link previews enabled, right?
> 
> urm, what are link previews?, is that show tweet cards inside columns?,

Yes 😅 

> if so, no,
> I'll enable it now and let it run for a few hours

**Comment by v8dave** [comment]
> > > > Memory usage on 4.3.2 is fantastic :)
> > > 
> > > 
> > > Neat!
> > > And you have the link previews enabled, right?
> > 
> > 
> > urm, what are link previews?, is that show tweet cards inside columns?,
> 
> Yes

heh, 2hrs in, it's using about 100mb more than without, but stable at that :D

**Comment by v8dave** [comment]
> > > > > Memory usage on 4.3.2 is fantastic :)
> > > > 
> > > > 
> > > > Neat!
> > > > And you have the link previews enabled, right?
> > > 
> > > 
> > > urm, what are link previews?, is that show tweet cards inside columns?,
> > 
> > 
> > Yes
> 
> heh, 2hrs in, it's using about 100mb more than without, but stable at that :D

Ok, Memory usage is going great, I did notice one thing I started a video in a card (youtube), it carried on playing long after it vanished off the screen, I had to reload to kill it.

**Comment by eramdam** [comment]
> > > > > > Memory usage on 4.3.2 is fantastic :)
> > > > > 
> > > > > 
> > > > > Neat!
> > > > > And you have the link previews enabled, right?
> > > > 
> > > > 
> > > > urm, what are link previews?, is that show tweet cards inside columns?,
> > > 
> > > 
> > > Yes
> > 
> > 
> > heh, 2hrs in, it's using about 100mb more than without, but stable at that :D
> 
> Ok, Memory usage is going great, I did notice one thing I started a video in a card (youtube), it carried on playing long after it vanished off the screen, I had to reload to kill it.

Neat! I'll look into the video thing, it might not be that hard to fix.
