### ISSUE TITLE
"Like from accounts" popup only on select accounts

### ISSUE THREAD

**Issue by passcod** [eramdam/BetterTweetDeck#559]
**Is your feature request related to a problem? Please describe.**

I have multiple accounts and really like the "like from accounts" new feature! However, I'd like to have it only trigger on one specific account where I'm often making the mistake, and not on my main where it's slowing me down...

**Describe the solution you'd like**

New setting when the feature is enabled to select which account gets it

**Describe alternatives you've considered**

Not enabling it, I guess :/

**Comment by eramdam** [comment]
I guess I could have a setting with a comma separated list of screennames of which account to enable it on 🤔

**Comment by passcod** [comment]
👍 or a regex or something, whatever's easiest
