### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Mohamed3on** [eramdam/BetterTweetDeck#56]
the bug happens in line 81, function s (probably should work on your function names :D)
the null causing the error is in variable e. I don't know what the purpose of the function is, so I can't stop it from being called.
![image](https://cloud.githubusercontent.com/assets/12295159/14963495/2a4b05e8-10a4-11e6-9640-33fd0b4fbe45.png)

**Comment by eramdam** [comment]
Hum, I won't take care of that in v2. I'm in a middle of a rewrite for v3 so it will be fixed naturally. And the `s` name comes from the minification process 😜

**Comment by Mohamed3on** [comment]
Good luck!
