### ISSUE TITLE
"Save tweeted hashtags" does not work

### ISSUE THREAD

**Issue by kun432** [eramdam/BetterTweetDeck#560]
**Describe the bug**
"Save tweeted hashtags" does not work. After tweeted with hash tags, hash tags in textarea are gone.

**To Reproduce**
1. Go to BTD settings, enable "Save tweeted hashtags", and save.
2. Reload TweetDeck.
3. Tweet with hash tags. (Ctrl+Enter or click on "Tweet")
4. hash tags are gone from textarea....

**Expected behavior**
After tweeted with hash tags, hash tags in textarea should be kept.

**Screenshots**
no, sorry.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome 89.0.4389.114（Official Build）（x86_64）
 - Version: Better TweetDeck 4.0.0

**Additional context**
no

**Comment by eramdam** [comment]
Hum, the hashtags are properly re-pasted inside the composer when the composer drawer gets closed/re-opened so I guess the real issue is that hashtags don't get pasted back after sending a tweet when the composer is still opened.

**Comment by kun432** [comment]
> the real issue is that hashtags don't get pasted back after sending a tweet when the composer is still opened.

so this is still a issue, right? I don't know why you closed this, but you mean I should open a new one?

**Comment by eramdam** [comment]
It's fixed on the main branch and will get in the next release, this is why I closed it
