### ISSUE TITLE
[Firefox Nightly] Download button not working

### ISSUE THREAD

**Issue by Kourai** [eramdam/BetterTweetDeck#561]
**Describe the bug**
The download media doen't work on firefox (Nothing happens)

**To Reproduce**
1. Load tweetdeck
2. find a cute meme you want to download
3. click on the download button provided by BTD
4. nothing happens (no error message, no message in the browser console either, and of course no image download)

**Expected behavior**
Image should be download to default location (as it does for Chrome)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser : Firefox Nigthly 89.0a1 (2021-04-02) (64-bit), or Firefox 87.0 (64-bit)
 - BTD Version : 4.0.0 

**Additional context**
I had the same bug BEFORE the 4.0.0, but as I knew it was out soon I didn't report hoping it will "fix itself"

I Try on google chrome which works quite well to download, and set the name of the file(s)

Here is my settings : 
``` 
{
  "tweetActionsPosition": "left",
  "showTweetActionsOnHover": true,
  "tweetActions": {
    "addCopyMediaLinksAction": true,
    "addDownloadMediaLinksAction": true,
    "addMuteAction": false,
    "addBlockAction": false
  },
  "showAccountChoiceOnFavorite": false,
  "usernamesFormat": "both",
  "tweetMenuItems": {
    "addRedraftMenuItem": true,
    "addMuteHashtagsMenuItems": true,
    "addMuteSourceMenuItem": true
  },
  "showLegacyReplies": false,
  "downloadFilenameFormat": "{{postedUser}}-{{year}}{{month}}{{day}}-{{fileName}}.{{fileExtension}}",
  "updateTabTitleOnActivity": true,
  "customColumnWidthValue": "400px",
  "needsToShowUpdateBanner": false,
  "biggerEmoji": true,
  "saveTweetedHashtags": false,
  "enableShareItem": false,
  "shouldShortenSharedText": true,
  "disableGifsInProfilePictures": false,
  "collapseReadDms": true,
  "replaceHeartsByStars": false,
  "theme": "default",
  "enableAutoThemeSwitch": false,
  "customAccentColor": "rgb(224, 36, 142)",
  "customCss": "",
  "useCustomColumnWidth": true,
  "needsToShowFollowPrompt": false,
  "installedVersion": "4.0.0",
  "timestampShortFormat": "HH:mm",
  "timestampFullFormat": "yyyy/MM/dd HH:mm",
  "timestampStyle": "custom",
  "showCardsInsideColumns": true,
  "useModernFullscreenImage": true,
  "pauseColumnScrollingOnHover": false,
  "useOriginalAspectRatioForSingleImages": true,
  "fullTimestampAfterDay": true,
  "removeRedirectionOnLinks": false,
  "showClearButtonInColumnsHeader": true,
  "showCollapseButtonInColumnsHeader": true,
  "showRemoveButtonInColumnsHeader": false,
  "hideColumnIcons": true,
  "smallComposerButtons": false,
  "avatarsShape": "circle",
  "scrollbarsMode": "default",
  "badgesOnTopOfAvatars": true,
  "addSearchColumnsFirst": false
}
```

**Comment by eramdam** [comment]
Hum, it works just fine here on Firefox 87 on macOS. I sometimes saw very weird bugs on Nightly versions of Firefox so I would try the stable version and see if the bug happens there or not.

**Comment by Kourai** [comment]
Well that's the 1st thing I try as I am aware of the strange bug on nightly. And  I got the exact same problem on firefox 87 (but still on Linux! I'll try to check the windows versions )

**Comment by eramdam** [comment]
The fact that it didn't work on v3 makes me think that somehow there's something different with Firefox on Linux regarding programmatically initiated download 😕  I don't have access to a Linux system so I can't investigate further.

Worst case you could use the Copy Links item to download from the link directly 🤷
