### ISSUE TITLE
Theme switcher doesn't apply automatically to the Trending columns

### ISSUE THREAD

**Issue by COLAMAroro** [eramdam/BetterTweetDeck#563]
**Describe the bug**
When my Windows goes into dark mode at night, TweetDeck goes into dark mode, except the trending tab. I had the same behaviour earlier today going from dark to white mode

**To Reproduce**
1. Enable automatic theme switcher
2. Open TweetDeck
3. Change the theme of the OS or the Browser (to trigger a theme change)

**Expected behavior**
The theme should change on the whole page, including trendings

**Screenshots**
![Screenshot of the bug](https://i.imgur.com/SNBcHas.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (20H2, build 19042.867)
 - Browser: Firefox Developer Edition (88.0b7 64Bits)
 - Version: 4.0.0

**Additional context**
Automatic switcher to dark theme I use is available [on this GitHub repo](https://github.com/Armin2208/Windows-Auto-Night-Mode)

**Comment by COLAMAroro** [comment]
Here is a screenshot after a manual refresh, showing it's just the issue is in the automatic changer, not the theme being broken
![Screenshot after a refresh of the page](https://i.imgur.com/c1EpQXe.png)

**Comment by COLAMAroro** [comment]
Issue fixed in 4.0.3, thanks 😃

**Comment by COLAMAroro** [comment]
Sorry, I'm a stupid idiot, I just moved the trending column out of the view...

**Comment by eramdam** [comment]
No worries, fix should be in the next release 😁
