### ISSUE TITLE
Timeline pause while still collecting new tweets

### ISSUE THREAD

**Issue by ravanga** [eramdam/BetterTweetDeck#564]
Twitter's insistence on the algorithmic timeline is incredibly frustrating.

Tweetdeck would be great if it would "save" your spot in the timeline so that you can chronologically scroll through newer tweets without the automatic scrolling engaging and without Twitter bundling new tweets together that it has to load separately.

The Fenix 2 app for Android and iOS has this feature. It stores new tweets in the background, which I can come to at any time to scroll through. However, I'd like a desktop solution. Is that something that's possible with Tweetdeck and this BetterTweetDeck extension?

**Comment by eramdam** [comment]
Unfortunately TweetDeck broke the "streaming off" setting a while back and re-instating would require deep access into the internal code of TweetDeck so it's not something I can do, I'm afraid 😞
