### ISSUE TITLE
youtu.be doesn't go fullscreen preview

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#570]
If the tweet contains **youtube.com** link the video opens in fullscreen preview overlay as expected, 
but if the tweet contains **youtu.be** link 

![youtu.be thumbnail](https://i.imgur.com/8pziKsC.jpg)

clicking on it opens the video only inside tweet column, impeding volume control.

![youtu.be preview](https://i.imgur.com/KUn8o0i.jpg)

Win7Ult, latest Waterfox

**Comment by eramdam** [comment]
That's just how TweetDeck does it, can't do much.
