### ISSUE TITLE
horizontal scrollbar

### ISSUE THREAD

**Issue by clumsyfingers** [eramdam/BetterTweetDeck#571]
great update but i ahve a horizontal scrollbar that didnt use to be there. is there a way to remove it?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by eramdam** [comment]
Please add a screenshot of the "horizontal scrollbar".

**Comment by clumsyfingers** [comment]
https://i.imgur.com/akOnAiG.png

**Comment by eramdam** [comment]
Yeah im not sure why this scrollbar appears 😕
