### ISSUE TITLE
Disable activity indicator in taskbar

### ISSUE THREAD

**Issue by katchy3132** [eramdam/BetterTweetDeck#572]
**Is your feature request related to a problem? Please describe.**

Starting with V4 a star/ activity indicator shows up when any column gets updated . 
![0fP2Cfup3S](https://user-images.githubusercontent.com/3707138/113984494-d6e56f00-9853-11eb-9778-c773395dcd8f.png)
Before V4  only a blue dot on the column that was updated would be shown ( I this this is TD and not BTD) 
![chrome_pi8j6rLJk6](https://user-images.githubusercontent.com/3707138/113984635-fb414b80-9853-11eb-861a-2f97040aeaaa.png)

**Describe the solution you'd like**

Ability to mute taskbar indicator so it acts like previous versions. Bonus points to customize it - ie. only update when a specified column is updated.

**Comment by eramdam** [comment]
![image](https://user-images.githubusercontent.com/1409924/114060460-40608000-984a-11eb-9a74-8128fca167f9.png)
