### ISSUE TITLE
"Share on Tweetdeck" do not function properly

### ISSUE THREAD

**Issue by syazyz** [eramdam/BetterTweetDeck#573]
**Describe the bug**
Update to newest version(4.0.0) and the problem occurred. When I use the "Share on Tweetdeck" in contextual menu, it always return a text without page title. The link of page also not be shorten.

**To Reproduce**
1. Go to any page
2. Right click and select "Share on Tweetdeck"
3. See error above

**Screenshots**
![2](https://user-images.githubusercontent.com/11090567/114032839-38b1d300-986c-11eb-866b-7569d777866c.jpg)
![3](https://user-images.githubusercontent.com/11090567/114032849-3cddf080-986c-11eb-8e12-9d057c7dc378.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]
 - Browser [Firefox 87.0 64bit]

**Comment by eramdam** [comment]
Will be fixed in the next release coming later this week.

**Comment by eramdam** [comment]
Fixed in 4.0.2 (propagating for different browsers).

**Comment by Geobert** [comment]
Follow up on this, using Ffx nightly and BTW 4.1.1, sharing doesn't put the title, only "..." (three dots)

**Comment by Geobert** [comment]
> 
> 
> @Geobert make sure the extension has the permissions to access tabs. And do note that I **do not** officially support Firefox Nightly, they regularly break random stuff in the WebExtensions API so I can't afford to chase any bug there.

It was the permission! So no future breakage from Ffx :) I don't remember turning it off though ¯\_(ツ)_/¯

Thank you for your time!
