### ISSUE TITLE
Tweetdeck cannot switch to light mode

### ISSUE THREAD

**Issue by kittykilian2** [eramdam/BetterTweetDeck#574]
**Describe the bug**
On iMac in Firefox my Tweetdeck picks dark mode as default (This started happening about 2 days ago). I have to go to the settings to change to light mode each time I reconnect to Tweetdeck (several times a day). As of today, april 9 2021, the toggle for light or dark mode has completely vanished, see screenshot. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![2021-04-09_09-49-52](https://user-images.githubusercontent.com/82205395/114148904-97358a80-991a-11eb-9785-243b46df18d3.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser Firefox
 - Version Most recent

**Additional context**

**Comment by eramdam** [comment]
The switch has not "vanished", I added the link for users to click and change the theme in Better TweetDeck's settings in order to prevent a situation where Better TweetDeck and TweetDeck have different opinions on what theme to apply.

**Comment by eramdam** [comment]
Fixed in 4.0.4
