### ISSUE TITLE
Quick retweet button

### ISSUE THREAD

**Issue by steinuil** [eramdam/BetterTweetDeck#575]
**Is your feature request related to a problem? Please describe.**

I use have two accounts, I like to retweet a lot of stuff on one of them and having to navigate to the popup at the center of the screen and clicking the retweet button is one too many clicks.

**Describe the solution you'd like**

I'd like a button next to the reply/rt/like button that retweets the tweet from the account associated to the column (if there is such a thing) without asking if I want to change account or make a quote rt instead.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
