### ISSUE TITLE
"Like from Accounts" doesn't work (network 404s)

### ISSUE THREAD

**Issue by bradwilson** [eramdam/BetterTweetDeck#576]
**Describe the bug**

I enabled the "Show account picker when clicking on the like button" feature. When clicking the like button, I see the popup for all my accounts, and then in the upper right corner I see the message "Cannot retrieve favorite status" shown once for each account. The account list like buttons contain spinners forever.

In the Network tab, I see one failed requests (HTTP 404) per account, all hitting https://api.twitter.com/1.1/statuses/show.json.

**Screenshots**

Failure popup:
![image](https://user-images.githubusercontent.com/16944/114219587-b4208c80-991f-11eb-9222-bfcbfa19e61c.png)

Network error list:
![image](https://user-images.githubusercontent.com/16944/114219722-e3cf9480-991f-11eb-9a21-dee2944b9f1c.png)

Request:
![image](https://user-images.githubusercontent.com/16944/114220008-4a54b280-9920-11eb-804c-cef64571eed9.png)
![image](https://user-images.githubusercontent.com/16944/114220532-f9918980-9920-11eb-9f54-51069ac5e25c.png)

Response:
![image](https://user-images.githubusercontent.com/16944/114220722-3198cc80-9921-11eb-9d03-8b72f41b9e09.png)
![image](https://user-images.githubusercontent.com/16944/114220291-a7506880-9920-11eb-94f7-50fc77e2edd7.png)

**Desktop (please complete the following information):**

 - OS: Windows 10 20H2
 - Browser: Firefox 
 - Version: 87.0

**Comment by eramdam** [comment]
It's possible that this given tweet was deleted. TweetDeck doesn't remove deleted tweets so it gives you the impression that you can interact with it when it fact you can't. Is that happening on all tweets?

**Comment by eramdam** [comment]
Yeah I just confirmed that this happens when the target tweet has been deleted. Unfortunately I can't detect that (otherwise I would have made a fix to remove the tweet from the UI to prevent this from happening).

**Comment by bradwilson** [comment]
This isn't a deleted tweet. This can be reproduced on all tweets for me.

**Comment by bradwilson** [comment]
Ah, additional information: it's in the Notifications column where this fails for me 100% of the time.

**Comment by eramdam** [comment]
Okay then I repro. My guess is that I'm picking up the wrong tweet there, you should have lead up with that 😄

**Comment by bradwilson** [comment]
I didn't realize until I just went to verify after you closed the bug. I only tried it with mentions, but didn't realize that was a factor. 😛
