### ISSUE TITLE
Please add an option to disable the emoji menu that appears and covers the tweet button.

### ISSUE THREAD

**Issue by Amariithynar** [eramdam/BetterTweetDeck#578]
When I type ":D" or ":P" I want it to be ":D" or ":P", not to have a menu pop up that covers the "tweet" button appear and prevent me from sending the tweet. There needs to be an option to stop this behaviour. Unfortunately, there isn't, in BTD or otherwise. So, I come here to ask for just that.

**Comment by eramdam** [comment]
1. You can use Ctrl+Enter on Windows or Cmd+Enter on Mac to send your tweet without the mouse
2. I'll look into making emoji stuff into settings

**Comment by Amariithynar** [comment]
Thank you very much! Even if it turns out not to be possible for some reason, thank you for at least looking into it, and for the alternative method to send a tweet even if it appears!

**Comment by Amariithynar** [comment]
Awesome, thank you so much, once again!
