### ISSUE TITLE
Dark/Light mode disappeared on Desktop Tweetdeck + themes button doesn't work

### ISSUE THREAD

**Issue by dukefolk** [eramdam/BetterTweetDeck#580]
On the desktop version the dark/light mode button has been removed and replaced with a themes button that actually doesn't work. When I click on it it won't do anything so I'm stuck to dark mode by default.

**Comment by eramdam** [comment]
What browser are you using? This would be really useful in order to know what’s going on. @dukefolk

**Comment by dukefolk** [comment]
Hi,

I am using Chrome

**Comment by eramdam** [comment]
I can't reproduce on Chrome, the link works fine for me... perhaps Chrome is blocking the opening of the window somehow?

**Comment by eramdam** [comment]
Fixed in 4.0.3
