### ISSUE TITLE
Embeeded tweets get displayed multiple times when viewing a quoting tweet with an image and returning to the timeline

### ISSUE THREAD

**Issue by Wanyal** [eramdam/BetterTweetDeck#581]
**Describe the bug**
A tweet embedded in another tweet gets displayed multiple times if you click on the quoting tweet, and then go back to the timeline that quoting tweet was on, and each time you do this the tweet getting quoted is embedded one more time.

**To Reproduce**
1. Add column that contains a tweet that quotes another tweet and has an image attached (e.g. https://twitter.com/ByYourLogic/status/1380721375036444676)
2. Click on the tweet to make the column show that tweet and its replies.
3. Go back to the column the tweet was in
4. Observe the embedded tweet for the tweet in question is now embedded twice

**Expected behavior**
The tweet being quoted stays only embedded once in the quoting tweet

**Screenshots**
![firefox_JM4oBj8nVK](https://user-images.githubusercontent.com/3915657/114268217-e4d3f500-99f7-11eb-8778-64b762bd5de3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19042.906
 - Browser: Firefox 87.0
 - Version: 4.0.2

**Additional context**

**Comment by eramdam** [comment]
Yep 😅 I noticed the same bug on my end yesterday. It will be fixed in the next release. Probably next week

**Comment by eramdam** [comment]
Fixed in 4.0.3
