### ISSUE TITLE
Stuck in Dark Mode

### ISSUE THREAD

**Issue by jewels667** [eramdam/BetterTweetDeck#584]
Several times since the update TweetDeck has flipped to dark mode on its own after a refresh. Now it no longer gives me the option to select light mode. Under Theme it says "select theme preferences" on what looks like a hyperlink. Dark/Light ticky box no longer available. When you click the text, nothing happens. I am using Chrome.

**Comment by eramdam** [comment]
Duplicate of https://github.com/eramdam/BetterTweetDeck/issues/580

**Comment by eramdam** [comment]
Fixed in 4.0.3
