### ISSUE TITLE
Focus lost

### ISSUE THREAD

**Issue by tristangrimaux** [eramdam/BetterTweetDeck#587]
The focus is lost in the tweet editor

Start writing a tuit, change to another app, get back: the focus is lost

**Expected behavior**
The cursor should still be there. Very annoying when adding content to a tuit

I'm using latest Chrome on Linux. Happened after the upgrade to version 4.0.2, still going on in version 4.0.3

**Comment by eramdam** [comment]
It seems to happen even without Better TweetDeck enabled, then it's not a Better TweetDeck bug
