### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by artnathanh** [eramdam/BetterTweetDeck#589]
Tweetdeck lacks Twitter's "new" bookmark feature - "Add to Bookmarks" under the ... menu would be great, as would a "Bookmarks" column.

**Comment by eramdam** [comment]
Like I say [every time this gets asked](https://github.com/eramdam/BetterTweetDeck/issues?q=is%3Aissue+bookmark+is%3Aclosed): I can't do it because it's all behind Twitter's private API and interacting with it would get me in trouble with Twitter 😬
