### ISSUE TITLE
Tweets with a link to deviantart (Not direct link to image) shows a blank thumbnail

### ISSUE THREAD

**Issue by Primeey** [eramdam/BetterTweetDeck#59]
[Without BetterTweetDeck](https://i.imgur.com/whi6ccZ.png)

[With BetterTweetDeck](https://i.imgur.com/UJftYaM.png)

[Direct link to the image works though](https://i.imgur.com/swjnIfP.png)

[The link in question](http://magnega.deviantart.com/art/My-Overwatch-open-beta-experience-609143595)

**Comment by eramdam** [comment]
Thx, will fix that in v3 anyway
