### ISSUE TITLE
Unable to insert a displayed emoji by clicking

### ISSUE THREAD

**Issue by f6fvy** [eramdam/BetterTweetDeck#591]
When entering the first characters of an emoji (like ":thum" - for "thumb"), a selection (list) of emojis is displayed below the text input field, but clicking on one of them doesn't insert it. Using the up/down arrows and "Enter" work, though.

Version 4.0.3 on FF 87.0 (32 bits) - Win7

**Comment by eramdam** [comment]
Will be fixed in the next release
