### ISSUE TITLE
Column Specific "Like from Account" & Dialog Staying Open

### ISSUE THREAD

**Issue by AllOutJay** [eramdam/BetterTweetDeck#592]
Not sure if this was a feature in BetterTD or just TD, but will there be any option like before to just like from multiple accounts without the popup/dialog closing when you like it from one account? I found that to be useful when I wanted to like from multiple accounts quickly without having to click ellipsis and then "Like from accounts..." to like from the other account(s).

Also, I was wondering if there was anyway to make "Like from Account" be column specific or for that to be looked into. Since the 2 accounts I run have some similarities but aren't entirely that similar, there are certain situations where I would only like to like from a specific account versus all the time. Example, I want the dialog to pop up only on a column specific to a list I made since that correlates to both of them.

**Comment by eramdam** [comment]
>  but will there be any option like before to just like from multiple accounts without the popup/dialog closing when you like it from one account?

Unfortunately the closing mechanism is a limitation TweetDeck coded a while back to prevent users with multiple accounts to mass like/RT and it's deep within the code of those components so I can't reliably hack into that if I wanted to.

> Also, I was wondering if there was anyway to make "Like from Account" be column specific or for that to be looked into. Since the 2 accounts I run have some similarities but aren't entirely that similar, there are certain situations where I would only like to like from a specific account versus all the time. Example, I want the dialog to pop up only on a column specific to a list I made since that correlates to both of them.

This is a good idea but unfortunately there is not (to my knowledge) a good way to reliably identify a specific column in TweetDeck without relying on their internal ID, which aren't really exposed in the UI, so I'd need to somehow think of an UI way to expose them/allow them to be picked. Which is a lot of work for an arguably niche feature. 

If I think of a better solution I'll revisit this for I'll close as wontfix for now, sorry 😞
