### ISSUE TITLE
(Minor) Re-Drafting a tweet doesn't keep the actual recipients

### ISSUE THREAD

**Issue by COLAMAroro** [eramdam/BetterTweetDeck#594]
**Describe the bug**
When re-drafting a tweet when someone has been explicitly unchecked for mentions, the new draft comes back to it's default about recipients

**To Reproduce**
1. Respond to a tweet with at least two "mentionned" account (responding to your own tweet works too, if someone else also can be mentionned)
2. Re-draft the tweet

**Expected behavior**
The redrafted tweet should keep the same recipients (instead of reverting to default one)

**Screenshots**
In case I'm unclear (sorry, I'm bad at english), I am talking about this panel
![Screenshot of recipients list](https://i.imgur.com/ugzAKVI.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 (Build 19042.928)
 - Browser: Firefox Developer Edition - Version 88.0b8
 - Version: 4.1.0

**Additional context**
This is probably not a bug, just an oversight, and it's really minor

**Comment by eramdam** [comment]
Could you check if this is still an issue? Last time I tried reproducing the issue I couldn't no matter what I did so either I fixed it without knowing it or I'm missing something.

**Comment by COLAMAroro** [comment]
Just tested it again, I still have the issue.

Windows 11 21H2 (Build 22000.856)
Firefox Developer Edition - Version 105.b6 (64 bits)
BTD version 4.8.6

This was right before sending the tweet
![image](https://user-images.githubusercontent.com/12484955/188270299-9d685ecb-6c34-49c5-b852-2a8881a28c36.png)
This was right after re-drafting
![image](https://user-images.githubusercontent.com/12484955/188270306-fcf070a6-c486-470f-b3e2-c6487b0a3d96.png)
