### ISSUE TITLE
Add a tooltip with the full date on hover when the date is relative or custom

### ISSUE THREAD

**Issue by Mozinet-fr** [eramdam/BetterTweetDeck#596]
When the date format is relative or custom (e.g. with year removed), it could be useful to display the complete date in a tooltip on mouse over.

**Comment by eramdam** [comment]
It turns out TweetDeck has a method I can easily use to display a given Date object into a full representation, so this is how it would look 
![image](https://user-images.githubusercontent.com/1409924/116200494-403afe00-a6ed-11eb-8c9b-e95d0304e280.png)

Would that do the job?

**Comment by eramdam** [comment]
Now that I look at the code of that method, it seems like it only renders time into a 12h format so I guess I'll need to add a format option for that tooltip as well 😅

**Comment by Mozinet-fr** [comment]
Can't you reuse the global format option?

**Comment by eramdam** [comment]
I guess. But I feel like it might sound confusing that the global format option applies even if you set the timestampsa s relative? 🤔
