### ISSUE TITLE
Settings page blank on Waterfox Classic 2021.03

### ISSUE THREAD

**Issue by Diyamund** [eramdam/BetterTweetDeck#598]
**Describe the bug**
Hi! I recently moved to Waterfox Classic from Firefox, and I noticed the settings page is blank.

**To Reproduce**
1. Go to the settings page in Waterfox Classic.
2. The page should be blank with nothing but the tab title

**Expected behavior**
Better TweetDeck's options should show up.

**Screenshots**
[A screenshot I posted on Imgur](https://imgur.com/a/u9S1NIj)
[A screenshot on a clean install of Waterfox Classic to prove that it's not any addons colliding](https://imgur.com/a/zH3VBDl)

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC 2019 (Build 17763.1852)
 - Browser: Waterfox Classic 2021.03
 - Version: 4.1.0

**Comment by eramdam** [comment]
Waterfox Classic runs a 4 years old version of Gecko so unfortunately I can’t reliably support that. Sorry.
