### ISSUE TITLE
Add the option "engagement" on the "Activity" and "List' column

### ISSUE THREAD

**Issue by flinterwood** [eramdam/BetterTweetDeck#599]
When we search for hashtags, we can see an option called "engagement" which we can set the amount of likes/retweets to be shown on the column. Is there a way to put this option on the "Activity" or "List" too?

**Comment by eramdam** [comment]
Unfortunately, the engagement options are simply mapped to [search modifiers](https://twitter.com/search-advanced). Since the Activity and List columns aren't powered by the search, there's not much I can do.
