### ISSUE TITLE
Turn off autoplay of GIFs

### ISSUE THREAD

**Issue by KAMiKAZOW** [eramdam/BetterTweetDeck#60]
Would  be cool if there was an option to turn off GIF autoplay.

**Comment by eramdam** [comment]
Planned in v3 😄  https://github.com/eramdam/BetterTweetDeck/tree/v3#ok-thats-cool-what-about-features

**Comment by KAMiKAZOW** [comment]
So leave this report open because it's not yet implemented?

**Comment by eramdam** [comment]
Yes.
