### ISSUE TITLE
Contextual menu entry cannot be removed in Brave

### ISSUE THREAD

**Issue by vphantom** [eramdam/BetterTweetDeck#607]
**Describe the bug**

In Brave with BetterTweetDeck version 4.1.0, the context menu item for BetterTweetDeck seems to be permanent; the option to remove it has no effect.

**To Reproduce**
1. Go to `BTD Settings`
2. Uncheck `Share on TweetDeck" item in the browser's contextual menu`
3. Click `Save`
4. Open a new tab to any web site
5. Right-click anywhere

**Expected behavior**
I expect for the context menu item to be gone, as it was in the past. This seems to be a recent bug or an incompatibility with Brave or Chrome 90 (I was on Chrome 89 previously).

**Desktop (please complete the following information):**
 - OS: Linux 64-bit
 - Browser: Brave
 - Version: 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)

**Comment by eramdam** [comment]
I don't use Brave on a regular basis but I assume the right click item should disappear after a reboot of Brave because that's typically when the background script of the extension starts up. You tried that, right?

**Comment by vphantom** [comment]
Oh this is embarrassing… No I had not restarted the whole browser, I was unaware that some extensions were browser-wide.

I can confirm that restarting Brave removed the menu item.

Should we add a `(requires browser restart)` next to that option?

**Comment by eramdam** [comment]
> No I had not restarted the whole browser, I was unaware that some extensions were browser-wide.

Well, the only way to register a contextual menu is inside the background script of an extension, and that script is (typically) ran only when the browser starts (since it's supposed to stay up always).
I'll try to look into making it so changing the settings removes the contextual menu without requiring a browser restart, although I have no idea if that's doable 😁

**Comment by eramdam** [comment]
Fixed in [4.2.0](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.2.0)
