### ISSUE TITLE
Spacer column

### ISSUE THREAD

**Issue by bennett4senate** [eramdam/BetterTweetDeck#609]
I use Tweetdeck for 3 different accounts, and usually have multiple columns open for each - home, notifications, messages at minimum - which are each grouped together. I would love to have a new Column type that is just a horizontal spacer, maybe high-contrast, that I could create and move to the appropriate position between each of the account groups for better visual differentiation between the groups. I could try adding a column with no content, but I think a spacer could be much smaller and take up less horizontal space.  
![Screen Shot 2021-05-06 at 10 50 19 AM](https://user-images.githubusercontent.com/13912492/117343202-e65ad680-ae58-11eb-8dbc-74fe35a0cc4c.png)

**Comment by bennett4senate** [comment]
Today I looked more thoroughly through the BTD setting page and found the ability to collapse columns. I also enabled avatars on top of columns. I'm finding that a collapsed column is largely meeting my needs for a visual spacer, and is aided by the avatars at the top of columns which also makes it clear which account I'm looking at. It still requires creating an empty column to collapse, and there's no option to change the color of a collapsed column, so I'll leave this issue open, but definitely have a viable workaround for now. thanks.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
