### ISSUE TITLE
Advanced mute engine

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#61]
Right the TweetDeck's mute engine is very simple and limited. It can only mute keywords/usernames/sources.

- [x] Regex filters
- [x] hashtag from menu
- [x] source from menu

**Comment by cmdrfletcher** [comment]
Also it would be nice if one could add a hasttag to mute via context menu.

**Comment by pixeldesu** [comment]
> mute tweets that match /regex/g

Done with #179 

> Also it would be nice if one could add a hashtag to mute via context menu.

Done with #180
