### ISSUE TITLE
Prevent ESC from closing composer and lose text

### ISSUE THREAD

**Issue by carlosedp** [eramdam/BetterTweetDeck#610]
**Describe the bug**
Is there any way to prevent ESC key from losing the content in a tweet that is being composed?

**To Reproduce**
1. Open Tweet composer
2. Hit ESC twice, it will close the composer
3. Text will be lost

**Expected behavior**
A way to keep the text in the compose area.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by eramdam** [comment]
TweetDeck has a "Stay open" checkbox for this. 
![image](https://user-images.githubusercontent.com/1409924/118380239-0dba4d80-b595-11eb-87c4-72f60de68f63.png)

I'd rather not reinvent the wheel for this specific issue.
