### ISSUE TITLE
Option to keep notification on

### ISSUE THREAD

**Issue by mmrsva** [eramdam/BetterTweetDeck#611]
In the past, if I missed a notification on Tweetdeck it would stay on the notification center on Windows until dismissed manually. Now, it disappears after a few seconds.

I wonder if it's possible for BetterTweetDeck to override this setting and make it stay until dismissed (with a config option so only those who want this feature enable it)

It's not a browser issue because other sites keep notifications until dismissed it only happens with Tweetdeck (but only recentrly, in the past Tweetdeck notifications stayed too).

Thanks for the good work so far!

**Comment by eramdam** [comment]
So I tried fiddling around and I can't seem to get a notification that stays on either Windows or macOS. And even with that, different OSes do different things with the `requireInteraction` option for HTML5 notifications, Windows seems to honor it fine, macOS doesn't so I'm not a fan of adding a setting that will apply only on specific OSes.. 😕 

If a lot of people end up requesting this I might reconsider but I'll be closing this issue for now.
