### ISSUE TITLE
add more tab on the left panel to navigate through the columns

### ISSUE THREAD

**Issue by flinterwood** [eramdam/BetterTweetDeck#612]
as i have tons of lists/columns on tweetdeck, it's kind of useless to navigate through the keys 1-9 on keyboard. i must navigate through the left panel, but it only shows 5 tabs per scroll. should have an option to increase more tabs to be shown at once on the left panel, so i don't have to scroll them

**Comment by eramdam** [comment]
I'm not sure I understand correctly, because the "limited" amount of space to show the columns in the sidebar is caused by the buttons shown in the bottom part of the sidebar, so I can't exactly show more without breaking the layout in weird ways/removing buttons 😕
