### ISSUE TITLE
Mute Conversation shows conversation in mentions and notifications columns

### ISSUE THREAD

**Issue by denaghdesign** [eramdam/BetterTweetDeck#613]
When selecting the "mute this conversation" option, tweets and replies to the conversation still appear in mentions and notifications.

**To Reproduce**
1. Go to a tweet in the notifications column
2. Click on the tweet's contextual menu
3. Scroll down to "Mute this conversation', click.
4. Refresh page/reload browser, conversation is still visible.

**Expected behavior**
Muting a tweet or conversation should remove it from my timeline, notficaitons, and mentions, as implied here: https://help.twitter.com/en/using-twitter/advanced-twitter-mute-options

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox, Chrome

**Comment by eramdam** [comment]
Unfortunately that might be a TweetDeck backend bug that I can't do much about 😞
