### ISSUE TITLE
Long-press like/rt to pick account for action

### ISSUE THREAD

**Issue by Kiloku** [eramdam/BetterTweetDeck#614]
**Is your feature request related to a problem? Please describe.**
I have multiple accounts, and sometimes I want to react to a tweet from an account that's not the same one that's associated with a given column. This is frequent enough that clicking the "more options" button, then "Like from accounts" and finally picking the account gets annoying.

**Describe the solution you'd like**
If I long press on a Like button or an RT button, it'd quickly bring up a list of your accounts, and clicking the one you want to use would do the action instantly.

**Describe alternatives you've considered**
None that I can tell

**Comment by eramdam** [comment]
There's no good/reliable ways to do "long press" in a web browser so I can't really do that.
