### ISSUE TITLE
Emoji selector acts erratically when no valid emoji is found (i.e. ":S", ":gjsgh32")

### ISSUE THREAD

**Issue by CharmsyPone** [eramdam/BetterTweetDeck#618]
Hey there! This is a bug that has been present since the recent revamp of BetterTweetDeck, and hasn't occured in the previous version.

Basically whenever I'm typing out a tweet and it uses a colon, followed by a _single_ letter or number, it doesn't show the emoji selector. Which is good, it shouldn't! But BetterTweetDeck also pretends that it is being displayed, and as such it does some weird behaviors. i.e. Typing in something like "I just played CS:S", and pressing enter to line break, will result in something like "I just played CS🔪", it's dependent on the most recent emoji you selected.

This also prevents ctrl+enter from working to post a tweet, just blocking it all together. Of course all this also happens with faces such as :D, :3, :P, etc. etc. This also occurs when there's no valid emoji to search for, i.e. :3c or something like :gfdklj35 does nothing, but still has the aforementioned problems.

So I'm hoping for a solution where it retains the "don't show emoji selector if it's the first character/no emoji found", much like the previous version of BetterTweetDeck (and it's something all good programs should do, looking at you Telegram), but it also fixes this annoying bug.

**Comment by eramdam** [comment]
It sounds like https://github.com/eramdam/BetterTweetDeck/issues/608 ? If so, it will be fixed in the next release

**Comment by CharmsyPone** [comment]
> It sounds like #608 ? If so, it will be fixed in the next release

Ah yep, that's the same thing basically. Just hoping you also know this happens regardless of character length, if it just doesn't match an actual emoji name.
