### ISSUE TITLE
Add A Gif stays after closing New Tweet tab and closes the entire New Tweet tab afterwards

### ISSUE THREAD

**Issue by aarsch** [eramdam/BetterTweetDeck#619]
DESCRIPTION
The display for "Add a Gif" stays open after closing the "New tweet" tab that it is displayed over using the +Feather button on the top left. Also, closing the "Add a Gif" tab with the X on the top right after the first bug has been experienced results in the entire "New tweet" tab closing instead of just the "Add a Gif" display.

REPRODUCTION
1. Open the tab "New tweet" via the top left button (the + with the quill/feather) and check mark "Stay open"
2. Click on the "Gif" button to add a gif, but do NOT add a gif.
3. With the selection of gifs displayed over the tab, close the "new tweet" tab entirely by clicking the top left button it was opened with. (do NOT close it with the X in the top right)
4. The "Add a Gif" tab stays open, even though the "New Tweet" tab was collapsed.
5. Open the "New tweet" tab again.
6. Close the "Add a Gif" window with the big X in the top right of the displayed window.
7. The entire "New tweet" tab collapses instead of just the "Add a Gif" display.

PREVIOUS EXCECTATION
Closing the "New tweet" tab with the "Add a Gif" display results in the entire collaps of the tab, INCLUDING the "Add a Gif". (Steps 1 - 4)
Closing the "Add a Gif" with the X afterwards results in only the "Add a Gif" window closing, NOT the entire tab collapsing. (Steps 5 - 7)

**Screenshots**
The "New tweet" tab is open, seen by the darker color going towards the "Add a gif" from the + Quill symbol on the left.
![image](https://user-images.githubusercontent.com/84548761/119064153-fcc96c00-b9da-11eb-8e9a-2da366f294f2.png)

The "New tweet" tab is closed, seen by the blue circle around the + Quill, but the "Add a Gif" display stays open.
![image](https://user-images.githubusercontent.com/84548761/119064634-0ef7da00-b9dc-11eb-9547-703b6457f3eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 90.0.4430.212

**Additional context**
Funny story, that was for some reason literally the first experience I had with Better Tweetdeck and I tried to explain to my acquaintances why that was bad but they didn't understand why I was mad. We then realized it must be a bug but they still didn't recognize I was right and I feel so sad. They always make fun of me when I complain about anything. Anyways stay safe person reading this and drink enough water please.

**Comment by eramdam** [comment]
Will be fixed in the next release

**Comment by eramdam** [comment]
Fixed in [4.3.0](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.0)!
