### ISSUE TITLE
Keyboard Shortcut: Clear Column

### ISSUE THREAD

**Issue by mdroidian** [eramdam/BetterTweetDeck#625]
**Is your feature request related to a problem? Please describe.**
When I'm using they keyboard to navigate tweets in a column, and across columns, it would be awesome to be able to use a keyboard shortcut to clear the column I'm in.

**Describe the solution you'd like**
- Define keyboard shortcut in settings
- Press defined keyboard shortcut to clear column 
- (mimicking exactly what the clear button currently does, only via keyboard)

**Describe alternatives you've considered**
https://greasyfork.org/en/scripts/15976-tweetdeck-clear
Vimium Chrome Extension

**Comment by eramdam** [comment]
Like I described [here](https://github.com/eramdam/BetterTweetDeck/issues/443#issuecomment-855173871), there's no good way for me to tell what column is focused (TweetDeck's "focus" methods only temporarily mark columns..).

**Comment by mdroidian** [comment]
When browsing with the keyboard, the class `.is-selected-tweet` is added to the `article`.  

Would that help?

**Comment by tyrosinase** [comment]
:bulb: What if focus didn't matter, and we could just define a hotkey to clear column 1, another for column 2, etc.?
