### ISSUE TITLE
Horizontal Scroll: Right Click+Hold and Drag

### ISSUE THREAD

**Issue by mdroidian** [eramdam/BetterTweetDeck#626]
**Is your feature request related to a problem? Please describe.**
If I'm using the mouse, clicking on the columns on the left sidebar or finding the little horizontal scrollbar seems cumbersome.

**Describe the solution you'd like**
Hold Right Click and drag left or right to enable horizontal scrolling
a la https://app.diagrams.net/

**Describe alternatives you've considered**
Using keyboard shortcuts
[Shift and Mouse Wheel](https://github.com/eramdam/BetterTweetDeck/issues/627)

**Comment by eramdam** [comment]
See https://github.com/eramdam/BetterTweetDeck/issues/627
