### ISSUE TITLE
Horizontal Scroll: Shift + Mouse Wheel

### ISSUE THREAD

**Issue by mdroidian** [eramdam/BetterTweetDeck#627]
**Is your feature request related to a problem? Please describe.**
If I'm using the mouse, clicking on the columns on the left sidebar or finding the little horizontal scrollbar seems cumbersome.

**Describe the solution you'd like**
Hold Shift and use mouse wheel to enable horizontal scrolling

**Describe alternatives you've considered**
Using keyboard shortcuts
[Right Click + Drag](https://github.com/eramdam/BetterTweetDeck/issues/626)

**Comment by eramdam** [comment]
I just tried in a Windows VM and this already works out of the box. I'm not sure I understand why I should implement this on TweetDeck's side.

**Comment by mdroidian** [comment]
Ah, right.  If your mouse is on the header of the column, it works!  Thanks!
