### ISSUE TITLE
Changing Accent Color does nothing

### ISSUE THREAD

**Issue by pizzaforfree** [eramdam/BetterTweetDeck#628]
**Describe the bug**
Just updated to 4.2.0, noticed my accent color was typical Twitter blue. Checked BTD settings, and my old accent color was still selected. Tried changing to a different accent color, both predescribed and hex selected, save, refresh BTD, still shows twitter blue. Did this multiple times, but twitter blue remained. 
EDIT: I should add that while the accent color isn't applied graphically, element inspector does show the correct color in --btd-accent-color, as shown in the following screenshot.
![image](https://user-images.githubusercontent.com/34205285/120977551-0ff96d00-c739-11eb-8ae1-612d26bf6d77.png)

Screenshot shows selected accent color (FFA789) does not match applied accent color. Columns closed for privacy.
![image](https://user-images.githubusercontent.com/34205285/120973634-d0308680-c734-11eb-958e-f0bd3988ae11.png)

**To Reproduce**
Reproduction of the bug can be done by simply changing the accent color.

**Expected behavior**
Expected accent color to apply.

**Desktop**
 - OS: Windows
 - Browser: Firefox 89.0 64bit
 - Version: 4.2.0

**Comment by eramdam** [comment]
Yep, I broke something 😓  Should be fixed in the next release!

**Comment by eramdam** [comment]
Fixed in [4.2.1](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.2.1)
