### ISSUE TITLE
Settings button in collapsed column

### ISSUE THREAD

**Issue by viki53** [eramdam/BetterTweetDeck#630]
**Describe the bug**

When a column is collapsed I can still see and click on the Settings button but clicking it doesn't do much as the settings section appears in a column that's collapsed. 

**To Reproduce**

**Expected behavior**

Either:
* Remove/hide this button when a column is collapsed
* Open/show the column when the button is clicked to open the settings

Not sure which is best yet… probably the later as it allows quicker access to the settings.

**Screenshots**

Normal state:  
<img width="225" alt="image" src="https://user-images.githubusercontent.com/1763364/121038833-e2e8a100-c7b0-11eb-8cd2-ec7724b47d68.png">

After clicking the "Settings" buttons in the 6th column:  
<img width="209" alt="image" src="https://user-images.githubusercontent.com/1763364/121039071-10cde580-c7b1-11eb-9c80-711dfbcfc7eb.png">

Behavior is the same on all types of column, it seems.

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Firefox
 - Version: 89.0

**Additional context**

**Comment by eramdam** [comment]
Good point, will be fixed in the next release

**Comment by eramdam** [comment]
Fixed in [4.3.0](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.0)!
