### ISSUE TITLE
Cannot download media 

### ISSUE THREAD

**Issue by wynnsyt** [eramdam/BetterTweetDeck#631]
**Describe the bug**
After enabling "Download media," clicking the download button does not do anything. No download is initiated.

**To Reproduce**
1. Go to BTD settings
2. Enable "Download media"
3. Find a tweet with an image and click the download button
4. Nothing happens

**Expected behavior**
The image is downloaded.

**Screenshots**
![Screen Shot 2021-06-07 at 12 41 16 PM](https://user-images.githubusercontent.com/2130881/121058293-2d0c5b00-c78e-11eb-9e58-ff8108cedf0d.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Firefox 89.0
 - BTD 4.1.1 

**Additional context**
- Clicking the button seems to trigger a TypeError in console (see screenshot above).
- I have tried disabling all extensions except BTD. 
- BTD is able to download media in Safari.
- "Copy links to media" seems to be working properly.

**Comment by eramdam** [comment]
It works fine for me on Firefox 89.0 as well 😕

**Comment by eramdam** [comment]
@wynnsyt does it still happen with 4.2.0?

**Comment by wynnsyt** [comment]
Now at 4.2.1 and it still happens.

**Comment by eramdam** [comment]
Do you have an adblocker/Ghostery-like extension enabled on TweetDeck? Do you use a tab container?

**Comment by wynnsyt** [comment]
I have tried again disabling all my extensions but the issue persists.
I never use tab container.

**Comment by eramdam** [comment]
Are you still experiencing this? I still can't reproduce and I have no idea what could be going on, probably something off with your configuration somehow? 😕

**Comment by wynnsyt** [comment]
I guess it must be something on my side then.

**Comment by mikelei8291** [comment]
Hi, I just installed the extension and tried to use the download button, but got the exact same error message shown in the dev console, and no file was downloaded.

![screenshot](https://user-images.githubusercontent.com/9620335/152495976-f8fe8764-d06d-4589-99b2-1289ee554d55.png)

I clicked the download button multiple times, and each time I clicked a new error message would appear.

**System info:**

- OS: Windows 10
- Browser: Firefox 97.0b3
- BTD Version: 4.7.3
