### ISSUE TITLE
Empty card space in columns with media hidden

### ISSUE THREAD

**Issue by xPaw** [eramdam/BetterTweetDeck#636]
**Describe the bug**
There is now `min-height` on cards in columns with media hidden, so there's an empty space since there is no card to load.
Looks like it was introduced by #616

**To Reproduce**
1. Set column to Media hidden

**Expected behavior**
No empty space

**Screenshots**
![image](https://user-images.githubusercontent.com/613331/121899981-96134600-cd2d-11eb-8b7c-70c6ed19b1a8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome 91
 - Version [e.g. 22] 4.2.1

**Additional context**

**Comment by eramdam** [comment]
Good catch, it will be fixed in the next release.

**Comment by eramdam** [comment]
Should be fixed in [4.3.0](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.0)
