### ISSUE TITLE
Port to Microsoft Edge

### ISSUE THREAD

**Issue by Revod** [eramdam/BetterTweetDeck#64]
Here are the news about the tools to port the extension to Microsoft Edge Browser: http://mspoweruser.com/microsofts-new-tool-lets-developers-convert-their-chrome-extensions-to-edge-extensions/

**Comment by eramdam** [comment]
Okay so I tried to run the extension on Edge and here are the things that need to be addressed to have a functional port:

- [ ] Make a different `manifest.json` file with the keys (look at the MSFT example one)
- [ ] See if the different events between the injected script and the content script actually work
- [ ] Improve the build so it's easier to build on Windows (right now it's a mess)
- [ ] `chrome.runtime.sendMessage/onMessage` just doesn't work atm from content scripts. I used that to get the settings but it looks like I can actually just query `chrome.storage` to do that
- [ ] `window.postMessage` from the inject script seems to trigger an error, I'm not sure yet about that

**Comment by eramdam** [comment]
Update on the progress: I managed to use [Microsoft Edge Extensions Toolkit](https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb) to have a working version of BTD on Microsoft Edge. However there are still some issues that I think will need for me to wait:

- The only `content_security_policy` value supported by Edge is the default one, and that breaks /a lot/ of things, cf: https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/supported-manifest-keys/
- All the requests with `fetch()` for thumbnails are triggering a CORS error whereas the ones using XmlHttpRequest work perfectly (somehow..)

Anyone able to help is more than welcome to do so, get in touch so we can progress on this.

**Comment by eramdam** [comment]
Closing this in favor of multiple issues under a milestone https://github.com/eramdam/BetterTweetDeck/milestone/4
