### ISSUE TITLE
 Full width multi-column view

### ISSUE THREAD

**Issue by oilpooh** [eramdam/BetterTweetDeck#640]
**Describe the solution you'd like**
 Full width multi-column view

**Describe alternatives you've considered**

Use this https://userstyles.org/styles/101095/tweetdeck-full-width-multi-column-view

css code but it will invalidate Display single images with their original aspect ratio

And pictures cannot be downloaded directly by right-clicking

Many thanks

**Comment by eramdam** [comment]
First of all, this kind of layout sounds very niche so I'm not too keen on making it a feature.
Second of all I'm not sure I understand the issue re: the aspect ratio? When I try it seems to work 🤷 
![Screen Shot 2021-06-22 at 8 56 45 PM](https://user-images.githubusercontent.com/1409924/123033293-60f59c00-d39c-11eb-902f-c853cf870a7e.png)

**Comment by eramdam** [comment]
However, if the issue is that the height of single images is too small (by default it's capped at 50% of the viewport height), you can add the following CSS snippet

```css
:root {
    --btd-max-og-ratio-height: 100vh;
}
```
