### ISSUE TITLE
Notification Volume setting

### ISSUE THREAD

**Issue by RangePup** [eramdam/BetterTweetDeck#643]
**Is your feature request related to a problem? Please describe.**
The notification chime is very loud and high pitched, in my opinion.

**Describe the solution you'd like**
A setting to change the notification volume.

**Describe alternatives you've considered**
The only solutions I can think of involve muting the tab entirely, or turning down the volume for all of Chrome.

**Additional context**
N/A

**Comment by eramdam** [comment]
Hum, it'd be tricky to design an UI around it because the way TweetDeck does it is using a hidden `<audio>` element. 

But you could use an userscript like this to adjust that

```js
// ==UserScript==
// @name        Notification volume - tweetdeck.twitter.com
// @namespace   Violentmonkey Scripts
// @match       https://tweetdeck.twitter.com/
// @grant       none
// @run-at      document-end
// @version     1.0
// @author      -
// @description 6/17/2021, 7:09:36 PM
// ==/UserScript==


const audioElement = document.querySelector('audio#update-sound');

if (audioElement) {
// https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume
  audioElement.volume = 0.5;
}
```
