### ISSUE TITLE
“Disable the tweet button until all images have a description” is erratic

### ISSUE THREAD

**Issue by emilazy** [eramdam/BetterTweetDeck#645]
**Describe the bug**
I (almost always?) have to disable the option to require descriptions to be able to post with an image even after filling out a description. Honestly, I’m not sure exactly the circumstances in which the behaviours I’ve noticed arise, but it never fully works properly; other times the Tweet button has started out enabled but the “All images require a description!” message stays even after filling them out. (Unfortunately I didn’t try actually posting a tweet after observing that behaviour and I can’t reproduce it now.)

**To Reproduce**
1. Enable “Disable the tweet button until all images have a description”
2. Start to compose a tweet
3. Attach an image
4. Fill out its description
5. Notice that posting is still disabled

**Expected behavior**
After filling out the image description, the Tweet button should be enabled, and the error message should disappear.

**Screenshots**
<img width="258" alt="A screenshot of the TweetDeck compose UI with an image, its filled-out description, a greyed out Tweet button, and the error ‘All images require a description!’" src="https://user-images.githubusercontent.com/18535642/124832117-12d3c180-df74-11eb-9651-65ab2eb55bb1.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari 14.1.1 (16611.2.7.1.4)
 - Version: 4.3.0

**Comment by Athanasius** [comment]
I just ran into this as well.  The first time I'd tried to tweet with an image it correctly stopped me initially, but then after I added the description the button stayed disabled.

I eventually got the tweet out after toggling the option off, saving the new settings *and* reloading the tab.

**Comment by eramdam** [comment]
I made a build with a fix for Firefox, let me know if it helps. I can make a quick build for Safari if you want.

[better_tweetdeck-21.9711.94.48-an+fx.xpi.zip](https://github.com/eramdam/BetterTweetDeck/files/6797298/better_tweetdeck-21.9711.94.48-an%2Bfx.xpi.zip)

**Comment by eramdam** [comment]
Should be fixed in 4.3.2 https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.2
