### ISSUE TITLE
Accent color is not honored in "Show more" links

### ISSUE THREAD

**Issue by lisardggY** [eramdam/BetterTweetDeck#646]
**Describe the bug**
When selecting a different accent color from the Settings->Themes menu, the "Show more" link for long threads is shown in the original blue, and not in the accent color.

**To Reproduce**
1. Go to Settings -> Themes
2. Select Dark Theme and Green Accent color.
3. In the timeline, find a threat with >10 responses and go into conversation view.
4. See link blue.

**Expected behavior**
Link should be green.

**Screenshots**
![image](https://user-images.githubusercontent.com/555329/125196112-355e2700-e261-11eb-849d-826c6f110657.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
- Version: User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Additional context**

**Comment by eramdam** [comment]
Will be fixed in the next release!

**Comment by eramdam** [comment]
Fixed in 4.3.2 https://github.com/eramdam/BetterTweetDeck/releases/tag/4.3.2
