### ISSUE TITLE
add surveys

### ISSUE THREAD

**Issue by HerrSammyDE** [eramdam/BetterTweetDeck#647]
**Is your feature request related to a problem? Please describe.**
Unfortunately, I have not yet found the function to create polls via Better Tweetdeck for Twitter.

**Describe the solution you'd like**
I would like to be able to create polls for tweets via Better Tweetdeck

**Describe alternatives you've considered**
Real alternatives except to use Twitter itself I unfortunately do not have, so I wish the whole thing in Better Tweetdeck as an update!

**Additional context**
-

**Comment by eramdam** [comment]
Polls are gated behind a private API so I can't easily interact with them. Besides, TweetDeck Preview will have that feature whenever it gets released to everybody so I'm not willing to spend time on code I'll have to discard eventually 😅 
https://twitter.com/Eramdam/status/1417517675618521095
