### ISSUE TITLE
The thumb of the vertical scrollbar of the first column only is working

### ISSUE THREAD

**Issue by f6fvy** [eramdam/BetterTweetDeck#649]
Scrolling the column with the thumb of the vertical scroll bar works only for the first column. It doesn't work for the other columns.

1. Click on the thumb of a vertical scroll bar, except the first column
2. Hold and try to scroll up or down
3. Nothing happens

The column should scroll up or down.

The mouse wheel and the up/down arrow buttons are working normally.

 - OS: Win7-32
 - Browser  Firefox
 - Version 90.0

**Comment by eramdam** [comment]
I just tried inside a Windows 10 VM (I don't have a copy of Windows 7 and it's an unsupported OS at this point) and it works just fine 🤷
