### ISSUE TITLE
Default Twitter "Like" icon animation instead of the TweetDeck one

### ISSUE THREAD

**Issue by mechanette** [eramdam/BetterTweetDeck#65]
So you might have noticed that the regular Twitter website and TweetDeck have different icons / icon animations sometimes.
The only thing that's done better in the regular Twitter is the Like button animation. It's much more awesome that the bland TD one.

There's an option to replace Like button with old Stars in BTD v3, so maybe it's also possible to change the Like icon animation somehow?

**Comment by eramdam** [comment]
I guess it _would be_ possible but if they didn't bother adding such a complex animation there is probably a reason. I will see how feasible it is but it sounds pretty annoying to implement, I have other bigger things to work on :/
