### ISSUE TITLE
"Share on Tweetdeck" doesnt include page title with page link

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#651]
**Describe the bug**
I'm guessing it's a bug. "Share on TweetDeck" doesn't sent page title with page link to tweet composer if no text on the page is selected, as it used to do. 

**Expected behavior**
If part of the text of shared page isn't selected, page title is shared with the page link.

**Desktop (please complete the following information):**
 - Win10 x64
 - Firefox 
 - 90.0 (64bit)

**Comment by eramdam** [comment]
@plissken1138 go in `about:addons`, under Better TweetDeck, then check the "Permissions" tab and make sure the "access browser tabs" permission is enabled. The next release should properly handle this case and request the permission as needed but in the meantime this is a workaround.

**Comment by plissken1138** [comment]
thumbs up!
