### ISSUE TITLE
Support for Firefox ESR?

### ISSUE THREAD

**Issue by hrw** [eramdam/BetterTweetDeck#655]
**Describe the bug**

Due to several reasons I am stuck with Firefox ESR (78.12.0 now). Last BTD version for it was 4.1.1 and newer ones require newer Firefox.

**To Reproduce**
1. Run Firefox ESR
2. try to install latest BTD

**Expected behavior**

Extension installs fine.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/185508/126783618-2465e7c5-90ab-49c2-9117-41cfe113c5fc.png)

**Desktop (please complete the following information):**
 - OS: Debian 'bullseye'
 - Browser: Firefox 
 - Version: 78.12.0esr

**Comment by eramdam** [comment]
Hum, I can't promise anything because I rely on many modern JS features and I have no idea whether or not they work fine on Firefox 78, I'll have to look into it.

**Comment by eramdam** [comment]
@hrw I have a build that should work on Firefox ESR. I quickly went through all the features and I didn't notice anything obvious but I'd be curious to hear your feedback. Could you try the attached build for a day or so and report back?
It _should_ install without any issues given that it has been signed by Mozilla. Don't pay attention to the weird version number 😁 

[better_tweetdeck-21.9726.12.43-an+fx.xpi.zip](https://github.com/eramdam/BetterTweetDeck/files/6874846/better_tweetdeck-21.9726.12.43-an%2Bfx.xpi.zip)

**Comment by hrw** [comment]
It installed fine, had to remove 4.1.1 I used previously. Reconfigured and will use and report.

So far feels like normal, working version.

**Comment by eramdam** [comment]
@hrw how did it go?

**Comment by hrw** [comment]
I did not observed any problems with ESR version. Works great.

**Comment by eramdam** [comment]
Great! I'll push the build to everyone later this week then! 😁

**Comment by eramdam** [comment]
Fixed in 4.4.0 https://github.com/eramdam/BetterTweetDeck/releases/tag/4.4.0

**Comment by hrw** [comment]
Thanks!
