### ISSUE TITLE
BetterTweetDeck Russian translation

### ISSUE THREAD

**Issue by ashed** [eramdam/BetterTweetDeck#656]
[Better-TweetDeck-ru-messages.zip](https://github.com/eramdam/BetterTweetDeck/files/6872054/Better-TweetDeck-ru-messages.zip)

BetterTweetDeck has no Russian translation
I translate BetterTweetDeck to Russian.

Add it to upstream, please

**Comment by eramdam** [comment]
Please use Crowdin for that https://crowdin.com/project/better-tweetdeck

Thanks.

**Comment by ashed** [comment]
Done
