### ISSUE TITLE
"</3" in tweet ends in "&lt;/3" after re-draft

### ISSUE THREAD

**Issue by WhereTheTimeWent** [eramdam/BetterTweetDeck#658]
**Describe the bug**
If a tweet contains "</3" and one clicks on "Re-draft", the "</3" is gone and there's `&lt;/3` instead.

**To Reproduce**
1. Post a tweet that contains "</3".
2. Click on "Re-draft" in the tweet menu of that tweet.

**Expected behavior**
I should still be able to express my broken heart after I've done a typo and used an amazing feature that saves me a lot of time.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 20H2
 - Browser: Brave (Chromium)
 - Version: 1.27.108 / Chromium: 92.0.4515.107
 - BTD version: 4.3.2

**Comment by eramdam** [comment]
Will be fixed in the next release (should be released by EOW)

**Comment by eramdam** [comment]
Fixed in 4.4.0 https://github.com/eramdam/BetterTweetDeck/releases/tag/4.4.0
