### ISSUE TITLE
Unselect "tweet action" buttons after pressing

### ISSUE THREAD

**Issue by johnkernke** [eramdam/BetterTweetDeck#66]
On chrome, once you press any of the tweet action buttons, they remain "selected" and will show the info text if you tab away and come back (eg "Like from <account>"). This becomes a slight issue when the tweet scrolls off the page, the browser adds a scrollbar for the entire page to show this info text for the button.

Unselecting the tweet action buttons after use would solve this issue.

**Comment by eramdam** [comment]
Is this really a Better TweetDeck issue tho? I feel like it's more a general TweetDeck/Chrome issue?

**Comment by johnkernke** [comment]
Sure that's an issue with Tweetdeck / Chrome, but wouldn't it be nice to make Tweetdeck better? :grinning:

**Comment by eramdam** [comment]
Sure, but I prefer to focus on other things before fixing minor stuff like that 😛
