### ISSUE TITLE
[Feature] Mark notifications shown in BetterTweetDeck as read ("elsewhere")

### ISSUE THREAD

**Issue by m-ueberall** [eramdam/BetterTweetDeck#662]
**Is your feature request related to a problem? Please describe.**
If you open `tweetdeck.twitter.com` and new tweets/interactions are visible in the "Notifications" column, they're not instantly marked as read. Once you, e.g., open `twitter.com` in another tab, you see the same notifications still marked as "new/unread". (Not sure whether this also applies to the app since I don't use the latter.)

**Describe the solution you'd like**
It would be nice to be able to specify that all tweets shown in the "Notifications" column are to be instantly marked as read as long as said column isn't minimized/removed.

**Comment by eramdam** [comment]
If I understand correctly, TweetDeck and Twitter have separate read states, so I'm not sure there's much I can do against that 😕
