### ISSUE TITLE
Add a faster "like" menu at accounts with linked accounts connected on it

### ISSUE THREAD

**Issue by flinterwood** [eramdam/BetterTweetDeck#664]
When we have a connected account and it shows a tweet, it could show us the like menu when we click at the "like" button to decide faster what account this "like" is going for, instead of clicking on the 3 dots and going for the "like from accounts" button. It would be faster for both situations (trying to like from original account or from linked account)

**Comment by eramdam** [comment]
Is that what you want? Because it's already there 😅 
![image](https://user-images.githubusercontent.com/1409924/129456954-31833be5-aef6-4e8a-8a9f-bdc00388d5a2.png)

**Comment by flinterwood** [comment]
yes! exactly! but it should have an option to enable it just when trying to like tweets showed by the linked account like its activity column, not every time

**Comment by eramdam** [comment]
> yes! exactly! but it should have an option to enable it just when trying to like tweets showed by the linked account like its activity column, not every time

Do you want to enable this only for specific accounts? That's what the field below the option is for 😅

**Comment by flinterwood** [comment]
wow that's it! sorry, some options are hard to me to understand what is there for lol

**Comment by eramdam** [comment]
No worries 😁  It just means I need to make this clearer somehow 😛
