### ISSUE TITLE
Allow to optionally name searches, for column titles that represent the _purpose_ of the search

### ISSUE THREAD

**Issue by rfkat** [eramdam/BetterTweetDeck#665]
**Is your feature request related to a problem? Please describe.**

Right now, the start of the search criteria is used as the column header. It's more helpful to have a column title that reflects the _purpose_ of the search.

**Describe the solution you'd like**

Add a virtual field that allows to specify a name for that search, and if a name was set, display the name only, wherever possible.

**Describe alternatives you've considered**

There is no workaround here, since the search currently _is_ the title.

**Additional context**
-

**Comment by eramdam** [comment]
TweetDeck Preview will have a similar feature so I'd rather wait for its general availability instead of spending time on a feature that will be made obsolete 😅 
https://twitter.com/Eramdam/status/1417515910424764419
