### ISSUE TITLE
Allow only requiring image descriptions in public tweets, non DMs

### ISSUE THREAD

**Issue by noamross** [eramdam/BetterTweetDeck#666]
**Is your feature request related to a problem? Please describe.**

I would like to be able to require tweet descriptions in my public tweets, but not require them in DMs.  It's useful for promoting accessibility to require this of oneself for public tweets, but it's not needed for private conversation.

**Describe the solution you'd like**

A sub-option to the checkbox under "Tweet Composer" options, saying "Disable the tweet button until all images have a description for DMs as well", that is unchecked by default.

**Comment by eramdam** [comment]
Fixed in 4.4.1, it makes the DM behavior opt-in 😄
