### ISSUE TITLE
fast retweet button separated from retweet with comment

### ISSUE THREAD

**Issue by flinterwood** [eramdam/BetterTweetDeck#667]
Could you create this fast retweet button? Should be similiar to the "hold shift to reload column". When we hold the shift key and move the mouse cursor over the retweet button, it would become another retweet button which would instantly retweet the tweet without asking if we want to retweet with comment

**Comment by eramdam** [comment]
Sounds like https://github.com/eramdam/BetterTweetDeck/issues/575
