### ISSUE TITLE
Clear button doesn't remember the last clear.

### ISSUE THREAD

**Issue by Luiggigom** [eramdam/BetterTweetDeck#668]
**Describe the bug**
When I clear the column it deletes the tweets and works correctly, but after a refresh it shows the same tweets that were cleared before.

**To Reproduce**
1. Watch a column
2.  Clear the column.
3. Reload the page.
4. See error of a column still showing the tweets from before.

**Expected behavior**
When I clear a column it saves the time from when I last cleared the column, then It will only show when I reload the page tweets since the last clear.

**Screenshots**
Non-applicable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 92

**Additional context**
No additional cotext.

**Comment by eramdam** [comment]
I haven't been able to reproduce 😕 
Does it still happen to you?

**Comment by Luiggigom** [comment]
Yes, but It's a twitter bug. Searching around I saw that the only way to solve it is to delete and create the column again. And that did it.

I might do another thread but as a feature to "reset" a column if keeps happening.
Thanks.

**Comment by richardm1** [comment]
Confirming this is a Twitter bug.  "Bare" TweetDeck (without a browser plugin) has the same issue.
