### ISSUE TITLE
Preview for ArtStation

### ISSUE THREAD

**Issue by Revod** [eramdam/BetterTweetDeck#67]
Hope to see in the next version support to preview of [ArtStation](https://www.artstation.com)

**Comment by eramdam** [comment]
I feel like they're not allowing that at all :/ https://www.reddit.com/r/Enhancement/comments/3o4pa3/feature_request_add_inline_image_viewer_support/

**Comment by Revod** [comment]
oh, thanks :/ :disappointed:
