### ISSUE TITLE
extension not working anymore

### ISSUE THREAD

**Issue by andycjw** [eramdam/BetterTweetDeck#672]
found this error in console, did anyone else have the same problem?

Uncaught Error: There are no constructors to search through!
    at i.findConstructor (chrome-extension://micblkellenpbfapmcpcfhcoeohhnpob/build/inject.js:2)
    at chrome-extension://micblkellenpbfapmcpcfhcoeohhnpob/build/inject.js:48
    at chrome-extension://micblkellenpbfapmcpcfhcoeohhnpob/build/inject.js:48
    at chrome-extension://micblkellenpbfapmcpcfhcoeohhnpob/build/inject.js:48

**Comment by andycjw** [comment]
turns out it's caused by conflicting extension, closing this

**Comment by eramdam** [comment]
@andycjw What was the conflicting extension? This would be useful to know for future issues 😁
