### ISSUE TITLE
Using milliseconds in date style does not work

### ISSUE THREAD

**Issue by yustier** [eramdam/BetterTweetDeck#674]
**Describe the bug**
If S, SSS, or u are used in custom date format, they are displayed in actual tweet as 0 or 000, not the correct time.

**To Reproduce**
1. Go to 'BTD Settings'
2. Click on 'Tweets display'
3. Set Date format to Custom and use the token S, SSS, or u in the format.
4. Save and reload TweetDeck
5. See timeline

**Expected behavior**
The part where S, SSS, or u are used in the date format should display correct tweeted time.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1 (Build 19043.1165)
 - Browser: Chrome 64bit Version 93.0.4577.63
 - Version: 4.4.0

**Comment by eramdam** [comment]
Unfortunately, this is "expected". It seems like the `created` timestamps only have up to a second of precision so displaying milliseconds will always show 0 😕 I don't know if it's true on Twitter's API side but it's true within TweetDeck's own data model.

**Comment by ciffelia** [comment]
It is actually possible get tweet timestamps with milliseconds precision, because recent tweet IDs (called snowflake) are based on precise timestamps. #367

**Comment by eramdam** [comment]
Oh, you're right. I completely forgot about this 😅 Will try to incorporate the work from that PR into the codebase.

**Comment by eramdam** [comment]
I ported @key-moon's implementation into v4 and it will be available in the next release 🙇
