### ISSUE TITLE
Follow from all of my accounts

### ISSUE THREAD

**Issue by NightshadeTrooper** [eramdam/BetterTweetDeck#675]
Hello, it would be great if there was the possibility to follow someone with all my accounts, since there is already a "Follow From" function, but it restarts every time I run this, I would be very grateful for such a thing.

**Comment by eramdam** [comment]
The mechanism that closes the "Follow from" dialog after one action is an older "anti-spam" measure put in place by TweetDeck, so working around that would technically violate TweetDeck's ToS so I'm not risking doing that. Sorry 😅
