### ISSUE TITLE
Boards à la Hootsuite

### ISSUE THREAD

**Issue by meduselchen** [eramdam/BetterTweetDeck#678]
Maybe I haven't found the right setting yet, but I would like to separate my columns by topics/projects. 

I find this well implemented in Hootsuite with the boards function, which then display the desired streams / columns. See this Screenshot: https://i.imgur.com/nVTwA5f.png

Would that be possible with BTD?

**Comment by eramdam** [comment]
Adding that would require a lot of work 😅 And [TweetDeck Preview has a similar feature](https://twitter.com/Eramdam/status/1417511007992238086) so I'm not really willing to work on something that will be obsolete whenever Preview becomes generally available 😁
