### ISSUE TITLE
Enlarge interaction buttons

### ISSUE THREAD

**Issue by Thex-PiedDroit** [eramdam/BetterTweetDeck#682]
**Is your feature request related to a problem? Please describe.**
Hi! I would like to suggest making the interaction buttons wider, as they are currently set to have a hitbox based on the text (current amount of retweets, then a space before the retweet icon, for example), which often makes it very difficult to click, as it requires a good amount of precision, and if a number changes before we click, it can result in clicking on the tweet itself instead.
![image](https://user-images.githubusercontent.com/8873598/135918623-83cdeaf8-e1a1-466f-935a-edede7cbe5c4.png)

**Describe the solution you'd like**
I would love hitboxes that encapsulate the interaction buttons in one easily clickable, and fairly unchanging rectangle instead, to make it easier to click.
![image](https://user-images.githubusercontent.com/8873598/135918868-ee3fa123-8a41-436e-b626-3552cbf11340.png)

**Comment by eramdam** [comment]
I'm weary about adding this as a feature both because it's "niche" and because it might break automatism from users. However, you can fix it by adding the following bit of Custom CSS:

```css
.tweet-action-item {
display: flex;
}
```

**Comment by Thex-PiedDroit** [comment]
Ah, wonderful, thanks a lot!
