### ISSUE TITLE
Pop Out Video in Tweet View

### ISSUE THREAD

**Issue by wynnsyt** [eramdam/BetterTweetDeck#683]
**Is your feature request related to a problem? Please describe.**
Currently, clicking on a video in my timeline creates a "pop out" view of the video, just like clicking on an image. The video plays at the center of the page.
However, clicking a video in a tweet view (after clicking on a tweet with video), it only plays inside the specific column, which depending on its aspect ratio, could be too small to enjoy. 
This can be quite frustrating with a thread of tweets containing videos.

**Describe the solution you'd like**
There could be a button to place the video at the center of the page, instead of playing the video inside the column.

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshots show the video playing in the column and at the center of the page. Note the huge difference in size.

![Screen Shot 2021-10-05 at 14 55 57](https://user-images.githubusercontent.com/2130881/136085691-682a1d65-4d39-4cfd-b40c-2c4aa542c426.png)
![Screen Shot 2021-10-05 at 14 55 46](https://user-images.githubusercontent.com/2130881/136085708-99e17d1d-8ba6-410b-a05e-ea243d438d14.png)

**Comment by eramdam** [comment]
I'm going to take a wild guess and assume you're using Firefox? If so, you can just use the Picture-in-Picture feature.

https://user-images.githubusercontent.com/1409924/136108107-deebf1c2-1caf-4b92-a533-1c8e465a6e1e.mov
