### ISSUE TITLE
Not showing all cards

### ISSUE THREAD

**Issue by xircon** [eramdam/BetterTweetDeck#686]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1316691/137133880-ad0511d0-ce55-4520-a8c4-92384022357b.png)

BBC works most of the time but Love Rugby League tweets never display the card.  Above is a screenshot of tweetdeck in a sidebar in Vivaldi and the actual tweet in twitter.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
Above
**Desktop (please complete the following information):**
Endeavour OS
Vivaldi-snapshot
4.3.2439.41-1 

:edit: Appears to be Twitter for Advertisers

![image](https://user-images.githubusercontent.com/1316691/137137618-03f53209-332a-4455-99f9-a88211ca5d92.png)
![image](https://user-images.githubusercontent.com/1316691/137137723-feaee85a-2d98-4899-8bac-27014857fb62.png)

**Comment by eduardomps** [comment]
@eramdam I didn't lknow if I should open a new issue or just add to this one, so here it goes: 
there's a minor inconvenience when there are multiple images in a card from Twitter for Advertisers, when (in the timeline) you click the arrow to next/previous image it also goes to the tweet view

![image](https://user-images.githubusercontent.com/1429383/139676106-1e1332a5-6e31-495a-b50f-0caba265fd7d.png)
![image](https://user-images.githubusercontent.com/1429383/139676171-9a38dd15-ab8b-4d1a-8545-e91db6d0ad6e.png)

if you click to go back to home, the second image in the card is shown, as if the click event is propagating more than it should,

**Comment by eramdam** [comment]
@eduardomps should be fixed in 4.5.0! https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.0

**Comment by eduardomps** [comment]
@eramdam updated here, fixed indeed, thanks!
