### ISSUE TITLE
Compose box in direct messages

### ISSUE THREAD

**Issue by callhermaxie** [eramdam/BetterTweetDeck#694]
I've been using better tweetdeck since ever and lately I've been missing this feature. I think it'd be good if the complete compose box (emojis, gifs etc) showed in reply to a direct message instead of the "simple" version.

Also, if there's any way to change the height of the messages/tweets.

English is not my first language so I apologize for any mistakes.
And thank you in advance for your attention!

**Comment by eugenioperea** [comment]
I agree with this! Especially the part about the height of the message window. It sort of increases dynamically as one types and it sometimes obscures the last line you're typing.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
