### ISSUE TITLE
add confirmation to the 'block' Tweet action

### ISSUE THREAD

**Issue by roycewilliams** [eramdam/BetterTweetDeck#695]
**Is your feature request related to a problem? Please describe.**
It is too easy to accidentally block someone.

**Describe the solution you'd like**
A confirmation dialog/popup ("Are you sure you want to block @[user]?")

**Describe alternatives you've considered**
Only alternative I know of is to leave the action disabled entirely.

**Additional context**
Especially important since accidentally blocking someone will force them to unfollow you - so you have to request action from the other party after accidentally blocking them. :D

**Comment by eramdam** [comment]
I agree it's not ideal...however, the feature was requested by folks who need to actually quickly block/mute folks 😅 
So maybe you could disable it and rely on the block action in the tweet menu instead?
![image](https://user-images.githubusercontent.com/1409924/139573952-6679e1f4-8383-4d1c-9940-d51a3c4af07c.png)

**Comment by roycewilliams** [comment]
Oh, that's a use case I hadn't thought of. But my particular problem is that the top level button is too easy to accidentally click. If there was a separate option for users to want that button to require confirmation, then both interests could be served?

**Comment by eramdam** [comment]
Fixed in [4.5.2](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.2)!
