### ISSUE TITLE
Extract "any pronouns" from bio

### ISSUE THREAD

**Issue by asshuka** [eramdam/BetterTweetDeck#697]
The new pronoun feature doesn't seem to catch "any pronouns" yet, I was wondering if it could be included?
Thank you so much for adding this feature BTW, it's much much appreciated <3

**Comment by eramdam** [comment]
It could be, I just need to be extremely precise and strict about the patterns because obviously matching `any` by itself will lead to a lot of false positives 😁 
I need to look at it.

**Comment by eramdam** [comment]
Started adding support for this in https://github.com/eramdam/BetterTweetDeck/commit/3fadd82b49fea095e615ec7b6a17738466b0ad0b

For now, it matches:
- `any pronouns` 
- `pronouns: any`
and shows `any pronouns` in the tweet columns.

It also tries to match `any/all`. Let me know if there are more patterns I should be aware of 😁

**Comment by eramdam** [comment]
Fixed in [4.5.2](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.2)!
