### ISSUE TITLE
Twitter for Advertisers carousel cards graphical issue

### ISSUE THREAD

**Issue by AlexzanDev** [eramdam/BetterTweetDeck#702]
**Describe the bug**
I use TweetDeck (and BTD) on a vertical screen. A lot of times the cards in the Twitter for Advertisers carousel are not shown horizontally but vertically, covering other tweets and creating a bad glitch. Without touching anything the problem applies to the second card of the carousel only (See screenshot 1). However, if you interact with the carousel, the problem worsens (Screenshot 2). By refreshing TweetDeck everything is fine.

**To Reproduce**

1. Use TweetDeck on a vertical screen
2. Wait for a carousel tweet with cards to be shown

**Expected behavior**
Cards should be displayed correctly in the carousel (horizontally).

**Screenshots**
![image](https://user-images.githubusercontent.com/35893655/140541894-33670d21-a44a-4399-9c39-a6c254dd5cc3.png)

![image](https://user-images.githubusercontent.com/35893655/140542189-385df306-e5f5-4b17-abb3-010dcc78652a.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: Chrome version is 95, while the BTD version is the latest, 4.5.0

**Comment by eramdam** [comment]
Fixed in [4.5.2](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.2)!

**Comment by AlexzanDev** [comment]
Thank you!
