### ISSUE TITLE
Video trimmer feature

### ISSUE THREAD

**Issue by dnestico** [eramdam/BetterTweetDeck#704]
As someone who uses twitter to  upload a lot of media and also uses Tweetdeck as my main twitter client, a video trimmer would be an amazing feature.

Basically you upload your video > An edit button shows > When you click edit button it opens like a card popup that lets you trim the video > Done.

Hopefully you can add this.

**Comment by eramdam** [comment]
I can't, it would require a big amount of work to ultimately try to mimick something that Twitter Web already has and that (I assume) TweetDeck Preview has/will have.

**Comment by dnestico** [comment]
Yea I figured it would take a lot of work, I really hope Tweetdeck gets it, but haven't seen so far yet.
