### ISSUE TITLE
Remove confirmation for "mute" and "block" tweet actions

### ISSUE THREAD

**Issue by msewell** [eramdam/BetterTweetDeck#707]
#695 added a confirmation dialog to the "mute" and "block" tweet actions.

As someone who has been using these actions liberally for a long time, and in fact has considered the speed at which users can be muted or blocked one of Better TweetDeck's most useful features, I would really, really like the old no-confirmation behavior back, or alternatively a setting to toggle the appearance of the confirmation dialog for these actions.

**Comment by eramdam** [comment]
I'll add a setting in the next release. Until then you quickly confirm the confirmation with the Enter key since it's a native dialog.

**Comment by eramdam** [comment]
Will be in the next release
