### ISSUE TITLE
Problem with vertical videos

### ISSUE THREAD

**Issue by netocavalcanti** [eramdam/BetterTweetDeck#709]
It depends on the size of the Tweetdeck window. 
The video is "croped" on the bottom and the top.
It don't show the media controls.

**To Reproduce**
1. find a vertical video and hit Play
2.  the video don't show the top and the bottom

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/agk6Tpi)

**Desktop (please complete the following information):**

- OS: Windows 10 
- Chrome v.95.0.4638.69

**Additional context**
If I resize the TD windows to make it more like the video, the video shows correctly.
Sorry if I could not explain it better. My english is limited.

**Comment by eramdam** [comment]
Will be fixed in the next release (see above PR)
