### ISSUE TITLE
Separate Page Per Column View or Multiple Pages with different columns

### ISSUE THREAD

**Issue by RibShark** [eramdam/BetterTweetDeck#710]
**Is your feature request related to a problem? Please describe.**
I have Autism and having multiple columns on one page is visually overwhelming for me. I would love to take advantage of the features TweetDeck + BTD offer but without being able to have different pages for Home/Notifications/Messages etc this isn't possible for me.

**Describe the solution you'd like**
I would like the ability to have multiple pages/tabs on the left navigation, each with a different column in (or a selection of any chosen columns maybe would also work), similar to how the main twitter works. Ideally these would also be able to be centred on the page (though this could be done with CSS).

**Describe alternatives you've considered**
I have tried using CSS to achieve this but it is beyond my skill level and probably better done without just using pure CSS.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
