### ISSUE TITLE
Optional Download Media button in fullscreen media viewer

### ISSUE THREAD

**Issue by DragoonAethis** [eramdam/BetterTweetDeck#711]
I use the fullscreen media viewer feature and Download Media action in tweet actions. It would be nice to have the same button available directly in the fullscreen viewer. Artist's interpretation:

![image](https://user-images.githubusercontent.com/1546665/141322948-435c9b3e-0dab-4857-a6a2-9490d5c36ca8.png)

**Comment by eramdam** [comment]
Will be fixed in next release

**Comment by eramdam** [comment]
Fixed in https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.3

**Comment by DragoonAethis** [comment]
Works, thanks!
