### ISSUE TITLE
Re-draft does not keep image descriptions

### ISSUE THREAD

**Issue by malfynnction** [eramdam/BetterTweetDeck#712]
**Describe the bug**
Re-drafting a tweet with images that have alt text will lose the alt text

**To Reproduce**

1. Compose a tweet with images
2. Add alt text to the images
3. Send tweet
4. Re-draft the tweet

**Expected behavior**
The images in the re-drafted tweet should keep their original descriptions

**Comment by eramdam** [comment]
Will be in the next release (probably next week)

**Comment by malfynnction** [comment]
Oh wow, that was quick. Thank you! (And thanks for all the work you do!)
