### ISSUE TITLE
Content warning false positive?

### ISSUE THREAD

**Issue by AlexzanDev** [eramdam/BetterTweetDeck#719]
**Describe the bug**
The content warning feature has been activated on a tweet that doesn't have any possible trigger. The original tweet can be found [here](https://twitter.com/802NOWONAIR/status/1459579823320608768) and is in Japanese.
I also noticed that every tweet from this account is flagged with a CW button.

**To Reproduce**

1. View the tweet linked up here on TweetDeck.

**Expected behavior**
Tweet should be displayed normally. This might help for other false positives.

**Screenshots**
![image](https://user-images.githubusercontent.com/35893655/141654235-4f1ba753-35d0-4d35-bf79-55bc124312f8.png)
![image](https://user-images.githubusercontent.com/35893655/141654240-cc2e2b31-65ad-4d3f-9361-c20c0a3b53cc.png)

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version: Chrome version is 95, while the BTD version is the latest, 4.5.2

**Comment by AlexzanDev** [comment]
I think that the square brackets are causing this issue. Tested it myself with and without brackets.

![image](https://user-images.githubusercontent.com/35893655/141654381-264d0e53-611c-4406-acbc-af67620a8061.png)

**Comment by eramdam** [comment]
Well, the thing is that the CW detection can now detect patterns like `[food]￼￼`, and unfortunately that catches things like this :/ 
I'd have to think about a better way to handle that but I'm honestly not sure how to do it.

**Comment by AlexzanDev** [comment]
@eramdam I thought so. And that makes sense since a lot of people write whatever they want as a CW, it's impossible to filter everything. I mean, maybe not? But it wouldn't be worth it for sure.

**Comment by eramdam** [comment]
> @eramdam I thought so. And that makes sense since a lot of people write whatever they want as a CW, it's impossible to filter everything. I mean, maybe not? But it wouldn't be worth it for sure.

Yeah exactly. I could maybe try to filter it out if the content of the brackets looks like a date but then it could also match some legitimate stuff as well so idk 😅
