### ISSUE TITLE
Expand content warning system to hide spoilers

### ISSUE THREAD

**Issue by diaphauma** [eramdam/BetterTweetDeck#720]
While not as important as content/trigger warning, it would be nice for BTD to be able to hide the text of tweets that begin with a spoiler warning. For instance, in the following tweet
"spoilers: roman history
holy shit caesar died"
the second line would be automatically hidden.
An alternative solution would be to let users have a "semi mute" feature, where tweets that contain a certain phrase (in this example "roman history" would be hidden behind a warning such as "this tweet contains your hidden phrase "roman history", would you still like to see it?"

**Comment by eramdam** [comment]
I tried implementing that at some point, the main problem was that there isn't a good pattern widely used for spoilers that I could find 😕  
Some folks do stuff like 
```
// foobar spoilers
```
and it gets very tricky to detect.

That said I like the idea of the "semi mute" concept, I could look into it!

**Comment by eramdam** [comment]
For reference, the patterns I've tried to support, which look harmless but ended up triggering way too often https://github.com/eramdam/BetterTweetDeck/pull/692/files#diff-88a3041b2c48b7cb603bff1a71acea3212fc09bfc89244f36baf5a28732768c8R31-R47

**Comment by methom** [comment]
+1 for the semi-mute feature. 
I just came here to report a similar idea which I called "treat hashtag as spoiler".
