### ISSUE TITLE
Display a notification whenever an update is available

### ISSUE THREAD

**Issue by O-Xian** [eramdam/BetterTweetDeck#721]
**Is your feature request related to a problem? Please describe.**
With Firefox, the extension is unloaded/reloaded when updated, which breaks some features (especially gif button and :emoticon : shortcut in the editor. It only works again after reloading Tweetdeck.

**Describe the solution you'd like**
ACK the issue in the documentation and advise to disable auto-update, BUT, display a notification whenever an updated is available so nothing breaks and users can update at a convenient time.

**Describe alternatives you've considered**
Disabling auto-update might not be deemed wise, in that case the extension should be able to continue to work even under this specific reload constraint.

**Additional context**
Windows 10 21H1, Firefox 94.0.1, reproducible on two computers (same environments).

Thanks!

**Comment by eramdam** [comment]
Fixed in 4.6.0!

**Comment by O-Xian** [comment]
Thanks for the quick fix @eramdam! 
However, it seems something's wrong. I have only seen 1 notification ever since 4.6.0 on two computers (same OS, same Firefox 94.0.2).
From that sample, it seems it's a short lived notification. If I'm not in front of the screen at that time, then I will miss it. Would it be possible to have something that stays displayed until ACK (such as the blue notification with the link to changelog)?

**Comment by eramdam** [comment]
The notification prompts you to reload TweetDeck tabs so it will only show if you have those tabs opened. The purpose of the notification is to prevent TweetDeck from being in a broken state because your browser updated+reloaded the extension.

Hope that clears it out.

**Comment by O-Xian** [comment]
But I do have a Tweetdeck open, it's one of my pinned tabs. I experienced that broken state today with 4.6.3: haven't seen the notification and guessed an update was on its way because the shortcodes wouldn't work.
