### ISSUE TITLE
Show emoticon button when replying / Prevent Emoticon window from being cut off in popout mode

### ISSUE THREAD

**Issue by Clydefrosch22** [eramdam/BetterTweetDeck#723]
The emoticon selection window is clearly designed for when you start a new individual tweet, fitting just below the textbox area and a typical 1080p displays lower border (with taskbar enabled)

But if you use popout to reply to someone else or quote retweet, the textbox area gets pushed down and if you go for an emoticon then, part of it is cut off (depending how long the tweet you reply to is) making it hard to select anything. You also can't scroll the popout area while the emoticon selection is opened, so you have to close it, scroll the popout area and then reopen and find your emoticons again.
Please make the emoticon selection screen pop out to the side or something and make it longer too if possible.

Alternatively, allow access to the emoticon selection without using popout mode.

**Comment by eramdam** [comment]
Fixed in 4.6.0!
