### ISSUE TITLE
Custom column size not working?

### ISSUE THREAD

**Issue by Grimtendo** [eramdam/BetterTweetDeck#724]
**Describe the bug**
My column size is completely dependent on how many columns are onscreen for some reason, is this intentional? For example, having only 1 column takes up the entire screen's width, and adding a second column will split it into two halves, etc. Even after changing the "Use a custom width for columns" setting, there's no difference.

**Expected behavior**
Changing the custom column width under General settings should make column sizes static.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Latest Chrome and BTD

**Additional context**
I've also tried using the following CSS snippet to make columns different sizes from each other, with no results. I may be using it wrong, but regardless, I'm having this issue with and without the custom CSS.
>.js-column.column:nth-child(1) {
  width: 500px;
}

**Comment by eramdam** [comment]
Can you say what value your tried to put in the setting?

**Comment by Grimtendo** [comment]
I've tried multiple. 250, 500, 900, etc. to look for any noticeable difference.

**Comment by eramdam** [comment]
@Grimtendo what unit did you use exactly? Because if you put `200` without any unit there it won't work very well, you're supposed to use a CSS unit so more something like `200px`.

**Comment by Grimtendo** [comment]
Sorry for not being clear but yes I've been using units like "500px"

**Comment by eramdam** [comment]
I don't know why it would happen, inputting a specific width works just fine on my end 😕 
![image](https://user-images.githubusercontent.com/1409924/142668962-3fc65b48-8915-4e25-8a3e-62089af6636f.png)
