### ISSUE TITLE
Copy links to media copies [object Object]

### ISSUE THREAD

**Issue by 9c23a5** [eramdam/BetterTweetDeck#725]
**Describe the bug**
After last update, the "Copy links to media" button on tweet actions doesn't work, it copies `[object Object]` instead of the actual link(s). Additionally, the same behavior is present when clicking the same Copy links to media button on the recently updated image expansion option (Display fullscreen images option enabled)

**To Reproduce**

1. Click on "Copy links to media" button on any tweet
2. Paste it anywhere
3. Get `[object Object]` (or multiple times if multiple pictures in the tweet)

**Expected behavior**
The content of the clipboard should be a link to the tweet's picture/video

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Chrome 96
- Version [e.g. 22] 4.5.4

**Comment by eramdam** [comment]
Will be fixed in the next release

**Comment by eramdam** [comment]
Fixed in 4.6.0!
