### ISSUE TITLE
Images/"content boxes" for the same tweet in different columns not always visible

### ISSUE THREAD

**Issue by m-ueberall** [eramdam/BetterTweetDeck#726]
**Describe the bug**
If you see the same tweet in multiple columns (for instance, if you retweet it after it occurs in the "Activity" column), attached images and/or "content boxes" will not always be displayed in both columns. (As far as I remember, they always appear in the "Home" column, but it could work the other way round, so maybe it's the copies that are never affected from missing "attachments".)
Sometimes, Twitter does not modify a tweet to include "content boxes" for a hyperlink right away, but as you can see below, in this case the tweet is already an hour old and has already been seen by numerous others (i.e., post-processing should have taken place).

**To Reproduce**
Retweet tweets from the" Activity" column not showing "attachments" until you see that a tweet "gains" these in the "Home" column.

**Expected behavior**
All images/"content boxes" attached to a tweet should always be displayed.

**Screenshot**
![btd_noimg](https://user-images.githubusercontent.com/625934/142730504-77052cb1-66d6-4445-8ff7-f1117be719a0.png)
_(Note that the "heart state" is not in sync, _but that's a different matter._)_

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome Version 96.0.4664.45 (Official Build) (64-Bit)
- BTD Version: 4.5.4

**Comment by eramdam** [comment]
It's possible that TweetDeck's code responsible to render cards (the link previews) doesn't handle activity items very well so this is why it doesn't work 😕 Unfortunately I can't tweak that code myself so I can't do much.
