### ISSUE TITLE
Pronoun display picks up false positives if any of the standard 3 subject pronouns are followed by any special character, even if not followed by another pronoun

### ISSUE THREAD

**Issue by kittymmeow** [eramdam/BetterTweetDeck#727]
Any use of "they", "he", or "she" followed by a special character (including numbers) in a user's bio or location gets picked up by the pronoun display, regardless of context, even when the special character is not a / or | and is not followed by another pronoun. A bio solely containing a sentence like "`he's here`" and no other text will output the user's pronoun display as "he/him". 

If the character is not / or | but is still followed by another pronoun, it will only output the first pronoun used. A bio of "they!she" will only output "they/them" in the pronoun display.

Because the bio has precedence over the location for pronoun detection, this can also result in a false positive detected from a user's bio overriding an actual pronoun set detected from the location field. A bio containing "`he's here`" and a location containing "`they/them`" will only show "he/him" in the pronoun display.

This does not occur for the subject pronouns from neopronoun sets, even common ones that have a dedicated page on pronouns.page like it or xe.

The most common source of false positives on this will probably be contractions using apostrophes like the example above.

**Comment by eramdam** [comment]
Yup. I was made aware of this one a few days ago, I have [a fix](https://github.com/eramdam/BetterTweetDeck/commit/9c8cce6c9dff92ce4b6ff2195ac213525de5cb2d) on the main which as far as I can tell should fix the behavior you're describing. It will be in the next release.

**Comment by eramdam** [comment]
Fixed in 4.6.0!
