### ISSUE TITLE
Hide already seen tweets?

### ISSUE THREAD

**Issue by mshaler** [eramdam/BetterTweetDeck#729]
I would like to hide tweets I've already seen like RSS/Reddit.  

Is this possible with BetterTweetDeck?

**Comment by eramdam** [comment]
There should be a "hide this tweet" item in the the tweets' menu. Would that work?
![image](https://user-images.githubusercontent.com/1409924/143295694-db159679-140a-4c73-9e6e-b5af00607d51.png)

**Comment by y0himba** [comment]
Pretty sure the OP means to hide Tweets that have been read automatically to clean up the column. Sort of how read messages are collapsed, 

Maybe collapse and dim the read tweets?

**Comment by eramdam** [comment]
Oooh. Hum, yeah, I don't know about that... There's not really a good way for me to even store what tweet you read and hiding a potentially high amount of tweets is bound to trigger some weird bugs in the UI code that renders tweets in columns 😅

**Comment by y0himba** [comment]
I kind of thought it would be intensive to hide them or dim them.  What
about a marker like the markers that show the user has loved or retweeted?
Label it read?

**Comment by busywhistling** [comment]
> There should be a "hide this tweet" item in the the tweets' menu. Would that work?
Is it possible to add it to the one-click action row at the bottom of tweets? If not, can this functionality be considered for addition? Thanks for the great work btw.

**Comment by eramdam** [comment]
Closing in favor of https://github.com/eramdam/BetterTweetDeck/issues/746
