### ISSUE TITLE
Thumbnail after hashtag if available

### ISSUE THREAD

**Issue by Killmax** [eramdam/BetterTweetDeck#73]
I think it could be a cool feature to add the little picture just after a hashtag if available, like that : 

![](http://i.imgur.com/i1i1gwm.png)

**Comment by eramdam** [comment]
Hum, would have to check but I'm pretty sure there is no easy way of fetching that since it's a Twitter Web/Mobile only feature. I will see but indeed it would be a nice thing to add as well!

**Comment by eramdam** [comment]
@Killmax Could you link one or some tweets with those kind of hashtags so I can see what I can do?

**Comment by Killmax** [comment]
This one : https://twitter.com/ittfworld/status/763755318807519232?s=09

But I think these pictures are just for an event not always.

**Comment by eramdam** [comment]
I did some research and there is no easy to guess / fetch the corresponding emojis for a hashtags. I'm closing this.
