### ISSUE TITLE
Add Bookmark column

### ISSUE THREAD

**Issue by diego10arg** [eramdam/BetterTweetDeck#730]
Would it be possible to add a new column with the Bookmark content (https://twitter.com/i/bookmarks) ?

It would also be nice to be able to Add/Remove tweets from bookmarks from the Action Menu.

Thanks in advance!

**Comment by eramdam** [comment]
Unfortunately, I can't. 
There isn't any good way for me to create a new type of columns and the bookmarks stuff is behind a private API anyway 😕.
Same issue for the add/remove from the action menu.
