### ISSUE TITLE
Show Spaces links as tweet cards

### ISSUE THREAD

**Issue by plissken1138** [eramdam/BetterTweetDeck#733]
Twitter Spaces links are now shown just as txt links in Tweetdeck, 
if it's possible it would be good to have them as tweet cards,
perhaps with the title (and similar gradient background, if I can be picky) as on twitter.com

![Tvitter Spaces card](https://i.imgur.com/wrgFsIH.png)

**Comment by eramdam** [comment]
Do you have a link to a tweet with a spaces card? I'd need to check how the data model looks

**Comment by plissken1138** [comment]
this was link to the space https://twitter.com/i/spaces/1yoKMWnbvVzJQ
it's now ended, and I don't see any active spaces atm...
if it's of any help you search this link it will give you tweets that have it

**Comment by eramdam** [comment]
So I checked and, as I expected, the TweetDeck code I'm triggering in order to render cards doesn't have anything for Spaces and I doubt it will anytime soon. I'll take a look for good measure but I doubt that I can easily patch that part of TweetDeck to support a new kind of card 😕

**Comment by plissken1138** [comment]
Thanks for checking it out. I had card in mind mainly because it displays the Space title, but it doesn't necessarily have to be card so maybe an easier solution can be just to make TD display a Space link as (or with) the title of the Space?

**Comment by eramdam** [comment]
So I went and checked and there's no useful data from the card that I could use somehow so I can't really fix this. I guess there might be a private API endpoint to get informations about a specific space but I don't know about it 😞 

```
{
  "name": "3691233323:audiospace",
  "url": "https://t.co/cLHn2TNtYv",
  "card_type_url": "http://card-type-url-is-deprecated.invalid",
  "binding_values": {
    "id": {
      "type": "STRING",
      "string_value": "1kvJpAVoLjaxE"
    },
    "card_url": {
      "type": "STRING",
      "string_value": "https://t.co/cLHn2TNtYv",
      "scribe_key": "card_url"
    }
  },
  "card_platform": {
    "platform": {
      "device": {
        "name": "Swift",
        "version": "13"
      },
      "audience": {
        "name": "production",
        "bucket": null
      }
    }
  }
}

```
