### ISSUE TITLE
Content warnings should hide images in columns with "large media" setting

### ISSUE THREAD

**Issue by passcod** [eramdam/BetterTweetDeck#734]
When media is small or medium, it behaves as embedded to the tweet, so the content warning folding behaves correctly:

![image](https://user-images.githubusercontent.com/155787/144052290-5ad1d880-075c-44bc-b844-b02cba02b70a.png)

But when the "large media" setting is turned on for the column, the media is displayed "outside" the tweet, so only the text is folded:

![image](https://user-images.githubusercontent.com/155787/144052856-39dc4f89-c329-4356-a196-86cfee2ef6b9.png)

(screenshot deliberately cut off for obvious reasons)

If a fold is impractical, perhaps a blur could be added, e.g.

![image](https://user-images.githubusercontent.com/155787/144053026-081d3694-4e0f-4a3f-855a-da2873f3d4c7.png)

**Comment by eramdam** [comment]
Oh dear, yep 😅 Will look into this (or @pixeldesu if you're up for it)

**Comment by eramdam** [comment]
Fixed in 4.6.2!

**Comment by passcod** [comment]
You're the best! 🎉
