### ISSUE TITLE
Better Tweetdeck 4.6.0 eliminates avatar transparency

### ISSUE THREAD

**Issue by LukasThyWalls** [eramdam/BetterTweetDeck#735]
Hello!

**Describe the bug**
I have an avatar with transparent background (don't ask me how i uploaded it, i think i use Twidere or other app to do it, because with twitter config it add a color in background). I can still see it in Twitter web and other apps.

Before 4.6.0, Tweetdeck showed the avatar with transparent background. With 4.6.0, it shows a white background (maybe is the background color of the original avatar image, but it doesn't appear in Twitter web or Tweetdeck 4.5.4).

I downgraded from 4.6.0 to 4.5.4, and the transparent background is there, so is something 4.6.0 did.

Self-explanatory with the screenshots below.

**To Reproduce**

1. You need an Twitter avatar with transparent background (idk now, but in the past is not as easy as upload it with twitter because it kills the transparency). I have one in [http://twitter.com/LukasThyWalls](http://twitter.com/LukasThyWalls) so can be tested with that in a column.
2. With Better Tweetdeck 4.6.0, there is a background color instead of a transparency.
3. Downgrading to 4.5.4, the avatar background is transparent, as always was (and it's in Twitter web and other apps).

**Expected behavior**
Maintain the transparency in the avatar!

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1467366/144100030-62b24919-58cf-49c0-8482-e4dc80866bc9.png)   ![imagen](https://user-images.githubusercontent.com/1467366/144100084-ba7841ba-3a31-47c8-9b0d-e6e805056c73.png)

**Desktop (please complete the following information):**

- OS: Windows 10 21H1 64bits
- Browser: Firefox 94.0.2 64bits
- Better Tweetdeck Version: 4.6.0

**Additional context**
None, thanks for the addon, it's a must have!

**Comment by eramdam** [comment]
That's on purpose. Given that Twitter's NFT integration thing will show hexagon-shaped avatars, I wanted to show them as well, but then it meant that avatars that fake the hexagon by using the alpha channel could be confused for actual NFT-profile avatars... so I added the background to prevent that confusion 😅

**Comment by eramdam** [comment]
I realize that I apply that CSS even if you don't enable the mute nft setting thing... I'll make it so that style doesn't apply if you don't enable the setting. In the meantime, you can use this bit of CSS

```
img.avatar:not(.avatar--hexagone) {
  background-color: transparent !important;
}
```

**Comment by LukasThyWalls** [comment]
With that CSS the transparency is there (with or without the setting), so if this not interferes with the setting is the way to go.

However, as an opinion, if you add a white background to those avatars, they would still look squares with a dark theme background although they have an hexagon shape in a first look, although i suppose that would work when you are using the light theme (but then the background setting would do nothing noticiable). It should be better to add a border to the shape with an opposite color of the background, for example (i saw similar things done with only CSS), but i don't know if it can be done in this case with the avatars in tweetdeck.

But thinking about the preview coming one day and carry with the wind a lot or all of the work, i would not invest a lot of time in this detail, also being this what's it's this about, for me could they have the shape (excuse me) of a t*rd. But better not to talk about it, let's not wake up the ghosts.

Thanks eramdam!

**Comment by LukasThyWalls** [comment]
@eramdam a quick question, should i keep the custom css or it is going to be added to next version? Thanks!

**Comment by eramdam** [comment]
You should keep it. I feel like I'll need to think about this a little more because applying the style conditionally is trickier than I thought 😅

**Comment by LukasThyWalls** [comment]
> You should keep it. I feel like I'll need to think about this a little more because applying the style conditionally is trickier than I thought sweat_smile

No worries, thanks!
