### ISSUE TITLE
Tweet from "Twitter for advertisers" with *video* not rendering media

### ISSUE THREAD

**Issue by eduardomps** [eramdam/BetterTweetDeck#737]
**Describe the bug**
This issue is a follow-up on this one, already fixed - https://github.com/eramdam/BetterTweetDeck/issues/686
Basically, any tweet from the source Twitter for Advertisers renders correctly if the cards are one or more images. BUT for videos, YT links for instance, they only render the tweet's text.

**To Reproduce**
open any tweet with a Twitter for Advertisers source where the card contains a video
**Expected behavior**
The video card rendering (with legend) correctly, as it does with images.

**Screenshots**
Original tweet
![image](https://user-images.githubusercontent.com/1429383/144635476-9708e2c6-ec88-47da-9438-0d43bf90ac59.png)
in tweetdeck tweet view/timeline view
![image](https://user-images.githubusercontent.com/1429383/144635517-3b108755-32ca-43ac-bcbb-20e0f68d1111.png)
![image](https://user-images.githubusercontent.com/1429383/144636431-3c1ff1cc-e345-453c-b00b-7c543ca935f3.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser FF Dev Edition
- Version: BTD 4.6.3

**Additional context**
N/A

**Comment by eramdam** [comment]
I had to disable those kinds of cards because there were all kinds of rendering issues when those tried to show a carousel and I can't unfortunately tell the difference from "outside" 😞

**Comment by eduardomps** [comment]
oh well, I know the feeling.
maybe it can be nice to put up a "known issues" list so, at least, we can know why some things are not working and if they even _can_ be fixed with some work, a lot of work, or not at all currently
