### ISSUE TITLE
Verified account badge prevents mutual badge from showing

### ISSUE THREAD

**Issue by TheOpponent** [eramdam/BetterTweetDeck#740]
**Describe the bug**
When the verified badge and mutual badge are enabled at the same time, only the verified badge shows. This occurs in all places where the badge would appear.

**To Reproduce**

1. Enable "Show verified badges" and "Show badges on mutuals (you follow them and they follow you)".
2. Have a verified account you follow also follow you, and view any of their tweets. The verified badge appears but not the selected mutual badge. This applies to any option for the mutual badge graphic.

**Expected behavior**
The mutual badge appears next to the verified badge.

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Vivaldi
- Version: 3.8.2259.42 (Stable channel) (64-bit)

**Additional context**
n/a

**Comment by eramdam** [comment]
Fixed in 4.7.0!
