### ISSUE TITLE
Require confirmation on Re-draft

### ISSUE THREAD

**Issue by slgraham** [eramdam/BetterTweetDeck#741]
**Is your feature request related to a problem? Please describe.**
Re-draft is a cool feature, but its too easy to accidentally delete a tweet by accidentally clicking the option in the tweet menu
**Describe the solution you'd like**
Ideally, some kind of confirmation would be required before deleted the tweet in question.

Could even condition that confirmation on the presence of likes and/or comments on the tweet to be re-drafted, ie if there are above X likes, confirm before deleting.

**Describe alternatives you've considered**
Labeling the Re-draft option with more explicit language communicating that it deletes the tweet in question.

**Additional context**
n/a

**Comment by Clydefrosch22** [comment]
Random extra confirmations out of quick menues are rather irksome, but I guess the first time someone sees that function, people might believe this to be a traditional edit button.

If this is considered, I would beg for a [ ] Do not show this warning again checkbox though.

**Comment by eramdam** [comment]
Will be in the next release, alongside a setting and the confirmation will show up if/when the targeted tweet has had replies/RTs/likes.
