### ISSUE TITLE
Smaller image of links on tweets

### ISSUE THREAD

**Issue by diego10arg** [eramdam/BetterTweetDeck#742]
**Is your feature request related to a problem? Please describe.**
> Some tweets with links shows large images that take up too much screen state.

**Describe the solution you'd like**
 > I would like a setting to enforce auto-resize to "Small Media" as set up in my lists.

**Describe alternatives you've considered**
> Do not know CSS to change it myself.

**Additional context**
> How I like to see my tweets:
![image](https://user-images.githubusercontent.com/696076/146011341-5f218c84-1826-4002-98df-9465c4f68525.png)

(Original tweet link: https://twitter.com/JSiabaSerrate/status/1470751402674819074)

> How they are shown with large images in links:
![image](https://user-images.githubusercontent.com/696076/146011513-713ba35f-f4e7-4936-975a-a1dd450b2f20.png)

(Original tweet link: https://twitter.com/julianyosovitch/status/1470548440946024449)

Thanks in advance!
Diego

**Comment by eramdam** [comment]
I'm not sure what I understand what you want? 😅 
When I make a very large column and set the media size to "Small", it looks like what you want so I'm not sure I understand the issue 
![image](https://user-images.githubusercontent.com/1409924/147803285-593a0615-ad85-4ac3-98d4-873be29a4607.png)

**Comment by diego10arg** [comment]
Hi @eramdam, sorry for my delay to respond.

For some reason that I don't know, some tweets with **links** on it (like https://twitter.com/julianyosovitch/status/1470548440946024449) show a large image instead of a small one.

The difference I find between both tweets is that the first one (https://twitter.com/JSiabaSerrate/status/1470751402674819074) is a tweet with an attached image and the second one (https://twitter.com/julianyosovitch/status/1470548440946024449) is a tweet with a pasted link.

Would it be possible to resize the image shown on the tweets when it comes from a **link pasted on it**?

Hope you have a great year!

**Comment by eramdam** [comment]
Gotcha, will be fixed in the next release 
![image](https://user-images.githubusercontent.com/1409924/148142462-45db357f-29bc-421e-9d3e-9665c1a7e77d.png)

**Comment by eramdam** [comment]
Fixed in 4.7.0!
