### ISSUE TITLE
has the "download as gif" feature been removed?

### ISSUE THREAD

**Issue by mattstratton** [eramdam/BetterTweetDeck#744]
I believe this used to work (I know I used it!) but it seems to be gone, at least in Chrome?

**Comment by eramdam** [comment]
Yes. The feature was hard to maintain because the library I used ([gifshot](https://github.com/yahoo/gifshot)) hasn't been updated in a while and wasn't working reliably in a web extension context 😕 And this is on top of the fact that converting .mp4 files to .gif is always tricky/prone to errors 😞
