### ISSUE TITLE
Add option to hide all replies to a thread

### ISSUE THREAD

**Issue by ShadowJonathan** [eramdam/BetterTweetDeck#745]
#### Is your feature request related to a problem? Please describe.
When following a particular user mention, today I got someone abusing the mention of that user to gain hype and visibility. Subsequently, the feed was filled with nonsensical or useless replies to this tweet.

#### Describe the solution you'd like
Adding an ability to automatically hide replies to a tweet based on a source tweet.

#### Describe alternatives you've considered
https://github.com/eramdam/BetterTweetDeck/issues/746 could fix my problem for now, where i can quickly "shoot down" those replies as i spot them.

**Comment by eramdam** [comment]
Hum, the main thing is that it would work only on replies to a "root" tweet. Like, consider the following:

- Tweet A
   - Tweet B
      - Tweet D
         - Tweet E
   - Tweet C

Such a feature would only be able to catch B and C, but not D nor E.
But otherwise, I feel like it wouldn't be too complicated to implement.

**Comment by ShadowJonathan** [comment]
I think for the specific kind of problem im going for (rooting out bot replies, or popular tweets that arent relevant), removing B and C is alright, if i see a D, i could just go up one tweet and mute that once i see it, which is an order of magnitude less work already.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
