### ISSUE TITLE
Quick "hide tweet" button

### ISSUE THREAD

**Issue by ShadowJonathan** [eramdam/BetterTweetDeck#746]
#### Is your feature request related to a problem? Please describe.
Sometimes when going through my feed to scan what is interesting, I see "noise", tweets that dont matter to the feed, and i'd like to quickly remove them.

#### Describe the solution you'd like
Add a "hide" button next to one of these;
![image](https://user-images.githubusercontent.com/22740616/147096193-587e14b9-2fe0-48f0-9a21-c5c432f706bb.png)

**Comment by ShadowJonathan** [comment]
> There's an `hide tweet` item in a tweet's action menu. Would that work?

That does work the base usage, I'm just asking if such a button could be included in the "quick actions" menu, so that i can quickly go through a series of "spammy" tweets without having to hunt-and-peck the menu and the option each time.

**Comment by eramdam** [comment]
Makes sense. I'll just need to figure out what icon to put there because a `mute` icon would be redundant with the already-possible "mute author" button 😅

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
