### ISSUE TITLE
Display full date after 24h not working

### ISSUE THREAD

**Issue by johnkernke** [eramdam/BetterTweetDeck#75]
Pretty much the title. All the dates will remain as a relative date rather than swapping at 24 hours+. Using the "Absolute" date option does work, but having it set to "Relative" and the "Display full date after 24h" option ticked doesn't swap them.

**Comment by eramdam** [comment]
Hum, I actually never thought about this use-case, will fix it asap 😅

**Comment by eramdam** [comment]
@johnkernke what format do you think it should us in relative in 24h+ ? I'm curious.

**Comment by johnkernke** [comment]
Never really thought about that.

It would probably be best to have the user select what option they want for when the time goes over 24 hours, as users of different countries would be upset with 1 predefined choice. That way you could even have 2 different custom formats if you wished.

**Comment by eramdam** [comment]
Huum, that would add yet another setting then. I will see later, since in more than 3 years nobody every complained about that it can wait a little.
