### ISSUE TITLE
"Recent used hashtags" field in tweet composer panel

### ISSUE THREAD

**Issue by Explorare** [eramdam/BetterTweetDeck#750]
It would be great to have a field in tweet composer panel for recent used hashtags.

Detailed features:
1. Show recent used hashtags
2. Sort hashtags based on used counts, content
3. Add background to hashtags based on counts (optional)
4. Ability to pin / delete / ignore / add hashtags. This requires maintain a hashtag list locally.
5. Click the hashtag to add it to tweet content
6. Suggest related hashtag that are used together. Input a # and show suggest in transparent text, just like auto complete in IDE. This one is tricky, I think it can based on the similar counts, or set the relation manually? 

I need this feature for quick tweet compose related to live stream clips, which need to append many different hashtags for that streamer and content.

I do like to complete this feature and just send a pull request, but I'm just start reading the first chapter of _Eloquent JavaScript_, it may take me years to be able to finish this feature. 😅

**Comment by eramdam** [comment]
ICYMI: there's already a "keep tweeted hashtags" feature, it's a bit clunky but it's something already

**Comment by eramdam** [comment]
@Explorare does the existing feature I mention works for that use-case? If so, can I close the issue?

**Comment by eramdam** [comment]
Closing for now, feel free to re-open if the existing feature is not enough.
