### ISSUE TITLE
Notifications for one account not loading

### ISSUE THREAD

**Issue by omgitsraven** [eramdam/BetterTweetDeck#752]
**Describe the bug**
I've been using BTD for a few weeks now and had no problems until now, but as of this morning, the Notifications column for one of my accounts is stuck on 'Loading...', even though the notifications columns for my other accounts work fine.  Disabling BTD fixes the problem.

**To Reproduce**

1. Visit https://tweetdeck.twitter.com/ with BTD enabled.
2. My main account's notifications column never loads.
3. Disable the BTD add-on, and reload tweetdeck
4. The column loads normally.

**Desktop (please complete the following information):**

- Win10 Pro 19042
- Firefox 95.0.2
- BTD 4.7.0

**Additional context**
I've seen similar issues that were resolved by discovering and deleting strange mute filters, but there's nothing unusual in my mutes list (it's all things that I put there on purpose, that have been there for much longer than I've had this problem).

**Comment by eramdam** [comment]
I encountered that bug on my personal account yesterday and issued a fix on the newest nightly build. Can you try it and let me know if it fixes it for you as well?
[Better_TweetDeck_22.9107.96.93.xpi.zip](https://github.com/eramdam/BetterTweetDeck/files/7833605/Better_TweetDeck_22.9107.96.93.xpi.zip)

**Comment by omgitsraven** [comment]
The nightly works for me too, thank you!

**Comment by eramdam** [comment]
Should be fixed in 4.7.1
