### ISSUE TITLE
[bug] emoji shortcodes and emoji button broken

### ISSUE THREAD

**Issue by Wurzelmann** [eramdam/BetterTweetDeck#753]
**Describe the bug**
Inserting emojis via :shortcode: does not work any more and emoji button is missing from text box

**To Reproduce**

1. Write tweet/reply
2. type any shortcode for an emoji
3. Nothing happens

**Expected behavior**
Insert emojis via their shortcodes into message respectively using the emoji button to insert them

**Screenshots**
[no emoji search/button visible](https://i.imgur.com/jUvE20c.png)

**Desktop (please complete the following information):**

- OS: Debian sid
- Browser: Firefox 91.4.0esr (64-bit)
- Version BTD 4.7.0

**Additional context**
no additional context

**Comment by eramdam** [comment]
Are you sure the extension is actually enabled? Can you double check?

**Comment by eramdam** [comment]
Works fine on Firefox ESR 91 on macOS. I don't have a Debian system to test on unfortunately 
![image](https://user-images.githubusercontent.com/1409924/148692453-197669cf-b3b5-4023-82c9-9250a5128539.png)

**Comment by Wurzelmann** [comment]
> Are you sure the extension is actually enabled? Can you double check?

I should have specified in my first post: I double-checked whether the extension was enabled (it was), I even disabled and re-enabled it. I also specifically disabled the emoji-shortcode option, saved the preferences, reloaded Tweetdeck, re-enabled the search option, reloaded Tweetdeck. Nothing. It is just gone.

**Comment by eramdam** [comment]
I just published 4.7.1, which I believe should be live for Firefox now. Has it changed anything?

**Comment by Wurzelmann** [comment]
Unfortunately not... same behaviour as before. I did not install any new addons and the functionality was just gone. I am not seeing any errors in the console either, it's really strange...

**Comment by eramdam** [comment]
Are others feature working? Like the gif picker, the settings button, etc? Would help knowing that as to be able to pin point if the issue is isolated to the composer stuff or not.

**Comment by Wurzelmann** [comment]
Oh no, it WAS an error on my side, sorry! I tried to eliminate everything from my side, but after your 4.7.1 update, I tried a new session with another Twitter account it worked there. I then deleted all cookies and the cache for the site and it started working again. Sorry for the inconvenience, but I appreciate your quick answers, thank you!
