### ISSUE TITLE
Display name mutes not working

### ISSUE THREAD

**Issue by WizardShotTheFood** [eramdam/BetterTweetDeck#754]
**Describe the bug**
I have a filter that's supposed to mute anyone with ".eth" in their display name, but it's not muting anything.

**To Reproduce**

1. Go to Settings, Mute.
2. Choose "Display name (Regular Expression)" and attempt to mute "\.eth" (without the quotation marks).
3. Look at any given tweet where dipshits with .eth in their name are flooding the replies with their cultist idiocy.

**Expected behavior**
I don't have to see their nonsense.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 95.0.2

**Comment by eramdam** [comment]
The "." character in a regex is used to match any character, so you would actually mute things like "Seth", which is not what you want. Instead, you want to put `\.eth` 
![image](https://user-images.githubusercontent.com/1409924/148793792-f082b3db-8464-4ebc-b6ea-24ec09d62a20.png)

**Comment by WizardShotTheFood** [comment]
I did escape the period in the filter, and it's still not working. Either I typoed it when I opened the ticket or Github ate the backslash somehow.

![image](https://user-images.githubusercontent.com/4625609/148804407-291bf040-4db3-4ef9-b065-17a41f0eb799.png)

**Comment by eramdam** [comment]
Hum, weird, it works on my end. 
![image](https://user-images.githubusercontent.com/1409924/148805460-48061fde-c12a-45c3-9f64-d8c0b0a49d99.png)

That said I'm not 100% sure TweetDeck's muting runs on replies to a single tweet.

**Comment by WizardShotTheFood** [comment]
That might be the problem. If I just mute "eth" all of my tweets vanish from my notifications (as expected, given that my display name includes the phrase "eth deez nuts"), but I'm still visible when I check tweet replies.
