### ISSUE TITLE
Emojis missing after last update

### ISSUE THREAD

**Issue by rbruhn** [eramdam/BetterTweetDeck#755]
When tweeting or replying, the emoji icon to bring up the emojis is missing after the last update.

Open browser to Tweetdeck and click to reply or tweet.
No emoji menu to bring up emojis.

Expected behavior is to see the emoji menu to bring up the emojis you would like to select.

**Screenshots**
https://gyazo.com/686c037413a9d3e993b4dedfc8b02876

- OS: Windows 10
- Browser: Firefox
- Version 95.0.2

**Comment by eramdam** [comment]
Can you check if the workaround/troubleshooting done in https://github.com/eramdam/BetterTweetDeck/issues/753 help at all?

**Comment by rbruhn** [comment]
Clearing cache and cookies worked. Thank you.
