### ISSUE TITLE
Pressing ESC gets rid of emoji, gif and tweet availability pickers

### ISSUE THREAD

**Issue by egzn** [eramdam/BetterTweetDeck#757]
**Describe the bug**
When pressing the ESC key resets the tweet form to it's initial state, so the emoji picker, gif picker and tweet availability picker are not present until you close the "New Tweet" form and open it again.

**To Reproduce**

1. Go to the TweetDeck page
2. Check that all of those pickers are in the new tweet form
3. Press ESC key

**Expected behavior**
All pickers should be present at all time

**Screenshots**
Default tweet form
![imagen](https://user-images.githubusercontent.com/5099644/149121104-ad0e1375-247d-4ab0-b6f4-679beab55ccf.png)
Tweet form after pressing ESC
![imagen](https://user-images.githubusercontent.com/5099644/149121153-71dba372-cd13-46d2-9cf0-8462b50f2ef8.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 96.0

**Additional context**

**Comment by eramdam** [comment]
Seems like it happens only when using the `stay open` checkbox. I'll look into it.

**Comment by eramdam** [comment]
Note: apparently what happens is that TweetDeck clears out the DOM elements of the docker composer when this happens, despite the `Stay Open` checkbox being checked, which throws off my code that tries to detect whether or not the composer is open 😩 

I'll investigate more later today.

**Comment by egzn** [comment]
Hey! Sorry for the bit late heads-up! Installed the latest nightly, seems like it's working as it should now! Big thanks :D
