### ISSUE TITLE
Version for Firefox Android 

### ISSUE THREAD

**Issue by anoraktrend** [eramdam/BetterTweetDeck#758]
It'd be nice to have a version of this for Firefox Android but I can understand if it'll be a while before you consider it. It's not too big of a deal. My Android is my only device which I use often.

**Comment by ashifolfi** [comment]
I do want to mention that I installed it via the addon collection feature inside the debug menu and the only issue I had is being unable to actually hit save in preferences. I don't think it would be all that difficult to implement.

**Comment by eramdam** [comment]
I unfortunately don't have a good way to test the extension on Android so I can't really work on supporting it.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@eramdam, [Android-x86](https://www.android-x86.org/download.html) via [`virtualbox`](https://www.virtualbox.org/wiki/Downloads) easily provides [what you desire](https://github.com/eramdam/BetterTweetDeck/issues/758#issuecomment-1234852369:~:text=a%20good%20way%20to%20test%20the%20extension%20on%20android). Additionally, if you utilize Windows 10 or 11 as your primary operating-system, [the Windows Subsystem For Android](http://docs.microsoft.com/windows/android/wsa) allows perfect integration (installation and simultaneous utilization) of software packaged and compiled for Android into Windows.
