### ISSUE TITLE
Doesn't work at all in MS Edge

### ISSUE THREAD

**Issue by sillvva** [eramdam/BetterTweetDeck#759]
**Describe the bug**
The Microsoft Edge Add-on Store has no effect on tweetdeck.twitter.com

**To Reproduce**

1. I installed the extension through the Microsoft Edge Add-on Store
2. Customized the settings and hit save.
3. Open tweetdeck.twitter.com
4. See absolutely no change from before the extension was installed.

**Expected behavior**
The extension should work

**Screenshots**
![image](https://user-images.githubusercontent.com/5138384/150445518-5285c469-59ec-43e5-8644-139f52cb9a1e.png)
![image](https://user-images.githubusercontent.com/5138384/150445719-15e7abe3-a1f4-4787-9522-02a5add180ab.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Microsoft Edge
- Version: 97

**Comment by eramdam** [comment]
The extension doesn't support TweetDeck Preview yet. See https://github.com/eramdam/BetterTweetDeck/issues/653
