### ISSUE TITLE
Autoplay Videos in Feed/Fullscreen

### ISSUE THREAD

**Issue by unfamiliartunes** [eramdam/BetterTweetDeck#763]
One of my current gripes with TweetDeck is that it doesn't autoplay videos in the same way that Twitter does. Is there a way to change that? Thank you!

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
