### ISSUE TITLE
Add translate button to "Tweet actions to add"

### ISSUE THREAD

**Issue by Balentay** [eramdam/BetterTweetDeck#764]
It can get tedious navigating through menus or clicking on tweets to translate tweets, especially if you follow lots of people who speak different languages.  Adding a quick translate button would be quite convenient, much like the quick block and mute buttons

**Comment by peterquirk** [comment]
I have a column of Ukrainian sources contained in a list. It would be really convenient to have a column-level auto-translate feature that activate the translation feature on all foreign-language tweets in the column.
