### ISSUE TITLE
Make back mouse button for back to button on each column.

### ISSUE THREAD

**Issue by anatawa12** [eramdam/BetterTweetDeck#770]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I press back button on mouse on tweetdeck because I expect to back the column however backs to the previously shown page (like chrome://newtab).

**Describe the solution you'd like**

Make the back button on the mouse to click 'Back to Home'.

**Describe alternatives you've considered**
I've made a script to prevent going back but I need to enter the script every time.
However, this doesn't work for newly created column.
Also I want the mouse button to click Back to Home button.

```js
Array.from(document.getElementsByClassName('js-column'))
    .forEach(element => element.addEventListener('mouseup', (e) => { 
        console.log(`mouseup event: ${e.button}`)
        if (e.button === 3) e.preventDefault()
    }))
```

**Comment by eramdam** [comment]
That feature would be a bit too niche/specific for a browser extension IMO. However you should be able to just add it yourself with an userscript using something like TamperMonkey, it should work just fine.
