### ISSUE TITLE
Highlighting search words

### ISSUE THREAD

**Issue by ShadowJonathan** [eramdam/BetterTweetDeck#771]
Often enough when i scroll through search feeds, i see a ton of irrelevant tweets, I can easily dismiss them by seeing the positioning of the words, or some words around it.

BTD could softly highlight these words in these tweets, helping me search better.

**Comment by eramdam** [comment]
I like the idea but I feel like to work properly, I would need to somehow implement a way to interpret Twitter's query language and... I have no idea if there's a premade way to do it? Because I'm not writing a search query parser myself 😂

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
