### ISSUE TITLE
Strict search

### ISSUE THREAD

**Issue by ShadowJonathan** [eramdam/BetterTweetDeck#772]
When i try to search for a domain ("riot.im"), I often get unrelated lossy results ("... im gonna riot, im gonna go crazy ...")

I'd like for BTD to be able to filter these results as they come in, to provide even better results from them.

**Comment by eramdam** [comment]
I don't think I can do much + this would add a bunch of complexities in a hot path of TweetDeck (loading/filtering tweets) so I'm not comfortable making that change, sorry!
