### ISSUE TITLE
Confirmation step breaks on Quote Retweets when "Disable the tweet button until all images have a description" is enabled.

### ISSUE THREAD

**Issue by cremullins** [eramdam/BetterTweetDeck#773]
When Quote Retweeting with "Disable the tweet button until all images have a description" and "Confirmation step" are enabled on a particular account, the Tweet button remains disabled even when the "Ready to tweet?" check box is checked.

This issue does not appear when Tweeting normally, only when Quote Retweeting (aka "Retweet with comment").

To reproduce:

1. Log into at least two Twitter accounts in TweetDeck with BTD installed. If you cannot reproduce this bug with two accounts, try logging into three.
2. On one account, enable "Confirmation step".
3. In BTD settings, enable "Disable the tweet button until all images have a description".
4. Go to Quote Retweet any tweet, with an image from the account with the confirmation step enabled, and add alt text to the image.
5. Check the "Ready to tweet?" box.
5. You will find that the Tweet button remains greyed out.

Obviously, the Tweet button should not remain greyed out - the expected behaviour is that the Tweet button should light up and allow you to Tweet the image with its description. ~~Only workaround at the moment is to switch off the confirmation step - but this results in loss of the image and its description once the Tweet pane closes, making it a time-consuming pain.~~ **EDIT:** Bizarrely, Ctrl+Enter still works, so this is clearly a GUI issue. The button is showing up as inactive, but TweetDeck itself is actually letting me post the image with a keyboard shortcut.

![image](https://user-images.githubusercontent.com/99048570/152598889-179f14d5-7fd4-490b-9534-83e7101a82d6.png)

This issue was discovered in Chrome Version 97.0.4692.99. Having updated Chrome to the latest release, Version 98.0.4758.82, it is still a problem, so I can confirm it's not an issue with my browser.

**Comment by eramdam** [comment]
Ah, great. I had caught that bug briefly on my end but wasn't attentive enough to be able to figure out repro steps. Thanks! I'll try to look into it 🙇‍♂️
