### ISSUE TITLE
Limited results after searching for a gif

### ISSUE THREAD

**Issue by sqwarlock** [eramdam/BetterTweetDeck#774]
**Description**
When searching for a gif in the compose pane, any text returns far fewer results when compared to the main Twitter search.

**Reproduce**
1. Start a new tweet or reply
2. Click **Gif**
3. Enter your search term
4. See four to five rows of results and no more

**Expected behavior**
Expect to see results that mirror those on the main Twitter gif search, including "endless" scrolling.

**Screenshots**
Twitter search:
![2022-02-09 09_57_58-Window](https://user-images.githubusercontent.com/19698281/153261713-043d9b84-6d45-4afb-b027-984c274b6607.png)
![2022-02-09 09_58_14-Window](https://user-images.githubusercontent.com/19698281/153261739-7799b8aa-ded5-47a0-96e9-004a2a06c827.png)
![2022-02-09 09_58_21-Window](https://user-images.githubusercontent.com/19698281/153261748-0b6017d6-e908-4791-87d3-e2ff5a4e6472.png)

BTD search:
![2022-02-09 09_58_33-TweetDeck — Mozilla Firefox](https://user-images.githubusercontent.com/19698281/153261808-260e8387-0834-4c5f-9ffa-a04937d07b18.png)
![2022-02-09 09_58_42-TweetDeck — Mozilla Firefox](https://user-images.githubusercontent.com/19698281/153261812-3a3d3e76-2ff0-4b95-9674-d23379c327e0.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 
- Version: 97.0 (64-bit)

**Comment by eramdam** [comment]
Will be fixed in the next release and will be available in the nightly build shortly. You can join the [Discord server](https://better.tw/discord) to get access to the nightly builds for Firefox 😄
