### ISSUE TITLE
Auto-hide media marked as sensitive for specific natures only

### ISSUE THREAD

**Issue by Thex-PiedDroit** [eramdam/BetterTweetDeck#776]
The new twitter "mark media as sensitive" feature allows posters to specify the nature of why the media is considered sensitive, such as "violence" or "nudity".

BTDeck already has an option to entirely bypass this feature on the reading end, but having the ability to specify which types to bypass or not would be extremely appreciated.
I imagine this as a set of checkmarks under this option, to choose which ones to apply it to:
![image](https://user-images.githubusercontent.com/8873598/153736177-7c86d395-d672-4079-b123-ac77077cc5e2.png)

Thanks a lot, i hope you have a wonderful day!

**Comment by eramdam** [comment]
Will be in the next release
