### ISSUE TITLE
Ability to hide tweets with "more than X hashtags"

### ISSUE THREAD

**Issue by DavidPyke** [eramdam/BetterTweetDeck#777]
**Is your feature request related to a problem? Please describe.**
I have a search I follow that occasionally is spammed with tweets with 10 or more hashtags.  They're annoying.

**Describe the solution you'd like**
I would like a setting where if a tweet has more than a settable amount of tags, it can be automatically hidden

**Describe alternatives you've considered**
tried to hide specific tags, but the number of variations was too high.

**Additional context**

**Comment by eramdam** [comment]
Will be in the next release!

**Comment by DavidPyke** [comment]
Thank you!

**Comment by DavidPyke** [comment]
Maybe I'm missing something but I updated to 4.8.1 and I can't see the setting anywhere.

**Comment by eramdam** [comment]
![image](https://user-images.githubusercontent.com/1409924/155077961-7ebb017e-a803-4ba4-b0be-1f777d726cc4.png)
![image](https://user-images.githubusercontent.com/1409924/155077986-b1b71f91-90bd-43ae-85be-93a26105d167.png)
![image](https://user-images.githubusercontent.com/1409924/155078024-5b5e9c06-80b7-4295-9a7e-a0f05eeee830.png)

**Comment by DavidPyke** [comment]
Okay, it must be a firefox thing as my options look nothing like that.

**Comment by eramdam** [comment]
These are the Tweetdeck settings, accessible under the ⚙️ > settings > mute
