### ISSUE TITLE
Full Browser Video View (Feature Request)

### ISSUE THREAD

**Issue by diego10arg** [eramdam/BetterTweetDeck#778]
Would it be possible to strech the overlay video to full browser size?

![image](https://user-images.githubusercontent.com/696076/153926713-eb514aa6-c754-4bc9-8e9e-30aa44201834.png)

To show like this? (Paint edit)

![image](https://user-images.githubusercontent.com/696076/153927043-f1618cf1-3fe8-449a-bab3-9f60827f1ac1.png)

Thanks in advance!

**Comment by eramdam** [comment]
If you use the `Display fullscreen images à la Twitter Web` setting, videos will also get enlarged to their maximum possible size. Try it and let me know 😄

**Comment by diego10arg** [comment]
Hi @eramdam 

I looks better with that option, but it would be nice if it is possible to enlarge it to use the whole browser (I am using 4k display with chrome using about 1920px height x 2160px width) and each list uses the full width.

**Display fullscreen images à la Twitter Web OFF**

![Screen 2](https://user-images.githubusercontent.com/696076/154083279-c7d500b0-e63b-4694-af1a-41a699c73c19.jpg)

**Display fullscreen images à la Twitter Web ON**

![Screen 1](https://user-images.githubusercontent.com/696076/154083354-8d15ce10-4cb7-4bfe-acdb-f5631ed59a73.jpg)

**Expected if possible**

![Screen 1](https://user-images.githubusercontent.com/696076/154083609-61006c9c-1b15-43a2-8a1d-391757144509.jpg)

**Comment by eramdam** [comment]
I used to have a bigger height/width but it was causing issues with vertical videos, you can paste the following CSS code in the `Custom CSS` part of the settings 

```css
[btd-modern-overlays="true"] .js-modal-panel .l-table .l-cell .js-media-native-video {
    max-height: 95vh !important;
    max-width: 95vw !important;
}
```
1vh/1vw represents 1/100th of the viewport's height and width respectively, so feel free to tinker with the values there

**Comment by diego10arg** [comment]
It does not seems to be working even when changing vh/vw to 99 or 100.
Maybe it depends on the video format?
Or browser zoom? (@125) 

Tried with Display fullscreen images à la Twitter Web **ON** and **OFF**
