### ISSUE TITLE
Muting NFT avatar users doesn't apply to retweets

### ISSUE THREAD

**Issue by raccube** [eramdam/BetterTweetDeck#780]
**Describe the bug**

**To Reproduce**

1. Enable "Mute accounts who use the NFT avatar integration (hexagon-shaped avatar)" setting
2. Find a tweet by a user with an NFT avatar.
3. Retweet it from another account.
4. See someone else retweet a tweet by a user with an NFT avatar on your main timeline.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6197148/153948047-87c04d93-14c8-400b-ba93-e76d0dfe27ff.png)
![image](https://user-images.githubusercontent.com/6197148/153948068-b090e985-3b68-47fa-b859-336de9fed378.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version 97

**Additional context**
_None._

**Comment by eramdam** [comment]
Will be fixed in the next release!
