### ISSUE TITLE
Search columns under specific accounts 

### ISSUE THREAD

**Issue by saryuken** [eramdam/BetterTweetDeck#783]
Is it possible to add a feature that allows you to open a search column with a specific account the same way you can have different accounts for notifications/timeline? I need to see search results under a certain hashtag but worry that I might miss some because they are muted/blocked from my main account.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
