### ISSUE TITLE
Capture and redirect the back button

### ISSUE THREAD

**Issue by Brickcaster** [eramdam/BetterTweetDeck#789]
**Is your feature request related to a problem? Please describe.**
It is frustrating to, after opening and reading a thread, click the back button on the browser and lose my place in the scroll.

**Describe the solution you'd like**
I would like the back browser button to perform the "back to home" action of the most recently interacted with column.

**Describe alternatives you've considered**
Alternate solution: Open a dialog asking for confirmation before leaving the page.
Power move: Back button takes current column to home or takes all columns to home.  If all columns are at home, instead launches a confirmation dialog before allowing the back browse action.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
