### ISSUE TITLE
Option: trim context actions

### ISSUE THREAD

**Issue by Brickcaster** [eramdam/BetterTweetDeck#790]
**Is your feature request related to a problem? Please describe.**
The context action menu ("..." button) has a lot of redundant and inoften used options. Actions such as follow, send DM add to list, etc may not be used often if at all by some users and even when removed from this list these actions have alternate routes to make them still possible without having to re-enable them. This could make the context menu more focused and easier to use.

**Describe the solution you'd like**
Add a block in Tweet Actions settings page for "Context menu ("...") Actions", with a checkbox for each action.  Checked by default, unchecking causes the option to be hidden.
"✅Embed this tweet"
"✅Copy link to this tweet"
"✅Share via direct message"
etc

**Describe alternatives you've considered**
Alternative solution: add more of these to tweet actions. "Copy link to this tweet" is the action I use the most and that is most important to me.  "Translate this tweet" would also be helpful.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
