### ISSUE TITLE
Hide/Ignore/Remove "Reactions" from DMs

### ISSUE THREAD

**Issue by taconomix** [eramdam/BetterTweetDeck#792]
**Is your feature request related to a problem? Please describe.**
I'm in a DM Group with ~30 people, and on Twitter.com it's fine, it just shows reaction counts below the message. But on Tweetdeck, each reaction shows as a new message that say "@xxxxx Reacted To <message> with <emoji>". If lots of people are reacting to a lot of messages, it makes it impossible to follow the conversation in tweetdeck. 

**Describe the solution you'd like**
Reaction "badges" (Not sure if that's the correct term) would be great, but honestly just the ability to hide the reactions would be amazing. 

**Describe alternatives you've considered**
I've tried using the muted words option in the column settings, and it stops the reactions from showing as notifications/new messages, but the actual chat still shows them when opened. 

**Additional context**
Screenshot attached for context. Someone read through a conversation and reacted to like 20 messages, It's really difficult to find the last thing actually said in the group.
![Screenshot from 2022-02-23 22-24-52](https://user-images.githubusercontent.com/69542501/155452445-ddd7b379-aea9-4cd7-a84d-ac3031b1f395.png)

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
