### ISSUE TITLE
Re-retweet

### ISSUE THREAD

**Issue by karakufire** [eramdam/BetterTweetDeck#793]
**Is your feature request related to a problem? Please describe.**
To retweet same tweets again, I have to remove that retweet, seek same tweet, retweet.
It slightly takes labor to do that all on only Tweetdeck.

**Describe the solution you'd like**
**Re-retweet** button. Also I wish you to locate it upon "Retweet dialog" or as additional menu items.

**Describe alternatives you've considered**
Open tweet(current page moves or open into other tab/window), cancel retweet and retweet again.

**Additional context**

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
