### ISSUE TITLE
Refresh columns

### ISSUE THREAD

**Issue by dnestico** [eramdam/BetterTweetDeck#795]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A refresh button on individual columns could be used for when I like a tweet on twitter.com and it doesn't show that I liked that same tweet on tweetdeck until I refresh page.

**Describe alternatives you've considered**
Refreshing page is what I normally do

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
