### ISSUE TITLE
collapsible column flyout

### ISSUE THREAD

**Issue by ashifolfi** [eramdam/BetterTweetDeck#798]
This could be very useful for things like messages/certain DMs you want easily accessible or for a certain column you want to keep an eye on without having to move it around or constantly scroll back.

The idea is for it to by sort of styled like the messages flyout/popup on standard twitter/tweetdeck when collapsed and have the standard column appearance when expanded.

I looked into doing something like this with CSS but couldn't figure out how.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
