### ISSUE TITLE
Suddenly broken tweet buttons colors?

### ISSUE THREAD

**Issue by nekohayo** [eramdam/BetterTweetDeck#799]
**Describe the bug**

I don't know why, after the latest update, Better Tweetdeck now shows the accent color in a way that breaks the tweetdeck "New tweet" button (it doesn't show its icon or label until you hover it) and the associated buttons have poor label contrast, or missing labels. See screenshots below.

**Screenshots**

![Screenshot from 2022-03-07 10-08-36](https://user-images.githubusercontent.com/479401/157061727-1f8d35bf-e2fc-4cc7-98f1-5489f6cbd57e.png)

![Screenshot from 2022-03-07 10-09-04](https://user-images.githubusercontent.com/479401/157061737-6d25e0aa-af3b-4545-9426-60a14371b7fb.png)

Note that it's not just the missing Tweet button label in this 2nd picture, but also the fact that the accent color is used as the text and border color for buttons, which has very bad contrast when atop the tweetdeck blue background color for those elements.

This is on Linux with Firefox, currently with a light theme (since it's daytime), and I don't have other extensions affecting the colors/CSS (ex.: no DarkReader activated for this site). It used to work fine until this week.

**Comment by slimelia** [comment]
Also having the same isseu: screenshots below.
![image](https://user-images.githubusercontent.com/19677816/157108947-7870be64-2bdf-4300-abd9-0b6e6bb5c015.png)
![image](https://user-images.githubusercontent.com/19677816/157108989-bbba5a99-02c7-48ff-a387-f37bdfbaea0c.png)
![image](https://user-images.githubusercontent.com/19677816/157109018-3e3176c6-51b9-4d27-9ca3-50579ca5fa97.png)

This is on Opera GX LVL3 (core: 83.0.4254.70)

**Comment by eramdam** [comment]
Yeah, this was a regression in 4.8.3. Make sure you grabbed 4.8.4 and this should be fixed.
