### ISSUE TITLE
When sending dm's BTD seems to freeze for a minute

### ISSUE THREAD

**Issue by bearachute** [eramdam/BetterTweetDeck#80]
I guess I really can't reproduce it, don't have a way to the only way to really describe it is if I send a DM it takes about 5 seconds before I can click anything else or even respond to a DM. I wish I had a way to show you this.

**Comment by eramdam** [comment]
Is there a lot of DM (>100) in the thread? Because TweetDeck (without BTD) already freezes A LOT in those conditions. You might want to check that.

**Comment by bearachute** [comment]
actually no, i have very few dms going on but it seems no matter how many
seems to freeze it up

**Comment by eramdam** [comment]
Okay okay. I will try to reproduce but even without BTD, the DM feature of TweetDeck is not very realiable in itself so it might be hard.

**Comment by bearachute** [comment]
​yeah like i explained it's a little hard to reproduce but when i'm sending
a dm, there's usually a 5 seconds freezup in the dm and then i can finally
start typing in the window again, and sometimes i can't even click home,
mentions etc until that freezup goes away. the only other extensions i have
are tampermonkey and ublock origin.
​

**Comment by eramdam** [comment]
But the more important question is: does it still happen without BTD or not?
