### ISSUE TITLE
Accent colour is not used for 'Back to home/notifications' links

### ISSUE THREAD

**Issue by hrw** [eramdam/BetterTweetDeck#805]
**Describe the bug**

I use green colour as accent. Updated to 4.8.5 and got blue '< Back to Home' link.

**To Reproduce**

1. set custom accent colour
2. reload tweetdeck
3. click some tweet
4. see error

**Expected behavior**

"< Back to Home" link uses accent colour

**Screenshots**

![obraz](https://user-images.githubusercontent.com/185508/159275141-1f23ed93-04cb-4be4-96c9-f33a25e573b2.png)

**Desktop (please complete the following information):**

- OS: Fedora Linux
- Browser Firefox
- Version 98

**Comment by eramdam** [comment]
Will be fixed in the next release!

**Comment by hrw** [comment]
Found another place - when you hover author's name:

![obraz](https://user-images.githubusercontent.com/185508/159360907-8a6c6608-cc80-4de6-ad79-97abd9f65460.png)
