### ISSUE TITLE
[Feature Request] Pre-cache video embeds

### ISSUE THREAD

**Issue by alkaris2** [eramdam/BetterTweetDeck#806]
Sometimes video embeds don't play right away with TweetDeck, or just simply outright refuse to buffer the entire video entirely, I was wondering if there would be a way to pre-fetch and pre-cache these video embeds to speedup playback?  Just something at least speedup the way TweetDeck fetches embedded videos from tweets, because it can be quite annoying when things don't play right away or having to click off and click back on the video repeatedly just to get TweetDeck to load the embedded media content properly. Other times the media embeds just simply refuse to show anything at all, and you get a default generic greyed-out video player window with no controls.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
