### ISSUE TITLE
Trending column's accent color is broken with new update

### ISSUE THREAD

**Issue by StuffOfSonny** [eramdam/BetterTweetDeck#807]
![image](https://user-images.githubusercontent.com/61560546/159560610-25e1f9d9-119d-4b7f-aef4-59cc44108473.png)

**Comment by lupomikti** [comment]
I'd like to comment this is happening in all columns for me, but with the sensitive media overlay (the original one, not the new one). The accent color is not applied to the anchors ("Tweet media display settings", "View", and "Always show me sensitive media"). This is happening as of 4.8.5 and was working correctly in 4.8.4.

**Comment by eramdam** [comment]
> I'd like to comment this is happening in all columns for me, but with the sensitive media overlay (the original one, not the new one). The accent color is not applied to the anchors ("Tweet media display settings", "View", and "Always show me sensitive media"). This is happening as of 4.8.5 and was working correctly in 4.8.4.
> 
> Edit: also, hovering over account names on a card/tile are not in the accent color.

do you have a link to a tweet that shows the warning you're talking about? I know I saw it somewhere but it's tricky to find without knowing where to look 😅
