### ISSUE TITLE
Account labels redirect to [object Object]

### ISSUE THREAD

**Issue by AlexzanDev** [eramdam/BetterTweetDeck#808]
**Describe the bug**
Government and state-affiliated media account labels on Twitter don't redirect to [their FAQ page](https://help.twitter.com/en/rules-and-policies/state-affiliated). Instead, they redirect to tweetdeck.twitter.com/[object Object].

**To Reproduce**

1. Search for a tweet from an account with a label (es. POTUS)
2. Click on the label

**Expected behavior**
The label should redirect to the label FAQ on Twitter Support's website like it does on the Twitter Web App.

**Screenshots**

![image](https://user-images.githubusercontent.com/35893655/159940433-218fbfd1-a300-4ab4-80b1-c02e235f722d.png)
![image](https://user-images.githubusercontent.com/35893655/159940464-d1c24ee8-8cd2-4850-8e2c-86b48ef0ef46.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- BTD's version is the latest (4.8.5)

**Comment by eramdam** [comment]
Will be fixed in the next release!

**Comment by AlexzanDev** [comment]
Nice! Thank you.
