### ISSUE TITLE
[Feature Request] Twitter Communities

### ISSUE THREAD

**Issue by CrocodileCroco** [eramdam/BetterTweetDeck#814]
**Is your feature request related to a problem? Please describe.**
No, Twitter just silently rolled out the communities feature

**Describe the solution you'd like**
I would like to be able to view twitter communities with BetterTweetDeck

**Describe alternatives you've considered**
Idk

**Additional context**
Proof that twitter silently rolled out this feature : https://i.ibb.co/Phfm7Q5/image.png

**Comment by eramdam** [comment]
That's all behind a private API endpoint so I can't do much
