### ISSUE TITLE
[Request] Prevent the continuous unloading of scrolled posts

### ISSUE THREAD

**Issue by harl** [eramdam/BetterTweetDeck#815]
**Is your feature request related to a problem? Please describe.**
My problem, if you'd like to call it that, is that Twitter seems to have applied the same annoying "feature" to TweetDeck that it's had on the main page already, that makes it unload posts when I scroll down/up.
How most people seem to just accept that and work with it, is beyond me, because it makes reading, searching and responding very impractical in certain situations (or when I just want to load a few more posts and search for something in all the posts that are loaded so far).
I would expect all loaded content to remain loaded the way it is on most websites. Twitter shouldn't be allowed to automatically unload content away from my browsing experience just because some puppets, for whatever reasons, want to force an arbitrary limit of simultaneously loaded posts on me.
End of rant, I guess. Sorry.

**Describe the solution you'd like**
I wish for an option to prevent Twitter from continuously unloading content when the pages/columns are being scrolled.
Please implement this!
There should be no limit to the size (height/length) of a page.
Local memory limitations or browser crashes resulting from huge web pages are my own responsibility.

**Describe alternatives you've considered**
I've considered:
- rolling my eyes until my extremely cross eyebrows stop them
- taking a deep breath and ignoring the pain
- using the main Twitter page less often
- (I was actually hoping that TweetDeck didn't have this "feature" yet and/or that BTD already made it better)
- (I went through TweetDeck's and BTD's options dialogues and didn't find anything related to it)

**Additional context**
awooooooooooooo...!

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
