### ISSUE TITLE
CSS issue in account list (new tweet panel)

### ISSUE THREAD

**Issue by MayakoLyyn** [eramdam/BetterTweetDeck#82]
The account list in its default mode has a CSS issue (see screenshot below)

![image](https://cloud.githubusercontent.com/assets/3751959/17815248/b1fb9f86-6633-11e6-8fa7-5cd031cd242d.png)

Thanks :)

**Comment by eramdam** [comment]
@MayakoLyyn the bug looks like it's fixed in 3.0.15. Can you confirm? thx.

**Comment by MayakoLyyn** [comment]
@eramdam Yeap, that issue is now resolved on my side. Thanks :)

**Comment by eramdam** [comment]
The bug re-showed up randomly. I have a fix ready, will be in next release.
