### ISSUE TITLE
Add an option to center TweetDeck on the screen 

### ISSUE THREAD

**Issue by Divalz** [eramdam/BetterTweetDeck#821]
Hello,
I would like to know how I could center the columns 
_instead of all the columns being on the left I would like it to be centered._

if not, could someone give me the custom CSS to add? 
Thx

**Comment by contextnerror** [comment]
I use:
`section.column{
    left: 165px;
}`
There might be a more efficient way to do it but so far it works. Adjust the value of "left" as needed.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
