### ISSUE TITLE
Catch pronoun.is from bio

### ISSUE THREAD

**Issue by darkphoenix** [eramdam/BetterTweetDeck#822]
The current code for finding pronouns doesn't seem to catch stuff like pronoun.is/he/him.  I'm not sure how many people actually use that site, but I've seen it a few times and it would be neat to have BetterTD catch that.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
