### ISSUE TITLE
Notifications of the same type on same tweet should stack together

### ISSUE THREAD

**Issue by warpKaiba** [eramdam/BetterTweetDeck#823]
**Is your feature request related to a problem? Please describe.**
Individual notifications don't stack, so if a post gets more than a handful of interactions it clogs up the notifications column with copies of the same tweet.

**Describe the solution you'd like**
Implement an option to let notifications of the same type for the same post to stack into one notification, like it does on twitter.com.

**Describe alternatives you've considered**
I currently have 2 notifications columns per account, one for mentions and the other for the rest of the notifications. If this was implemented, the notifications column would be more useful and I might only need one of them per account.

I have also tried making custom CSS to make the individual notifications smaller, but it's finicky. 

**Additional context**

How it is (I can make it smaller with the 'hidden media' option, but it's not that much help): 
![2022-04-14_22-55](https://user-images.githubusercontent.com/27407917/163516108-797edc71-e880-43e7-b889-10a2b79ed36d.png)

How I want it to be:
![2022-04-14_22-55_1](https://user-images.githubusercontent.com/27407917/163516111-a456cc6a-4354-4b96-b113-9e07ee15f185.png)

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
