### ISSUE TITLE
CW flag not being picked up

### ISSUE THREAD

**Issue by WizardShotTheFood** [eramdam/BetterTweetDeck#824]
**Describe the bug**
A pair of tweets that came across my timeline have identical content warnings, but have the warnings formatted slightly differently. Only one was flagged as having CWs. The one that didn't began with "( cw", while the one that did was just "cw". The parentheses seem to break the detection.

**To Reproduce**
1. Examine the following tweets in TweetDeck with content warning collapse enabled:
	False negative: https://twitter.com/KorpsPropaganda/status/1372541131725082625
	True positive: https://twitter.com/KorpsPropaganda/status/1315208344173522944

**Expected behavior**
Both tweets should have CW collapses.

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Firefox
- Version: 99.0

**Comment by eramdam** [comment]
This will be in the next release and soon in a nightly release (for Firefox), I'll link it here when it's built

**Comment by eramdam** [comment]
After running the nightly with the "fix" I've noticed it introduced a bunch of false positives so I'll need to figure out a better fix.
