### ISSUE TITLE
Feature to hide spam direct messages

### ISSUE THREAD

**Issue by kgtkr** [eramdam/BetterTweetDeck#826]
**Is your feature request related to a problem? Please describe.**
Tweetdeck shows all message requests.
It's stressful to see all the spam DMs.

**Describe the solution you'd like**
Adds the feature to hide message requests or spam DMs.
This can be resolved by intercepting the API to get the DM and removing the values with the message request flag and spam flag.

**Describe alternatives you've considered**

**Additional context**

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
