### ISSUE TITLE
Mixing relative and absolute date format

### ISSUE THREAD

**Issue by frank42hh** [eramdam/BetterTweetDeck#834]
**Is your feature request related to a problem? Please describe.**
I can set the date format to "relative" or "absolute". With "absolute" I have the option to define a second format to kick in after 24 hours. For "relative" this isn't possible.
I really like the relative formatting, it's quite handy when you're live-following a hashtag (like when a TV show is live tweeting with its followers), because you can quickly follow tweets with the relative time, but in general, it's hard to locate a tweet when it's "4d 7h 24m ago". It feels inconvenient this way.

**Describe the solution you'd like**
I would really like to have the best of both worlds. A relative date format for tweets that are below 24 hours, and an absolute format for tweets that are above.
Also, perhaps it would be possible to make the "24 hours" edible, eh, editable. Not really needed by me, but would be convenient for some users, I assume.

**Describe alternatives you've considered**
I don't see an alternative for my feature suggestion.

**Additional context**
n/a

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
