### ISSUE TITLE
gfycat links when opened in BetterTweetDeck are extremely tiny

### ISSUE THREAD

**Issue by Primeey** [eramdam/BetterTweetDeck#84]
Tweet example: https://twitter.com/Primey_/status/769500414832246784
[Here's what it looks like](https://i.imgur.com/6cJOvQ0.png)

**Comment by eramdam** [comment]
that's something I fixed a few versions ago, are you up-to-date?

**Comment by Primeey** [comment]
Hey this issue has reappeared in v3.3.0
