### ISSUE TITLE
Add "Clear from here" option in Twitter Actions

### ISSUE THREAD

**Issue by diego10arg** [eramdam/BetterTweetDeck#840]
I like to read my timeline in chronological order (oldest first) so I scroll down and go up reading.
Sometimes it gets too crowded and the "Show More" button does not work properly and keeps refreshing and making me scroll again and again and so on.

It would be nice if you can add a "Clear from here" option in the Twitter Actions bar to purge the timeline from that tweet and below (older tweets).

![image](https://user-images.githubusercontent.com/696076/182398860-df66fe85-4738-46fa-bfe8-dbaa45a5230f.png)

Thanks in advance!

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
