### ISSUE TITLE
Old Tweetdeck Icons

### ISSUE THREAD

**Issue by Coniferr** [eramdam/BetterTweetDeck#841]
I'm asking if it's possible to add a feature that allows switching between the current icons and old icons

old icons example:
![image](https://user-images.githubusercontent.com/43714528/184071288-2ebccd60-e3cd-4e1f-a460-2ebfc7bf555b.png)

**Comment by eramdam** [comment]
You could probably achieve this with Custom CSS and by loading the old icon font, I guess @chylex has something like that for TweetDuck but I'm not going to add a specific feature for this, sorry.
