### ISSUE TITLE
TweetDeck Preview, Better TweetDeck and the future

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#848]
EDIT: As of February 2023, it is clear Twitter's new management doesn't give a shit about 3rd party developers so I am **NOT** going to invest any energy about building on top of Twitter's platform anymore.
---

If you want to find me, I'll still be on [Twitter](https://twitter.com/eramdam) but I'm also (more) active on [Mastodon](https://octodon.social/@Eramdam) and [Cohost](https://cohost.org/eramdam) these days. I might build something for Mastodon ;)

Old issue body below:

---

I'm opening another issue to replace https://github.com/eramdam/BetterTweetDeck/issues/653 because quite a lot has changed since I commented there, and I figured it would act as a better redirect point for future questions/discussions about this topic.

As you may know, Twitter has started rolling out a new version of TweetDeck. How you feel about it isn't relevant since it _will_ be rolled out generally at some point anyway[^1].

### Here's how it will affect Better TweetDeck:

- It brings feature parity with Twitter Web, which is a great thing because I had to do a lot of that with BTD
- It **completely** breaks BTD due to how it's built. The new TweetDeck is the Twitter Web App + some code to handle multiple feeds/columns [^2].

### What do I plan to do about it?

[A year ago](https://github.com/eramdam/BetterTweetDeck/issues/653#issuecomment-884667920) I had said I'd poke around and see what I could do, and around the beginning of this year, I started digging more seriously into how I could feasibly rewrite BTD for it.

Unfortunately, the tech stack that TweetDeck Preview uses makes it very hard to extend it:

- [Redux](https://redux.js.org/) (state/data management) is relatively easy to poke at, and I could do some things, but it's only one piece of the puzzle
- [React](https://reactjs.org/) in conjunction with [react-native-web](https://necolas.github.io/react-native-web/) make it **very hard** to mod anything in a reliable way because the component tree of the app is just a bunch of views that are indistinguishable from each other _and_ they're all styled with machine-generated CSS classes that change depending on the underlying styles applied. All of this means that any UI or CSS mod is hard to make and maintain.

However, some of the issues I have with TweetDeck Preview aren't technical. I have been working on Better TweetDeck for more than 8 years at this point, so the thought of having to throw out all the shared knowledge of the internals of TweetDeck to start over is, at best, annoying and, at worst, kind of depressing.

After thinking about it for a long time, I've concluded that I do not want to start over on even less stable grounds. As much as BTD has been fun as a project, it involved a lot of stress because overnight, Twitter could (and did!) break BTD without any warnings, and it doesn't sound like TweetDeck Preview would be less of a moving target.
Add to this the annoyances/support issues that come with working on a browser extension for all the major browsers, and honestly? I think I want to chill for a bit.

#### For Better TweetDeck

First and foremost, as of writing this, **I'm considering Better TweetDeck to be in a feature freeze state**. Any changes I do/accept to the codebase will be bug fixes when I can gather the motivation to do so. Notably, the "biggest" change that's on the way is updating the tooling of BTD to support [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/) because Google will require it for any updates to existing extensions, so I can't escape it.

### Conclusion

First of all, I want to thank everybody who used BTD, spread the word about it, or contributed to it in any shape or form. I definitely couldn't imagine it being so big when I started working on it as a student in 2014, and it's been a wild ride ♥️

Thanks for reading, and thanks for the support for all those years!

[^1]: _When_ this rollout exactly happens hasn't been communicated. My gut feeling says it'll be sometime around early next year but don't quote me on that as I'm (obviously) not a Twitter employee!
[^2]: That's not even an exaggeration, and I have been told it's by design to avoid running into a situation where TweetDeck has to wait months before it gets a new Twitter Web feature

**Comment by fdellwing** [comment]
As already stated on Twitter in the past, I'm open to help with infrastructure/maintenance.

**Comment by eramdam** [comment]
Reserving this post for future addendums:

# Addendum about API limitations and how Skyla could/might work around them.

### Notifications 
As of now there are no real ways to get notifications about likes/retweets/tweets in the Twitter API. Clients like Spring and TweetBot have made it work by polling metrics and tweets are a regular interval and dispatching notifications accordingly. This is definitely something I could do, but no plans yet.


### Activity column
TweetDeck Preview doesn't (won't?) have it and there's no good way to replicate this feature with Twitter's API. If you think about it the math is pretty damning, let's say you follow 100 followers, then, at a regular interval you need to:
- Do 100 requests to get all of your followings' followings
- Do 100 requests to get all of your followings' likes
- Do 100 requests (at least) to get all of your followings' quote tweets/retweets

This unfortunately smashes Twitter's rate limits pretty quickly. That said, you could get creative and build some workarounds:
- Pin a user's likes as a column.
- Build a "combined column" that takes multiple feeds (multiple users' likes, for instance) and lists all of them inside one column.

Both of which would be much more feasible/easy to scale and maintain so all hope isn't completely lost if you rely on that feature 😁

**Comment by decard123** [comment]
firstly, many thanks for your app and all your work over all this time developing and supporting it.

btw, note, although it may be just the usual generic Twitter dysfunction re this function, i have not got any #BTD Tweets although i am of course a Follower?

and i just of 'lucked' into this GitHub Post

i couldn't help with any actual coding - those days are long gone.; but what i am expert on is UI/GUI design and functionality.

it is odd (to me) how Twitter is basically trashing what was a solid worthwhile app.

**Comment by Infinitay** [comment]
Came here to request a feature but stumbled upon this. Can't imagine the feeling of building a QoL extension that becomes full-fledged only to have it break and _unmaintainable_ due to something out of your control.

Thanks for everything you've done throughout the years for this and continuing to maintain support while you can. I'm looking forward to what's to come of your own Twitter client Skyla. The fact that it will be open sourced is appreciated as well.

**Comment by victor-50** [comment]
I also stumbled on this, because I was looking for a solution for polls opening in twitter in stead of tweetdeck as used to be. On the side: maybe Elon Musk could help?

**Comment by frank42hh** [comment]
Hi!

»If you want to be involved somehow, please reach out! I could definitely use the help whenever the project is a bit more laid out.«

I would like to offer my help as beta tester and provide German translation if needed.

**Comment by Mitsunee** [comment]
As someone who has maintained a BetterDiscord theme for the better part of two years I know the pain of writing custom styles for a react app that changes classNames seemingly every goddamn week... nvm them being mangled too, which is something I don't even do myself.

I'd definitely be interested in an opensource Twitter+Mastodon client. I currently got Tweetdeck and mastodon in two separate tabs, with tweetdeck managing 3 accounts that I might end up scaling down to just my public one + some private lists.

**Comment by takohachibar** [comment]
Currently, the hashtag is fixed, but it is designed not to be active in the input field when the image is loaded. Is it possible to load this image, activate it and display the cursor at the beginning of the hashtag?

**Comment by stefanhayden** [comment]
🖖  What an honor to have used your tools for so long. Your future looks bright!

**Comment by gollum2411** [comment]
I'll sure miss you </3

**Comment by lisardggY** [comment]
Thanks for your work over the years. BTD was a great example of how an open app infrastructure can make each webapp or site the jumping board or others to improve or build upon, and it's a shame that web frameworks - and web companies - are actively working against that.

**Comment by Phelagor** [comment]
Well. Every good thing will have an end someday. Only the bad stuff will last for longer or even grow.
Your decision is understandable under the current state of twitter and in what direction it is moving.

Thanks a lot for the great tool you provided to make TweetDeck a better one 👍

**Comment by icedream** [comment]
I am agreeing with the others here, your decision is very understandable. I was a heavy user of this and it's sad to go Twitter where it goes, but there's nothing to be done here anymore.

Thank you for all the efforts you put into this, it made Twitter so much better to use!

**Comment by mben42** [comment]
Your decision is understandable. I will miss BTD for sure, but before all thank you for your great work during these years!

**Comment by saulojoab** [comment]
hey, thanks for the great work during those years. kinda crazy how much i'm used to using Better TweetDeck, its so weird whenever i boot up a new computer/browser and i got the default look on TTDeck. 

im very saddened by this but i can totally feel where you're coming from, so once again: thank you for the amazing extension and i hope things work out for you!

**Comment by rapdodge** [comment]
Thanks for the great work!

Your decision is understandable. :)

**Comment by DezGDNY** [comment]
You provided a value added service. You brought snacks to the party that was twitter. Their management has officially rung the death knell. Twitter will never be any better than it is at this moment, which is a sad, sad state. It's best days are behind it.

**Comment by WanWizard** [comment]
Thanks for making my life just that little bit better :

Let us hpe that after losing his mind, Musk will also loses all his money with the stupid move of buying Twitter, which would prevent him from wreaking more havoc upon the world...

**Comment by victor-50** [comment]
The new Tweetdeck is barely manageable. Looking around for alternatives, I found  [tweetduck](https://tweetduck.chylex.com/) , an exe-shell that has some merit. Maybe [eramdam](https://github.com/eramdam) would join the team there? 

On the side, I have to defend Musk. He wouldn't have stepped in if the first amendment was respected, and in this respect he has done good things although political opponents who support the powers that be think otherwise of course. The "files" it show that Twitter made some money for their censoring.  He had to clean up a lot and that's not an easy thing to do in a short time. It still is a private enterprise so it has to earn its money. This makes understandable that the add-free tweetdeck had to change, including the fact that there were freeriders who actually made money with tweetdeck. I am willing to pay, though not € 8 a month for an ad-free tweetdeck.

**Comment by kouhaidev** [comment]
thanks for maintaining Better TweetDeck, for making the long extended months of March 2020 better, and for changing "pronouns in bio" up to "pronouns in TweetDeck". pronouns make things better :3

**Comment by victor-50** [comment]
Addition: [Congress hearing]( https://summit.news/2023/02/09/videos-former-twitter-execs-squirm-as-theyre-told-they-could-be-arrested-for-election-interference/)

**Comment by mxamber** [comment]
Just today, a friend asked me to help them set up Tweetdeck because they couldn't find the "tweet from another account" thing, and I log in and there the fugly new UI is. All my columns gone, all my account team members, everything.

Screw that shit. They really don't understand *how* many people they're driving away by cutting off devs like this.

**Comment by BlueRayi** [comment]
I thank you from the bottom of my heart for all the wonderful tools you have given us.

And I regret the fact that you had to leave with a broken heart.

**Comment by decard123** [comment]
Musk is stupid arrogant privileged entitled f*k totally out of his depth in this environment. the fact is he does not have a CLUE what he is doing: he is just thrashing around mindlessly.
the trouble with stupid people is that they usually think they are sooooo smart, and arrogant with it.

PS did you read where he was seen being very cosy with the evil reptile Murdoch recently. i wonder if he is thinking if he can wangle some sort of deal to get him out of this mess he made out of his own arrogance, hubris, and stupidity?

**Comment by KAMiKAZOW** [comment]
Wouldn't mind a Better Mastodon that improved on stuff like following accounts on different servers and such. 👍

**Comment by eramdam** [comment]
Appreciate all the messages!

Just a small PSA that this thread isn't made to debate Twitter's CEO (or anything related) and I will be hiding/deleting comments accordingly. I've kept the repo open so people can write things out but if the discussion derails I will be locking the thread/archiving the repo.

Thank you.

**Comment by EpicLPer** [comment]
> Wouldn't mind a Better Mastodon that improved on stuff like following accounts on different servers and such. 👍

I second this! I'm using Misskey and Mastodon right now, and a client that brings together all the different platforms into a TweetDeck-Like experience (even if it has to be self-hosted to access) would be such an awesome and nice thing.

**Comment by naari3** [comment]
Maybe it's gone?
I can only select the Tweetdeck Preview version in my environment, sadly.

**Comment by sekoku** [comment]
RIP. Seems it's finally dead now. M/*sk apparently killed the old version and forces everyone onto the new one even if you tell BTD to roll back or tell Twitter to delete the new ones data and exit.

You had a good run. Time to use an extension that gets around the horrible new UI until M/*sk ruins _that_

**Comment by omfgnuts** [comment]
How do i now copy dem direct links to media? T_T

**Comment by Pazanate** [comment]
Thank you for your service. Seems like BTD has finally been killed off in the latest rollouts to accounts.

**Comment by Azazellz** [comment]
This new TweetDeck is so damn bad, my God.
You can't set filters (only media\no retweets\and so on). You can't even collapse the columns, they are always active.
And all my settings, all the added columns of different users, all disappeared on re-login.
What a piece of shit.
