### ISSUE TITLE
Add an "open in twitter" option [feature request]

### ISSUE THREAD

**Issue by spamsgood** [eramdam/BetterTweetDeck#850]
It would be great if we could get an option to open tweets in the twitter app on our pc/mac. Or even open it in another tab on the regular twitter site.

**Comment by contextnerror** [comment]
You can already open posts in a new tab. The post timestamp in the top right should have a link to the original post. For posts with images, opening the image link (https://t.co/etc.) in a new tab will also bring up the post.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
