### ISSUE TITLE
2 ideas - Column - Tweet found within Geographic location / around me à la birdhunt.co

### ISSUE THREAD

**Issue by Maijin** [eramdam/BetterTweetDeck#851]
**Is your feature request related to a problem? Please describe.**

- Add a column, select "around me" column will contain tweets from that radius/geo around me using browser geoloc
- Add a column, select based on radius/geo, show a map+radius and then the column will contain tweets from that radius/geo.
Like https://birdhunt.co

**Additional context**
Useful to see what's happening like event etc. around me or a specific chosen zone

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
