### ISSUE TITLE
feature: optional reduced API fetches for collapsed columns

### ISSUE THREAD

**Issue by roycewilliams** [eramdam/BetterTweetDeck#852]
**Describe the solution you'd like**
If feasible, it would be useful if API fetches could be optionally suspended (or less frequent) for collapsed columns. This would be helpful on lower-bandwidth connections. Fetching would return to normal when the column was expanded.

**Describe alternatives you've considered**
It's possible that this can only be addressed in upstream TweetDeck.

**Comment by eramdam** [comment]
I consider Better TweetDeck to be in a feature freeze state due to the impending release of the newer TweetDeck and will instead shift my focus to building an alternative client. As such, I'm marking this issue as closed for the time being.
See the following issue for details #848
