### ISSUE TITLE
No "Re-Draft" button any more?

### ISSUE THREAD

**Issue by rx65m** [eramdam/BetterTweetDeck#863]
**Describe the bug**
"Re-Draft" button not available.

**To Reproduce**
Just look at the place where it used to be.

**Expected behavior**
Find it next to the trash can on each scheduled tweet at the scheduled column.

**Screenshots**
No need as it is not inits place.

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser chrome
- Version 105.0.5350.0

**Additional context**

**Comment by eramdam** [comment]
I'm not sure what you're talking about because it's still here on my end 
![image](https://user-images.githubusercontent.com/1409924/209688130-ba7bd63f-512c-4a08-876d-e65737953fca.png)

**Comment by rx65m** [comment]
Thank you Damien.
I apologize for my ignorance. What I was looking for was the Edit button to
edit scheduled tweets.
I'm sorry for my confusion about the name of the button.
Rex.

**Comment by eramdam** [comment]
No worries!
