### ISSUE TITLE
Tweet actions don't work on custom modals

### ISSUE THREAD

**Issue by Primeey** [eramdam/BetterTweetDeck#87]
When you click on a youtube video and it opens in tweetdeck as a fullscreen preview the tweet actions at the very bottom do nothing when clicked. [These I'm talking about](http://i.imgur.com/jUVTYAQ.png)

EDIT: It seems to only happen with **Hide background behind fullscreen previews** enabled and only on youtube videos.. Maybe it happens with all video media? It works fine for pictures. Tweet actions in fullscreen previews for gfycat links and twitch.tv streams don't work even with the background enabled.

Here's a few tweet examples: 

Twitch.tv stream: https://twitter.com/charlieINTEL/status/772524473123606528 
gfycat: https://twitter.com/Primey_/status/771299595913719808
youtube video: https://twitter.com/charlieINTEL/status/772119838189686785

**Comment by eramdam** [comment]
I looked into it and it happens with every custom modal basically, it's just a minor JS error that triggers that. Thanks for the report though!

**Comment by eramdam** [comment]
Fixed by https://github.com/eramdam/BetterTweetDeck/commit/8f963504027d01f5a8237201d34c21797759cfdc

Will be in 3.0.16
