### ISSUE TITLE
Find a way to pause scrolling on mouseover

### ISSUE THREAD

**Issue by cfjedimaster** [eramdam/BetterTweetDeck#88]
Imagine this scenario - I see a cool link in the Home column and I want to click it. I move my cursor and a split second before I click, the column updates and my click doesn't work. Or - it updates enough where I click on some other UI item that has an undesired effect, like me Favoriting something I didn't want to.

I know I can pause scrolling in a column by slightly scrolling it down, but that pauses it forever. I don't want to scroll the column down just so I can then click safely. Nor do I want to try to move/click super fast to "beat" the next update. 

What I really want is for TD to simply recognize my cursor is over the column and wait to scroll down until after I leave the column. It would be exactly like the 'scroll down' behavior. New stuff is coming in, but the column just isn't automatically scrolling.

**Comment by eramdam** [comment]
I'm closing this, unfortunately it would be plugged too deep into TD's code for me to implement this in a reliable way.

**Comment by cfjedimaster** [comment]
So I know this was closed, but I see it is an option now. "Pause column scrolling on hover." Should it actually work?

**Comment by eramdam** [comment]
It should yeah. I don't use it personally, @EntranceJew might know more since he did the feature itself 😜

**Comment by cfjedimaster** [comment]
Good enough for me - I thought it wasn't working - but it seems to work. So thanks. :)
