### ISSUE TITLE
Thin horizontal scrollbar not working since 3.0.16

### ISSUE THREAD

**Issue by mechadrops** [eramdam/BetterTweetDeck#96]
The title pretty much describes everything. With option "Thinner scrollbars" turned on, the horizontal scrollbar is still appearing as fat since today's 3.0.16 update.

Is this a bug or was it an intentional design decision?

**Comment by babolivier** [comment]
Tried it on Chromium after updating to 3.0.16, couldn't reproduce :confused:

Screenshot for proof.

![scrollbar](https://cloud.githubusercontent.com/assets/5547783/18434269/6cd3a036-78ec-11e6-8071-db73cfecfdfc.PNG)

**Comment by mechadrops** [comment]
Horizontal scrollbar is the one on the bottom 😅 
Pic:
![chrome_2016-09-12_14-43-20](https://cloud.githubusercontent.com/assets/17452575/18434800/fd0a9ee2-78f7-11e6-8566-72b5e5f7b6e3.png)

**Comment by babolivier** [comment]
Whoops, seems like I didn't get enough coffee this morning :smile: 

Indeed, this one doesn't get affected by the "thinner scrollbars" option.

**Comment by eramdam** [comment]
Dang. Will investigate.

**Comment by eramdam** [comment]
Fixed, will ship in 3.0.17 (probably tomorrow)
