### ISSUE TITLE
Remove media link only when it ends the tweet

### ISSUE THREAD

**Issue by babolivier** [eramdam/BetterTweetDeck#97]
Hey hey,

I think it'd be nicer to remove a media's link in a tweet only if this link is placed at the end of the tweet. Otherwise, we can have cases like:

> Hey, I like what you did, but I was thinking more of something like: . What do you think about that?

If the person I'm talking to uses BTD, s.he won't necessarily link that missing something after "like:" with the media displayed below. Of course, this doesn't happen if the link ends the tweet, as the embed media "replaces" its link.

This case actually just happened to me as I'm discussing (using DMs) a flyer for one of my non-profit's events with our graphic artist, and I sent him a JPG image to give him a hint on my expectations.

Thoughts?

**Comment by eramdam** [comment]
Makes total sense.

PS: you can use `they` instead of `s.he`, it's as neutral and it's easier 😜

**Comment by eramdam** [comment]
The only tricky part is to determine when the link indeed ends the tweet...
